import test from 'node:test';
import assert from 'node:assert/strict';
import { compileAutonomyOccurrenceSession, compileAutonomyOccurrenceTaskIntent } from '../src/agent-autonomy-occurrence.mjs';
const BASE = Object.freeze({ objective:'Run the bounded Kilimanjaro reliability mission', allowedAgents:['chatgpt','claude-code'], startAgent:'chatgpt', maxRounds:8, maxTasks:16, maxTotalTokens:500_000, founderActionBudget:0, date:new Date('2026-08-22T07:00:00.000Z') });
function initialIntent(session,date=new Date('2026-08-22T07:00:00.000Z')){return compileAutonomyOccurrenceTaskIntent({session,originAgent:'uberbond',targetAgent:'chatgpt',kind:'RESEARCH_REQUIRED',objective:'Inspect the current repository and produce one evidence-backed finding.',evidenceRefs:['mission:kilimanjaro'],acceptanceTests:['current main SHA is recorded'],constraints:['local-preparation-only'],tokenBudget:10_000,date});}
test('different explicit schedule occurrences produce different session and task identities',()=>{const a=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:'schedule:2026-08-22T07:00:00+03:00'}),b=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:'schedule:2026-08-22T08:00:00+03:00'});assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(a.missionKey,b.missionKey);assert.notEqual(a.sessionId,b.sessionId);assert.notEqual(initialIntent(a).taskId,initialIntent(b).taskId);});
test('recompiling the same occurrence after a later restart preserves session and task identity',()=>{const k='github-actions:run-32560000000';const a=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:k,date:new Date('2026-08-22T07:00:00Z')}),b=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:k,date:new Date('2026-08-22T07:37:41Z')});assert.notEqual(a.createdAt,b.createdAt);assert.equal(a.sessionId,b.sessionId);assert.equal(a.missionKey,b.missionKey);assert.equal(initialIntent(a,new Date('2026-08-22T07:01:00Z')).taskId,initialIntent(b,new Date('2026-08-22T07:38:00Z')).taskId);});
test('same logical mission may use an explicit stable mission key across different occurrences',()=>{const m='mission:kilimanjaro:reliability-cluster';const a=compileAutonomyOccurrenceSession({...BASE,missionKey:m,occurrenceKey:'occurrence:001'}),b=compileAutonomyOccurrenceSession({...BASE,missionKey:m,occurrenceKey:'occurrence:002'});assert.equal(a.missionKey,m);assert.equal(b.missionKey,m);assert.notEqual(a.sessionId,b.sessionId);});
test('missing occurrence identity fails closed rather than reverting to collision-prone identity',()=>{const r=compileAutonomyOccurrenceSession(BASE);assert.equal(r.ok,false);assert.deepEqual(r.reasonCodes,['occurrence-key-required']);});
test('overlong occurrence keys are rejected instead of truncating distinct occurrences into one identity',()=>{const prefix='x'.repeat(240);const a=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:`${prefix}A`});const b=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:`${prefix}B`});assert.equal(a.ok,false);assert.equal(b.ok,false);assert.deepEqual(a.reasonCodes,['occurrence-key-too-long']);assert.deepEqual(b.reasonCodes,['occurrence-key-too-long']);const c=compileAutonomyOccurrenceSession({...BASE,occurrenceKey:prefix});assert.equal(c.ok,true);assert.equal(c.occurrenceKey,prefix);});
test('overlong explicit mission keys are rejected instead of silently truncating authority identity',()=>{const missionKey='m'.repeat(241);const r=compileAutonomyOccurrenceSession({...BASE,missionKey,occurrenceKey:'occurrence:001'});assert.equal(r.ok,false);assert.deepEqual(r.reasonCodes,['mission-key-too-long']);});
test('ordinary autonomy sessions cannot be silently passed through the occurrence task compiler',async()=>{const {compileAutonomySession}=await import('../src/agent-autonomy-loop.mjs');const legacy=compileAutonomySession(BASE);const r=compileAutonomyOccurrenceTaskIntent({session:legacy,originAgent:'uberbond',targetAgent:'chatgpt',objective:'should refuse',evidenceRefs:['mission:kilimanjaro'],acceptanceTests:['must refuse']});assert.equal(r.ok,false);assert.deepEqual(r.reasonCodes,['valid-occurrence-session-required']);});
