import test from 'node:test';
import assert from 'node:assert/strict';
import { compileScheduledAutonomyRun } from '../src/agent-autonomy-scheduled-run.mjs';
import { compileRelayTaskFromIntent } from '../src/agent-autonomy-relay-adapter.mjs';
import { createGithubRelayTask } from '../src/github-relay.mjs';
const SESSION=Object.freeze({objective:'Run bounded recurring Kilimanjaro reliability work',allowedAgents:['chatgpt','claude-code'],startAgent:'chatgpt',maxRounds:8,maxTasks:16,maxTotalTokens:500_000,founderActionBudget:0});
const INITIAL=Object.freeze({originAgent:'uberbond',targetAgent:'chatgpt',kind:'RESEARCH_REQUIRED',objective:'Inspect current repository truth and return one bounded finding.',evidenceRefs:['mission:kilimanjaro'],acceptanceTests:['current main SHA is recorded'],constraints:['local-preparation-only'],tokenBudget:10_000});
function scheduled(occurrenceKey,date){return compileScheduledAutonomyRun({missionKey:'mission:kilimanjaro:reliability-cluster',occurrenceKey,session:SESSION,initialIntent:INITIAL,date});}
function relayInput(task){return {taskId:task.taskId,objective:task.objective,originAgent:task.originAgent,targetAgent:task.targetAgent,parentTask:task.parentTask,contextRefs:task.contextRefs,evidenceRefs:task.evidenceRefs,constraints:task.constraints,forbiddenActions:task.forbiddenActions,requiredOutputs:task.requiredOutputs,acceptanceTests:task.acceptanceTests,budget:task.budget,economicObjective:task.economicObjective,consequenceClass:task.consequenceClass};}
function fakeGithubClient(){const issues=[];return {issues,async listIssues(){return issues;},async createIssue(input){const issue={number:issues.length+1,html_url:`https://example.invalid/issues/${issues.length+1}`,body:input.body,labels:input.labels,state:'OPEN'};issues.push(issue);return issue;}};}
test('scheduler boundary makes later occurrences distinct at session, task and run identity',()=>{const a=scheduled('schedule:2026-08-22T07:00:00+03:00',new Date('2026-08-22T04:00:00Z')),b=scheduled('schedule:2026-08-22T08:00:00+03:00',new Date('2026-08-22T05:00:00Z'));assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(a.missionKey,b.missionKey);assert.notEqual(a.session.sessionId,b.session.sessionId);assert.notEqual(a.initialIntent.taskId,b.initialIntent.taskId);assert.notEqual(a.run.runId,b.run.runId);});
test('restart reconstruction of the same occurrence keeps session, task and run identity stable',()=>{const k='github-actions:workflow:agent-mesh:run:32560000000';const a=scheduled(k,new Date('2026-08-22T04:00:00Z')),b=scheduled(k,new Date('2026-08-22T04:41:17Z'));assert.equal(a.ok,true);assert.equal(b.ok,true);assert.notEqual(a.run.createdAt,b.run.createdAt);assert.equal(a.session.sessionId,b.session.sessionId);assert.equal(a.initialIntent.taskId,b.initialIntent.taskId);assert.equal(a.run.runId,b.run.runId);});
test('scheduler cannot inject a precomputed sessionId or taskId around the occurrence boundary',()=>{const a=compileScheduledAutonomyRun({occurrenceKey:'occurrence:attack-task-id',session:SESSION,initialIntent:{...INITIAL,taskId:'attacker-controlled'}});assert.equal(a.ok,false);assert.deepEqual(a.reasonCodes,['scheduler-cannot-inject-derived-identity']);const b=compileScheduledAutonomyRun({occurrenceKey:'occurrence:attack-session-id',session:SESSION,initialIntent:{...INITIAL,sessionId:'legacy-collision'}});assert.equal(b.ok,false);assert.deepEqual(b.reasonCodes,['scheduler-cannot-inject-derived-identity']);});
test('GitHub relay dedupes a retry of the same occurrence but queues the next occurrence separately',async()=>{const client=fakeGithubClient();const a=scheduled('schedule:occurrence:001',new Date('2026-08-22T04:00:00Z')),r=scheduled('schedule:occurrence:001',new Date('2026-08-22T04:10:00Z')),n=scheduled('schedule:occurrence:002',new Date('2026-08-22T05:00:00Z'));const ar=compileRelayTaskFromIntent(a.initialIntent,a.session,new Date('2026-08-22T04:00:00Z')),rr=compileRelayTaskFromIntent(r.initialIntent,r.session,new Date('2026-08-22T04:10:00Z')),nr=compileRelayTaskFromIntent(n.initialIntent,n.session,new Date('2026-08-22T05:00:00Z'));assert.equal(ar.taskId,rr.taskId);assert.notEqual(ar.taskId,nr.taskId);const qa=await createGithubRelayTask({client,owner:'owner',repo:'repo',input:relayInput(ar),date:new Date('2026-08-22T04:00:00Z')}),qr=await createGithubRelayTask({client,owner:'owner',repo:'repo',input:relayInput(rr),date:new Date('2026-08-22T04:10:00Z')}),qn=await createGithubRelayTask({client,owner:'owner',repo:'repo',input:relayInput(nr),date:new Date('2026-08-22T05:00:00Z')});assert.equal(qa.status,'QUEUED');assert.equal(qr.status,'ALREADY_QUEUED');assert.equal(qr.issueNumber,qa.issueNumber);assert.equal(qn.status,'QUEUED');assert.notEqual(qn.issueNumber,qa.issueNumber);assert.equal(client.issues.length,2);});
