import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { evaluateCompoundIntelligence } from '../src/compound-intelligence-evaluation.mjs';
import { evaluateSystemLevelAsiEvidence } from '../src/system-level-asi-evidence.mjs';
const packet=JSON.parse(fs.readFileSync(new URL('../artifacts/c13-invariant-cognition-v2-canonical-packet.json',import.meta.url),'utf8'));
const row=c13=>({dimension:'self-improvement',evidenceRef:'evidence://c13-v2-real-integration',independentEvaluatorRef:'evaluator://c13-v2-independent',verifierId:'c21-real-integration-verifier',verifierLineageRef:'lineage://c21-real-integration-verifier',taskPopulationHash:'e89e2e8935a6b7477cb0acc9a854914230e5a28f14dabb5efd9d43b3fabeb1ee',observedAt:'2026-09-11T17:50:00Z',baselineVerifiedAtEvaluationTime:true,thresholdFrozenBeforeEvaluation:true,freshContextHeldout:true,freshContextRetained:true,contaminationStatus:'CLEAN',evaluatorIndependent:true,compoundEvaluation:c13});
test('real C13 return authenticates directly in C21 under exact identity',()=>{const c13=evaluateCompoundIntelligence(packet);assert.equal(c13.receiptHash,'c1e4108f92f7dc63378b106d7405a131ebc37e110fe9ce08639493537dd6bcc3');assert.equal(c13.compositionId,packet.compositionId);assert.equal(c13.compositionRevision,packet.compositionRevision);const c21=evaluateSystemLevelAsiEvidence({candidateId:packet.compositionId,candidateRevision:packet.compositionRevision,dimensions:[row(c13)],observedAt:'2026-09-11T18:00:00Z'});assert.equal(c21.ok,true,JSON.stringify(c21));assert.equal(c21.counts.evidencedDimensions,1);assert.equal(c21.missingCriticalDimensions.includes('self-improvement'),false);assert.equal(c21.asiStatus,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');});
test('real C13 return refuses a different candidate revision',()=>{const c13=evaluateCompoundIntelligence(packet);const c21=evaluateSystemLevelAsiEvidence({candidateId:packet.compositionId,candidateRevision:'wrong-revision',dimensions:[row(c13)],observedAt:'2026-09-11T18:00:00Z'});assert.equal(c21.ok,false);});
