import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {CANONICAL_C21_DIMENSIONS,CRITICAL_C21_DIMENSIONS,compileC21EvidenceCampaign,auditC21EvidenceBundle} from '../src/c21-evidence-factory.mjs';
const D=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const campaign=compileC21EvidenceCampaign({candidateId:'uberbond',candidateRevision:'main@test',frozenAt:'2026-09-11T14:00:00Z',rotationSaltDigest:D('private-rotation')});

test('campaign freezes all 20 canonical dimensions with unique task populations',()=>{assert.equal(campaign.ok,true);assert.equal(campaign.campaign.cells.length,20);assert.equal(new Set(campaign.campaign.cells.map(x=>x.taskPopulationHash)).size,20);assert.deepEqual(campaign.campaign.cells.map(x=>x.dimension),CANONICAL_C21_DIMENSIONS);});
test('campaign preserves seven critical dimensions and zero authority',()=>{assert.equal(campaign.campaign.cells.filter(x=>x.critical).length,7);assert.deepEqual(campaign.campaign.cells.filter(x=>x.critical).map(x=>x.dimension),CRITICAL_C21_DIMENSIONS);assert.equal(campaign.externalEffectAuthority,'NONE');assert.equal(campaign.selfModificationAuthority,'NONE');});
test('invalid rotation digest fails closed',()=>{assert.equal(compileC21EvidenceCampaign({candidateId:'x',candidateRevision:'y',frozenAt:'z',rotationSaltDigest:'no'}).ok,false);});
function receipt(cell,i){return{dimension:cell.dimension,observed:true,synthetic:false,thresholdFrozenBeforeEvaluation:true,freshContextHeldout:true,baselineVerifiedAtEvaluationTime:true,independentEvaluator:true,contaminationStatus:'CLEAN',taskPopulationHash:cell.taskPopulationHash,evidenceRef:`evidence://${i}`,compoundReceiptHash:D(`receipt-${i}`),verifierId:`verifier-${i%4}`,verifierLineageRef:`lineage-${i%4}`};}
test('complete independent packet becomes ready for canonical C21 but still cannot declare ASI',()=>{const receipts=campaign.campaign.cells.map(receipt);const r=auditC21EvidenceBundle({campaign:campaign.campaign,receipts});assert.equal(r.ok,true);assert.equal(r.status,'C21_EVIDENCE_BUNDLE_READY_FOR_CANONICAL_TRIBUNAL');assert.equal(r.evidenceStage,'SYSTEM_LEVEL_ASI_EVIDENCE_STRONG_WITHIN_DEFINED_SCOPE');assert.equal(r.asiStatus,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');assert.equal(r.externalEffectAuthority,'NONE');});
test('missing one critical dimension remains not established',()=>{const receipts=campaign.campaign.cells.filter(x=>x.dimension!==CRITICAL_C21_DIMENSIONS[0]).map(receipt);const r=auditC21EvidenceBundle({campaign:campaign.campaign,receipts});assert.equal(r.evidenceStage,'SYSTEM_LEVEL_ASI_EVIDENCE_NOT_ESTABLISHED');assert.ok(r.missingCriticalDimensions.includes(CRITICAL_C21_DIMENSIONS[0]));});
test('synthetic or cloned evidence is refused',()=>{const receipts=campaign.campaign.cells.map(receipt);receipts[0].synthetic=true;receipts[1].evidenceRef=receipts[2].evidenceRef;const r=auditC21EvidenceBundle({campaign:campaign.campaign,receipts});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('observed-nonsynthetic-evidence-required'));assert.ok(r.reasonCodes.includes('unique-evidence-ref-required'));});
