import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent, readCognitiveJournal } from '../src/cognitive-event-journal.mjs';
import { exportCognitiveJournalSegments } from '../scripts/sovereign-context-segment-journal.mjs';
import { appendRuntimeCognitiveJournalEvent, readRuntimeCognitiveJournal } from '../scripts/sovereign-cognitive-journal-runtime.mjs';

function event(id,minute=0){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'RUNTIME_STORE_TEST',subjectId:id,summary:`Runtime store ${id}`,evidenceRefs:[`test://${id}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-11T22:${String(minute).padStart(2,'0')}:00Z`});assert.equal(out.ok,true);return out;}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ub-context-runtime-'));const legacy=path.join(root,'events.jsonl');for(let i=0;i<4;i+=1){const out=appendCognitiveJournalEvent({journalPath:legacy,compiledEvent:event(`archive-${i}`,i)});assert.equal(out.ok,true);}const snapshot=exportCognitiveJournalSegments({journalPath:legacy,outputRoot:path.join(root,'segments'),segmentSize:2});assert.equal(snapshot.ok,true);return{root,legacy,snapshotPath:snapshot.snapshotPath,tail:path.join(root,'tail.jsonl')};}

test('legacy runtime mode preserves existing journal semantics',()=>{const f=fixture();try{const read=readRuntimeCognitiveJournal({journalPath:f.legacy});assert.equal(read.ok,true);assert.equal(read.runtimeMode,'LEGACY_JSONL');assert.equal(read.entryCount,4);const appended=appendRuntimeCognitiveJournalEvent({journalPath:f.legacy,compiledEvent:event('legacy-new',8)});assert.equal(appended.ok,true);assert.equal(readCognitiveJournal(f.legacy).entryCount,5);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('layered runtime reads immutable archive plus empty hot tail',()=>{const f=fixture();try{const read=readRuntimeCognitiveJournal({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail});assert.equal(read.ok,true);assert.equal(read.runtimeMode,'ARCHIVE_PLUS_TAIL');assert.equal(read.archiveEntryCount,4);assert.equal(read.tailEntryCount,0);assert.equal(read.entryCount,4);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('layered append extends only the tail and preserves exact global sequence',()=>{const f=fixture();try{const before=fs.readFileSync(f.legacy,'utf8');const first=appendRuntimeCognitiveJournalEvent({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail,compiledEvent:event('tail-1',8)});assert.equal(first.ok,true);assert.equal(first.sequence,5);assert.equal(first.archiveEntryCount,4);assert.equal(first.tailEntryCount,1);const second=appendRuntimeCognitiveJournalEvent({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail,compiledEvent:event('tail-2',9)});assert.equal(second.ok,true);assert.equal(second.sequence,6);const read=readRuntimeCognitiveJournal({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail});assert.equal(read.entryCount,6);assert.equal(read.tailEntryCount,2);assert.equal(read.entries.at(-1).event.subjectId,'tail-2');assert.equal(fs.readFileSync(f.legacy,'utf8'),before);assert.equal((fs.statSync(f.tail).mode&0o777).toString(8),'600');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('layered runtime refuses detached or mutated tail',()=>{const f=fixture();try{const appended=appendRuntimeCognitiveJournalEvent({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail,compiledEvent:event('tail-poison',8)});assert.equal(appended.ok,true);const row=JSON.parse(fs.readFileSync(f.tail,'utf8').trim());row.previousEntryDigest='f'.repeat(64);fs.writeFileSync(f.tail,`${JSON.stringify(row)}\n`);const read=readRuntimeCognitiveJournal({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail});assert.equal(read.ok,false);assert.ok(read.reasonCodes.includes('verified-layered-tail-required'));}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('layered runtime refuses duplicate event that already exists in immutable archive',()=>{const f=fixture();try{const archive=readCognitiveJournal(f.legacy);const existing={ok:true,status:'COGNITIVE_EVENT_READY',eventId:archive.entries[0].eventId,event:archive.entries[0].event};const out=appendRuntimeCognitiveJournalEvent({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath,tailPath:f.tail,compiledEvent:existing});assert.equal(out.ok,false);assert.equal(out.status,'COGNITIVE_JOURNAL_RUNTIME_DUPLICATE');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('archive configuration without an explicit tail fails closed',()=>{const f=fixture();try{const read=readRuntimeCognitiveJournal({journalPath:f.legacy,archiveSnapshotPath:f.snapshotPath});assert.equal(read.ok,false);assert.equal(read.status,'COGNITIVE_JOURNAL_RUNTIME_CONFIGURATION_REFUSED');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
