import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { writeCognitiveJournalSegmentSnapshot } from '../src/cognitive-journal-segment-store.mjs';
import { compileContextJournalRuntimeState, verifyContextJournalRuntimeState } from '../src/context-journal-runtime-state.mjs';
import { appendConfiguredRuntimeCognitiveJournalEvent, LAYERED_REQUIRED_SENTINEL, readConfiguredRuntimeCognitiveJournal, resolveConfiguredCognitiveJournalRuntime } from '../scripts/sovereign-cognitive-journal-configured-runtime.mjs';

function event(id, minute=0){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'CONFIGURED_RUNTIME_TEST',subjectId:id,summary:`Configured runtime ${id}`,evidenceRefs:[`test://${id}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-11T23:${String(minute).padStart(2,'0')}:00Z`});assert.equal(out.ok,true);return out;}
function base(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ub-configured-runtime-'));const journal=path.join(root,'events.jsonl');for(let i=0;i<3;i+=1)assert.equal(appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event(`base-${i}`,i)}).ok,true);return{root,journal};}
function activate(f){const legacy=fs.readFileSync(f.journal,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);const snapshot=writeCognitiveJournalSegmentSnapshot({entries:legacy,outputRoot:path.join(f.root,'segments'),segmentSize:2});assert.equal(snapshot.ok,true);const compiled=compileContextJournalRuntimeState({archiveManifestId:snapshot.manifestId,archiveEntryCount:snapshot.totalEntries,archiveTipDigest:snapshot.journalTipDigest,activatedAt:'2026-09-11T23:20:00Z'});assert.equal(compiled.ok,true);fs.writeFileSync(path.join(f.root,'layered-required'),`${LAYERED_REQUIRED_SENTINEL}\n`,{mode:0o600});fs.writeFileSync(path.join(f.root,'journal-runtime.json'),`${JSON.stringify(compiled.state)}\n`,{mode:0o600});return{snapshot,state:compiled.state};}

test('runtime state is content-addressed and zero authority',()=>{const state=compileContextJournalRuntimeState({archiveManifestId:'a'.repeat(64),archiveEntryCount:3,archiveTipDigest:'b'.repeat(64),activatedAt:'2026-09-11T23:20:00Z'});assert.equal(state.ok,true);assert.match(state.state.stateId,/^[a-f0-9]{64}$/);assert.equal(state.state.tailFile,`tail-${state.state.generationId}.jsonl`);assert.equal(verifyContextJournalRuntimeState(state.state).ok,true);const widened=structuredClone(state.state);widened.externalEffectAuthority='WRITE';assert.equal(verifyContextJournalRuntimeState(widened).ok,false);});

test('no runtime state and no sentinel preserves legacy mode',()=>{const f=base();try{const out=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(out.ok,true);assert.equal(out.runtimeMode,'LEGACY_JSONL');assert.equal(out.configurationSource,'LEGACY_DEFAULT');assert.equal(out.entryCount,3);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('sentinel without runtime state refuses downgrade to stale legacy journal',()=>{const f=base();try{fs.writeFileSync(path.join(f.root,'layered-required'),`${LAYERED_REQUIRED_SENTINEL}\n`);const out=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONFIGURED_COGNITIVE_JOURNAL_RUNTIME_DOWNGRADE_REFUSED');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('verified runtime state resolves exact archive and generation tail',()=>{const f=base();try{const activated=activate(f);const resolved=resolveConfiguredCognitiveJournalRuntime({journalPath:f.journal});assert.equal(resolved.ok,true);assert.equal(resolved.runtimeState.stateId,activated.state.stateId);assert.equal(path.basename(resolved.archiveSnapshotPath),activated.snapshot.manifestId);assert.equal(path.basename(resolved.tailPath),activated.state.tailFile);const read=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(read.ok,true);assert.equal(read.runtimeMode,'ARCHIVE_PLUS_TAIL');assert.equal(read.entryCount,3);assert.equal(read.runtimeStateId,activated.state.stateId);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('configured layered append writes generation tail and leaves legacy bytes frozen',()=>{const f=base();try{const before=fs.readFileSync(f.journal,'utf8');const activated=activate(f);const out=appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('after-activation',9)});assert.equal(out.ok,true);assert.equal(out.sequence,4);assert.equal(out.runtimeMode,'ARCHIVE_PLUS_TAIL');assert.equal(out.runtimeStateId,activated.state.stateId);assert.equal(fs.readFileSync(f.journal,'utf8'),before);const tail=path.join(f.root,activated.state.tailFile);assert.equal(fs.existsSync(tail),true);assert.equal((fs.statSync(tail).mode&0o777).toString(8),'600');const read=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(read.entryCount,4);assert.equal(read.entries.at(-1).event.subjectId,'after-activation');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('state archive binding mismatch and corrupted state fail closed',()=>{const f=base();try{activate(f);const statePath=path.join(f.root,'journal-runtime.json');const state=JSON.parse(fs.readFileSync(statePath,'utf8'));state.archiveEntryCount+=1;fs.writeFileSync(statePath,JSON.stringify(state));const out=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONFIGURED_COGNITIVE_JOURNAL_RUNTIME_STATE_REFUSED');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('removing state after activation remains a hard downgrade refusal',()=>{const f=base();try{activate(f);fs.rmSync(path.join(f.root,'journal-runtime.json'));const out=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONFIGURED_COGNITIVE_JOURNAL_RUNTIME_DOWNGRADE_REFUSED');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
