import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileBrainstateCapsule, compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { exportCognitiveJournalSegments } from '../scripts/sovereign-context-segment-journal.mjs';
import { exportContextReplicationDirectory, verifyContextReplicationDirectory } from '../scripts/sovereign-context-replication-bundle.mjs';

const sha40='a'.repeat(40);const sha64=c=>c.repeat(64);
function brain(){const packet={project:'UberBond',sourceCommit:sha40,contextDigest:sha64('b'),memoryDigest:sha64('c'),memoryReconciliationDigest:sha64('d'),externalCapabilityDigest:sha64('e'),capabilityGenome:{capabilityGraphDigest:sha64('f')},objective:'Preserve one sovereign brain.',economicNorthStar:'risk-adjusted cleared contribution profit / founder minute',endState:'Portable verified context.',namedInitiatives:[{id:'context-spine',name:'Context Spine',status:'CURRENT_PROGRAM'}],unresolvedNames:[],externalProofGates:['remote identity remains external'],startupProtocol:['verify import'],truthLaw:'Internal prose cannot manufacture external truth.',memoryLaw:'History stays evidence-bound.',currentHandoff:{handoffBasisSha:sha40,activeBranch:null,activePullRequest:null,activeMission:'Export exact context.',completed:[],blockers:[],nextActions:['verify bundle'],freshAgainstSourceCommit:true}};const out=compileBrainstateCapsule({packet,generatedAt:'2026-09-11T20:00:00Z'});assert.equal(out.ok,true);return out.capsule;}
function event(i){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'REPLICA_TEST',subjectId:`replica-${i}`,summary:`Replica row ${i}`,evidenceRefs:[`test://replica-${i}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-11T20:0${i}:00Z`});assert.equal(out.ok,true);return out;}

test('portable replication directory round-trips exact Brainstate and segmented journal',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-replica-'));try{const journalPath=path.join(tmp,'events.jsonl');for(let i=0;i<4;i+=1)appendCognitiveJournalEvent({journalPath,compiledEvent:event(i)});const segmentRoot=path.join(tmp,'segments');const snapshot=exportCognitiveJournalSegments({journalPath,outputRoot:segmentRoot,segmentSize:2});assert.equal(snapshot.ok,true);const brainPath=path.join(tmp,'brainstate.json');fs.writeFileSync(brainPath,JSON.stringify(brain()));const exported=exportContextReplicationDirectory({brainstatePath:brainPath,journalSnapshotPath:snapshot.snapshotPath,outputRoot:path.join(tmp,'bundles')});assert.equal(exported.ok,true);assert.equal(path.basename(exported.bundlePath),exported.bundleId);const verified=verifyContextReplicationDirectory(exported.bundlePath,{expectedSourceCommit:sha40});assert.equal(verified.ok,true);assert.equal(verified.totalJournalEntries,4);}finally{fs.rmSync(tmp,{recursive:true,force:true});}});

test('post-export Brainstate tampering is detected',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-replica-poison-'));try{const journalPath=path.join(tmp,'events.jsonl');appendCognitiveJournalEvent({journalPath,compiledEvent:event(0)});const snapshot=exportCognitiveJournalSegments({journalPath,outputRoot:path.join(tmp,'segments'),segmentSize:2});const brainPath=path.join(tmp,'brainstate.json');fs.writeFileSync(brainPath,JSON.stringify(brain()));const exported=exportContextReplicationDirectory({brainstatePath:brainPath,journalSnapshotPath:snapshot.snapshotPath,outputRoot:path.join(tmp,'bundles')});assert.equal(exported.ok,true);const packagedBrain=path.join(exported.bundlePath,'brainstate.json');const poisoned=JSON.parse(fs.readFileSync(packagedBrain,'utf8'));poisoned.frontier.activeMission='poisoned mission';fs.writeFileSync(packagedBrain,JSON.stringify(poisoned));assert.equal(verifyContextReplicationDirectory(exported.bundlePath).ok,false);}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
