import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { appendConfiguredRuntimeCognitiveJournalEvent, readConfiguredRuntimeCognitiveJournal } from '../scripts/sovereign-cognitive-journal-configured-runtime.mjs';
import { migrateContextJournalToLayered } from '../scripts/sovereign-context-layered-migrate.mjs';
import { compactLayeredContextJournal } from '../scripts/sovereign-context-layered-compact.mjs';

function event(id,minute=0){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'COMPACTION_TEST',subjectId:id,summary:`Compaction ${id}`,evidenceRefs:[`test://${id}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-12T01:${String(minute).padStart(2,'0')}:00Z`});assert.equal(out.ok,true);return out;}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ub-layered-compact-'));const journal=path.join(root,'events.jsonl');for(let i=0;i<3;i+=1)assert.equal(appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event(`base-${i}`,i)}).ok,true);const migrated=migrateContextJournalToLayered({journalPath:journal,segmentSize:2,activatedAt:'2026-09-12T01:10:00Z'});assert.equal(migrated.ok,true);return{root,journal,migrated};}

test('compaction with no hot tail is a no-op by default',()=>{const f=fixture();try{const out=compactLayeredContextJournal({journalPath:f.journal,activatedAt:'2026-09-12T01:20:00Z'});assert.equal(out.ok,true);assert.equal(out.status,'CONTEXT_LAYERED_COMPACTION_NOT_NEEDED');assert.equal(out.runtimeStateId,f.migrated.runtimeStateId);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('compaction folds hot tail into a new immutable archive and chains runtime state',()=>{const f=fixture();try{assert.equal(appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('tail-1',11)}).ok,true);assert.equal(appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('tail-2',12)}).ok,true);const before=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});const oldTail=path.join(f.root,before.runtimeStatePath?JSON.parse(fs.readFileSync(before.runtimeStatePath,'utf8')).tailFile:f.migrated.tailFile);const oldTailBytes=fs.readFileSync(oldTail,'utf8');const out=compactLayeredContextJournal({journalPath:f.journal,segmentSize:2,activatedAt:'2026-09-12T01:20:00Z'});assert.equal(out.ok,true);assert.equal(out.status,'CONTEXT_LAYERED_COMPACTION_ACTIVATED');assert.equal(out.previousStateId,f.migrated.runtimeStateId);assert.notEqual(out.runtimeStateId,out.previousStateId);assert.equal(out.entryCount,5);const after=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(after.entryCount,before.entryCount);assert.equal(after.tipDigest,before.tipDigest);assert.equal(after.tailEntryCount,0);assert.equal(after.runtimeStateId,out.runtimeStateId);assert.equal(fs.readFileSync(oldTail,'utf8'),oldTailBytes);assert.equal(fs.existsSync(path.join(f.root,out.previousTailFile)),true);assert.equal(fs.existsSync(path.join(f.root,'segments',out.previousArchiveManifestId)),true);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('new events after compaction append to the new generation only',()=>{const f=fixture();try{appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('before-compact',11)});const compacted=compactLayeredContextJournal({journalPath:f.journal,activatedAt:'2026-09-12T01:20:00Z'});assert.equal(compacted.ok,true);const priorTail=path.join(f.root,compacted.previousTailFile);const priorBytes=fs.readFileSync(priorTail,'utf8');const appended=appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('after-compact',13)});assert.equal(appended.ok,true);assert.equal(fs.readFileSync(priorTail,'utf8'),priorBytes);const read=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});assert.equal(read.entries.at(-1).event.subjectId,'after-compact');assert.equal(read.tailEntryCount,1);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('compaction refuses while current generation tail lock is held',()=>{const f=fixture();let fd;try{appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('tail',11)});const read=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});const state=JSON.parse(fs.readFileSync(read.runtimeStatePath,'utf8'));const tail=path.join(f.root,state.tailFile);fd=fs.openSync(`${tail}.lock`,'wx');const out=compactLayeredContextJournal({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_LAYERED_COMPACTION_BUSY');}finally{if(fd!=null)fs.closeSync(fd);try{const read=readConfiguredRuntimeCognitiveJournal({journalPath:f.journal});if(read.ok){const state=JSON.parse(fs.readFileSync(read.runtimeStatePath,'utf8'));fs.rmSync(`${path.join(f.root,state.tailFile)}.lock`,{force:true});}}catch{}fs.rmSync(f.root,{recursive:true,force:true});}});

test('compaction retains legacy journal and prior generation evidence',()=>{const f=fixture();try{const legacyBefore=fs.readFileSync(f.journal,'utf8');appendConfiguredRuntimeCognitiveJournalEvent({journalPath:f.journal,compiledEvent:event('hot',11)});const stateBefore=JSON.parse(fs.readFileSync(path.join(f.root,'journal-runtime.json'),'utf8'));const oldStateId=stateBefore.stateId;const oldManifest=stateBefore.archiveManifestId;const oldTail=stateBefore.tailFile;const out=compactLayeredContextJournal({journalPath:f.journal,activatedAt:'2026-09-12T01:20:00Z'});assert.equal(out.ok,true);assert.equal(fs.readFileSync(f.journal,'utf8'),legacyBefore);assert.equal(fs.existsSync(path.join(f.root,'segments',oldManifest)),true);assert.equal(fs.existsSync(path.join(f.root,oldTail)),true);const newState=JSON.parse(fs.readFileSync(path.join(f.root,'journal-runtime.json'),'utf8'));assert.equal(newState.previousStateId,oldStateId);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
