import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { compileBrainstateCapsule, compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { exportCognitiveJournalSegments } from '../scripts/sovereign-context-segment-journal.mjs';
import { exportContextReplicationDirectory } from '../scripts/sovereign-context-replication-bundle.mjs';
import { admitContextReplicationDirectory } from '../scripts/sovereign-context-replication-admission.mjs';

const h=c=>c.repeat(64);function git(root,...args){return execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();}
function repo(root){const r=path.join(root,'repo');fs.mkdirSync(r);git(r,'init','-q');git(r,'config','user.email','test@uberbond.local');git(r,'config','user.name','UberBond Test');fs.writeFileSync(path.join(r,'x'),'1');git(r,'add','.');git(r,'commit','-qm','one');const one=git(r,'rev-parse','HEAD');fs.writeFileSync(path.join(r,'x'),'2');git(r,'commit','-qam','two');const two=git(r,'rev-parse','HEAD');const oneTree=git(r,'rev-parse',`${one}^{tree}`);const fork=git(r,'commit-tree',oneTree,'-p',one,'-m','fork');return{r,one,two,fork};}
function brain(source,name){const packet={project:'UberBond',sourceCommit:source,contextDigest:h('b'),memoryDigest:h('c'),memoryReconciliationDigest:h('d'),externalCapabilityDigest:h('e'),capabilityGenome:{capabilityGraphDigest:h('f')},objective:'Preserve one sovereign brain.',economicNorthStar:'risk-adjusted cleared contribution profit / founder minute',endState:'Admitted replicated context.',namedInitiatives:[{id:'context-spine',name:'Context Spine',status:'CURRENT_PROGRAM'}],unresolvedNames:[],externalProofGates:['remote transport remains external'],startupProtocol:['verify ancestry'],truthLaw:'Internal prose cannot manufacture external truth.',memoryLaw:'History stays evidence-bound.',currentHandoff:{handoffBasisSha:source,activeBranch:null,activePullRequest:null,activeMission:`Replicate ${name}.`,completed:[],blockers:[],nextActions:['admit candidate'],freshAgainstSourceCommit:true}};const out=compileBrainstateCapsule({packet,generatedAt:'2026-09-11T21:00:00Z'});assert.equal(out.ok,true);return out.capsule;}
function bundle(root,name,source){const dir=path.join(root,name);fs.mkdirSync(dir);const journal=path.join(dir,'events.jsonl');const event=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'ADMISSION_TEST',subjectId:name,summary:`Admission ${name}`,evidenceRefs:[`test://${name}`],truthClass:'VERIFIED_CURRENT',observedAt:'2026-09-11T21:00:00Z'});appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event});const snap=exportCognitiveJournalSegments({journalPath:journal,outputRoot:path.join(dir,'segments'),segmentSize:2});const bp=path.join(dir,'brainstate.json');fs.writeFileSync(bp,JSON.stringify(brain(source,name)));const out=exportContextReplicationDirectory({brainstatePath:bp,journalSnapshotPath:snap.snapshotPath,outputRoot:path.join(dir,'bundles')});assert.equal(out.ok,true);return out.bundlePath;}

test('cross-source candidate is admitted only when local Git proves fast-forward ancestry',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-admit-'));try{const g=repo(tmp);const current=bundle(tmp,'current',g.one);const candidate=bundle(tmp,'candidate',g.two);const out=admitContextReplicationDirectory({candidateBundlePath:candidate,currentBundlePath:current,trustedRepoRoot:g.r});assert.equal(out.ok,true);assert.equal(out.sourceAncestry.relation,'FAST_FORWARD');assert.equal(out.sourceAncestry.mergeBase,g.one);}finally{fs.rmSync(tmp,{recursive:true,force:true});}});

test('cross-source import without trusted Git proof is refused',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-admit-nogit-'));try{const g=repo(tmp);const current=bundle(tmp,'current',g.one);const candidate=bundle(tmp,'candidate',g.two);const out=admitContextReplicationDirectory({candidateBundlePath:candidate,currentBundlePath:current});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_REPLICATION_SOURCE_PROOF_REQUIRED');}finally{fs.rmSync(tmp,{recursive:true,force:true});}});

test('diverged source candidate remains refused even when both commits exist locally',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-admit-fork-'));try{const g=repo(tmp);const current=bundle(tmp,'current',g.two);const candidate=bundle(tmp,'candidate',g.fork);const out=admitContextReplicationDirectory({candidateBundlePath:candidate,currentBundlePath:current,trustedRepoRoot:g.r});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('safe-source-ancestry-required'));}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
