import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { readContextJournalRuntime, appendContextJournalRuntime, contextLayeredRequiredPath, CONTEXT_LAYERED_REQUIRED_SENTINEL } from '../src/context-journal-runtime.mjs';
import { migrateContextJournalToLayeredStore } from '../scripts/sovereign-context-journal-migrate.mjs';
import { compactContextJournalLayeredStore } from '../scripts/sovereign-context-journal-compact.mjs';

function event(id,minute=0){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'TERMINAL_JOURNAL_TEST',subjectId:id,summary:`Terminal journal ${id}`,evidenceRefs:[`test://${id}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-12T03:${String(minute).padStart(2,'0')}:00Z`});assert.equal(out.ok,true);return out;}
function fixture(count=3){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ub-terminal-journal-'));const journal=path.join(root,'events.jsonl');for(let i=0;i<count;i+=1)assert.equal(appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event(`base-${i}`,i)}).ok,true);return{root,journal};}
function descriptorHistory(root,id){return path.join(root,'journal-store','descriptors',`${id}.json`);}

test('v2 migration is downgrade protected and preserves legacy bytes and descriptor history',()=>{const f=fixture();try{const before=fs.readFileSync(f.journal,'utf8');const out=migrateContextJournalToLayeredStore({journalPath:f.journal,segmentSize:2,activatedAt:'2026-09-12T03:10:00Z'});assert.equal(out.ok,true);assert.match(out.generationId,/^[a-f0-9]{64}$/);assert.equal(out.downgradeProtected,true);assert.equal(fs.readFileSync(f.journal,'utf8'),before);const required=contextLayeredRequiredPath(f.journal);assert.equal(fs.readFileSync(required,'utf8').trim(),CONTEXT_LAYERED_REQUIRED_SENTINEL);const live=JSON.parse(fs.readFileSync(path.join(f.root,'journal-store','store.json'),'utf8'));const historical=JSON.parse(fs.readFileSync(descriptorHistory(f.root,live.descriptorId),'utf8'));assert.deepEqual(historical,live);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('activated store disappearance refuses stale legacy fallback',()=>{const f=fixture();try{migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});fs.rmSync(path.join(f.root,'journal-store'),{recursive:true,force:true});const out=readContextJournalRuntime({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_JOURNAL_DOWNGRADE_REFUSED');assert.ok(out.reasonCodes.includes('activated-layered-store-missing'));}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('sentinel-only crash window fails closed and migration can finish',()=>{const f=fixture();try{fs.writeFileSync(contextLayeredRequiredPath(f.journal),`${CONTEXT_LAYERED_REQUIRED_SENTINEL}\n`,{mode:0o600});const refused=readContextJournalRuntime({journalPath:f.journal});assert.equal(refused.ok,false);assert.equal(refused.status,'CONTEXT_JOURNAL_DOWNGRADE_REFUSED');const repaired=migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});assert.equal(repaired.ok,true);assert.equal(readContextJournalRuntime({journalPath:f.journal}).ok,true);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('duplicate cognitive event is refused across immutable archive and tail',()=>{const f=fixture();try{migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});const existing=event('base-0',0);const out=appendContextJournalRuntime({journalPath:f.journal,compiledEvent:existing});assert.equal(out.ok,false);assert.equal(out.status,'COGNITIVE_JOURNAL_DUPLICATE');const active=readContextJournalRuntime({journalPath:f.journal});assert.equal(active.entryCount,3);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('compaction atomically rotates hot tail and preserves exact descriptor lineage',()=>{const f=fixture();try{const legacyBytes=fs.readFileSync(f.journal,'utf8');const migrated=migrateContextJournalToLayeredStore({journalPath:f.journal,segmentSize:2,activatedAt:'2026-09-12T03:10:00Z'});assert.equal(appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot-1',8)}).ok,true);assert.equal(appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot-2',9)}).ok,true);const before=readContextJournalRuntime({journalPath:f.journal});assert.equal(before.tailEntryCount,2);const oldGeneration=before.generationId;const oldTail=path.join(f.root,'journal-store','generations',oldGeneration,'tail.jsonl');const oldTailBytes=fs.readFileSync(oldTail,'utf8');const oldDescriptor=JSON.parse(fs.readFileSync(path.join(f.root,'journal-store','store.json'),'utf8'));const out=compactContextJournalLayeredStore({journalPath:f.journal,segmentSize:2,activatedAt:'2026-09-12T03:20:00Z'});assert.equal(out.ok,true);assert.equal(out.status,'CONTEXT_JOURNAL_COMPACTION_VERIFIED');assert.equal(out.previousDescriptorId,migrated.descriptorId);assert.notEqual(out.generationId,oldGeneration);const after=readContextJournalRuntime({journalPath:f.journal});assert.equal(after.entryCount,before.entryCount);assert.equal(after.tipDigest,before.tipDigest);assert.equal(after.tailEntryCount,0);assert.equal(after.previousDescriptorId,before.descriptorId);assert.equal(fs.readFileSync(oldTail,'utf8'),oldTailBytes);assert.equal(fs.readFileSync(f.journal,'utf8'),legacyBytes);const newDescriptor=JSON.parse(fs.readFileSync(path.join(f.root,'journal-store','store.json'),'utf8'));const oldHistory=JSON.parse(fs.readFileSync(descriptorHistory(f.root,oldDescriptor.descriptorId),'utf8'));const newHistory=JSON.parse(fs.readFileSync(descriptorHistory(f.root,newDescriptor.descriptorId),'utf8'));assert.deepEqual(oldHistory,oldDescriptor);assert.deepEqual(newHistory,newDescriptor);assert.equal(newDescriptor.previousDescriptorId,oldDescriptor.descriptorId);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('conflicting immutable descriptor history blocks compaction',()=>{const f=fixture();try{const migrated=migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});assert.equal(migrated.ok,true);appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot-conflict',8)});const live=JSON.parse(fs.readFileSync(path.join(f.root,'journal-store','store.json'),'utf8'));fs.writeFileSync(descriptorHistory(f.root,live.descriptorId),JSON.stringify({...live,archiveEntryCount:live.archiveEntryCount+1}),{mode:0o600});const before=readContextJournalRuntime({journalPath:f.journal});assert.equal(before.ok,true);const out=compactContextJournalLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:20:00Z'});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_JOURNAL_COMPACTION_HISTORY_REFUSED');assert.ok(out.reasonCodes.includes('current-descriptor-history-conflict'));const after=readContextJournalRuntime({journalPath:f.journal});assert.equal(after.ok,true);assert.equal(after.descriptorId,before.descriptorId);assert.equal(after.tipDigest,before.tipDigest);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('new append after compaction uses only the new generation tail',()=>{const f=fixture();try{migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot-before',8)});const old=readContextJournalRuntime({journalPath:f.journal});const oldTail=path.join(f.root,'journal-store','generations',old.generationId,'tail.jsonl');const oldBytes=fs.readFileSync(oldTail,'utf8');const compacted=compactContextJournalLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:20:00Z'});assert.equal(compacted.ok,true);const appended=appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot-after',10)});assert.equal(appended.ok,true);assert.equal(appended.generationId,compacted.generationId);assert.equal(fs.readFileSync(oldTail,'utf8'),oldBytes);const active=readContextJournalRuntime({journalPath:f.journal});assert.equal(active.entries.at(-1).event.subjectId,'hot-after');assert.equal(active.tailEntryCount,1);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('compaction refuses while current tail writer lock is held',()=>{const f=fixture();let fd;let lock;try{migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot',8)});const active=readContextJournalRuntime({journalPath:f.journal});const tail=path.join(f.root,'journal-store','generations',active.generationId,'tail.jsonl');lock=`${tail}.lock`;fd=fs.openSync(lock,'wx');const out=compactContextJournalLayeredStore({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_JOURNAL_COMPACTION_BUSY');}finally{if(fd!=null)fs.closeSync(fd);if(lock)fs.rmSync(lock,{force:true});fs.rmSync(f.root,{recursive:true,force:true});}});

test('full reconstructed journal rejects a duplicate already present in a poisoned tail',()=>{const f=fixture();try{migrateContextJournalToLayeredStore({journalPath:f.journal,activatedAt:'2026-09-12T03:10:00Z'});const active=readContextJournalRuntime({journalPath:f.journal});const tail=path.join(f.root,'journal-store','generations',active.generationId,'tail.jsonl');const archiveEvent=active.entries[0];const poisoned={...archiveEvent,sequence:4,previousEntryDigest:active.tipDigest};fs.writeFileSync(tail,`${JSON.stringify(poisoned)}\n`);const out=readContextJournalRuntime({journalPath:f.journal});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_JOURNAL_LAYERED_INVALID');}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
