import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { exportCognitiveJournalSegments, verifyCognitiveJournalSegmentSnapshot } from '../scripts/sovereign-context-segment-journal.mjs';

function event(i){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'STORE_TEST',subjectId:`store-${i}`,summary:`Store row ${i}`,evidenceRefs:[`test://store-${i}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-11T21:0${i}:00Z`});assert.equal(out.ok,true);return out;}

test('filesystem snapshot is content addressed and verifies after write',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-segments-'));try{const journal=path.join(tmp,'events.jsonl');const root=path.join(tmp,'segments');for(let i=0;i<5;i+=1)assert.equal(appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event(i)}).ok,true);const exported=exportCognitiveJournalSegments({journalPath:journal,outputRoot:root,segmentSize:2});assert.equal(exported.ok,true);assert.equal(exported.segmentCount,3);assert.equal(path.basename(exported.snapshotPath),exported.manifestId);const verified=verifyCognitiveJournalSegmentSnapshot(exported.snapshotPath);assert.equal(verified.ok,true);assert.equal(verified.totalEntries,5);const reused=exportCognitiveJournalSegments({journalPath:journal,outputRoot:root,segmentSize:2});assert.equal(reused.ok,true);assert.equal(reused.status,'CONTEXT_JOURNAL_SEGMENT_SNAPSHOT_ALREADY_PRESENT');}finally{fs.rmSync(tmp,{recursive:true,force:true});}});

test('preexisting poisoned content-address directory is refused rather than trusted by name',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ub-segments-poison-'));try{const journal=path.join(tmp,'events.jsonl');const root=path.join(tmp,'segments');for(let i=0;i<3;i+=1)appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event(i)});const exported=exportCognitiveJournalSegments({journalPath:journal,outputRoot:root,segmentSize:2});assert.equal(exported.ok,true);const manifest=JSON.parse(fs.readFileSync(path.join(exported.snapshotPath,'manifest.json'),'utf8'));const descriptor=manifest.segments[0];const file=path.join(exported.snapshotPath,`segment-${String(descriptor.segmentIndex).padStart(8,'0')}-${descriptor.segmentDigest}.json`);const segment=JSON.parse(fs.readFileSync(file,'utf8'));segment.entries[0].event.summary='poison';fs.writeFileSync(file,JSON.stringify(segment));assert.equal(verifyCognitiveJournalSegmentSnapshot(exported.snapshotPath).ok,false);const retry=exportCognitiveJournalSegments({journalPath:journal,outputRoot:root,segmentSize:2});assert.equal(retry.ok,false);assert.ok(retry.reasonCodes.includes('existing-segment-snapshot-invalid'));}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
