import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent, readCognitiveJournal } from '../src/cognitive-event-journal.mjs';
import { readContextJournalRuntime, appendContextJournalRuntime } from '../src/context-journal-runtime.mjs';
import { migrateContextJournalToLayeredStore } from '../scripts/sovereign-context-journal-migrate.mjs';
import { exportCognitiveJournalSegments } from '../scripts/sovereign-context-segment-journal.mjs';
import { syncSovereignContext } from '../scripts/sovereign-context-sync.mjs';

function event(i,kind='MEMORY_UPDATE'){const out=compileContextCognitiveEvent({kind,sourceNodeId:'context-spine',subjectType:'ACTIVE_STORE_TEST',subjectId:`active-${i}`,summary:`Active layered journal row ${i}`,evidenceRefs:[`test://active-${i}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-11T21:${String(i).padStart(2,'0')}:00Z`});assert.equal(out.ok,true);return out;}
function seed(dir,count=4){const journal=path.join(dir,'events.jsonl');for(let i=0;i<count;i++){const out=appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event(i)});assert.equal(out.ok,true);}return journal;}

test('migration atomically activates archive plus global tail without rewriting legacy journal',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-active-journal-'));try{const journal=seed(dir);const before=fs.readFileSync(journal,'utf8');const legacy=readCognitiveJournal(journal);const migrated=migrateContextJournalToLayeredStore({journalPath:journal,segmentSize:2});assert.equal(migrated.ok,true);assert.equal(migrated.storageMode,'LAYERED_ARCHIVE_TAIL');assert.equal(migrated.entryCount,4);assert.equal(migrated.tipDigest,legacy.tipDigest);assert.equal(fs.readFileSync(journal,'utf8'),before);const active=readContextJournalRuntime({journalPath:journal});assert.equal(active.ok,true);assert.equal(active.storageMode,'LAYERED_ARCHIVE_TAIL');assert.deepEqual(active.eventIds,legacy.eventIds);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('post-migration append uses true global sequence and leaves legacy frozen',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-active-tail-'));try{const journal=seed(dir);const legacy=readCognitiveJournal(journal);const before=fs.readFileSync(journal,'utf8');assert.equal(migrateContextJournalToLayeredStore({journalPath:journal,segmentSize:2}).ok,true);const appended=appendContextJournalRuntime({journalPath:journal,compiledEvent:event(9)});assert.equal(appended.ok,true);assert.equal(appended.sequence,5);assert.equal(appended.previousEntryDigest,legacy.tipDigest);const active=readContextJournalRuntime({journalPath:journal});assert.equal(active.entryCount,5);assert.equal(active.tipDigest,appended.entryDigest);assert.equal(active.tailEntryCount,1);assert.equal(fs.readFileSync(journal,'utf8'),before);assert.equal(readCognitiveJournal(journal).entryCount,4);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('repeated migration verifies current layered store instead of rebuilding it',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-active-repeat-'));try{const journal=seed(dir,2);const first=migrateContextJournalToLayeredStore({journalPath:journal,segmentSize:1});assert.equal(first.ok,true);const second=migrateContextJournalToLayeredStore({journalPath:journal,segmentSize:1});assert.equal(second.ok,true);assert.equal(second.status,'CONTEXT_JOURNAL_LAYERED_ALREADY_ACTIVE');assert.equal(second.descriptorId,first.descriptorId);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('descriptor tampering fails closed instead of falling back to stale legacy file',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-active-poison-'));try{const journal=seed(dir,2);assert.equal(migrateContextJournalToLayeredStore({journalPath:journal}).ok,true);const descriptorPath=path.join(dir,'journal-store','store.json');const descriptor=JSON.parse(fs.readFileSync(descriptorPath,'utf8'));descriptor.archiveEntryCount=1;fs.writeFileSync(descriptorPath,JSON.stringify(descriptor));const out=readContextJournalRuntime({journalPath:journal});assert.equal(out.ok,false);assert.equal(out.status,'CONTEXT_JOURNAL_LAYERED_INVALID');}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('segment export after migration snapshots archive plus live tail',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-active-export-'));try{const journal=seed(dir,3);assert.equal(migrateContextJournalToLayeredStore({journalPath:journal,segmentSize:2}).ok,true);assert.equal(appendContextJournalRuntime({journalPath:journal,compiledEvent:event(8)}).ok,true);const exported=exportCognitiveJournalSegments({journalPath:journal,outputRoot:path.join(dir,'snapshots'),segmentSize:2});assert.equal(exported.ok,true);assert.equal(exported.totalEntries,4);assert.equal(exported.sourceStorageMode,'LAYERED_ARCHIVE_TAIL');}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('sovereign sync transparently checkpoints into layered tail',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-active-sync-'));try{const journal=seed(dir,1);assert.equal(migrateContextJournalToLayeredStore({journalPath:journal}).ok,true);const out=syncSovereignContext({journalPath:journal,capsuleCachePath:path.join(dir,'brain.json'),mountCachePath:path.join(dir,'mount.json'),generatedAt:'2026-09-11T21:30:00Z'});assert.equal(out.ok,true);assert.equal(out.journalStorageMode,'LAYERED_ARCHIVE_TAIL');const active=readContextJournalRuntime({journalPath:journal});assert.equal(active.ok,true);assert.ok(active.tailEntryCount>=1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
