import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileContextCognitiveEvent } from '../src/sovereign-context-fabric.mjs';
import { appendCognitiveJournalEvent } from '../src/cognitive-event-journal.mjs';
import { appendContextJournalRuntime, readContextJournalRuntime } from '../src/context-journal-runtime.mjs';
import { syncSovereignContext } from '../scripts/sovereign-context-sync.mjs';

function event(id,minute=0){const out=compileContextCognitiveEvent({kind:'MEMORY_UPDATE',sourceNodeId:'context-spine',subjectType:'SELF_MAINTENANCE_TEST',subjectId:id,summary:`Self maintenance ${id}`,evidenceRefs:[`test://${id}`],truthClass:'VERIFIED_CURRENT',observedAt:`2026-09-12T04:${String(minute).padStart(2,'0')}:00Z`});assert.equal(out.ok,true);return out;}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ub-self-maintenance-'));const journal=path.join(root,'events.jsonl');assert.equal(appendCognitiveJournalEvent({journalPath:journal,compiledEvent:event('seed',0)}).ok,true);return{root,journal};}

test('resident sync automatically migrates legacy journal once threshold is crossed',()=>{const f=fixture();try{const out=syncSovereignContext({journalPath:f.journal,capsuleCachePath:path.join(f.root,'brain.json'),mountCachePath:path.join(f.root,'mount.json'),generatedAt:'2026-09-12T04:10:00Z',autoMigrateEntries:1,autoCompactTailEntries:50});assert.equal(out.ok,true);assert.equal(out.journalStorageMode,'LAYERED_ARCHIVE_TAIL');assert.equal(out.maintenanceStatus,'CONTEXT_JOURNAL_LAYERED_MIGRATION_VERIFIED');assert.equal(out.maintenanceChanged,true);const active=readContextJournalRuntime({journalPath:f.journal});assert.equal(active.ok,true);assert.equal(active.downgradeProtected,true);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('resident sync automatically compacts a hot layered tail at threshold',()=>{const f=fixture();try{const first=syncSovereignContext({journalPath:f.journal,capsuleCachePath:path.join(f.root,'brain.json'),mountCachePath:path.join(f.root,'mount.json'),generatedAt:'2026-09-12T04:10:00Z',autoMigrateEntries:1,autoCompactTailEntries:50});assert.equal(first.ok,true);const before=readContextJournalRuntime({journalPath:f.journal});assert.equal(appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot',20)}).ok,true);const hot=readContextJournalRuntime({journalPath:f.journal});assert.equal(hot.tailEntryCount,1);const out=syncSovereignContext({journalPath:f.journal,capsuleCachePath:path.join(f.root,'brain.json'),mountCachePath:path.join(f.root,'mount.json'),generatedAt:'2026-09-12T04:20:00Z',autoMigrateEntries:1,autoCompactTailEntries:1});assert.equal(out.ok,true);assert.equal(out.maintenanceStatus,'CONTEXT_JOURNAL_COMPACTION_VERIFIED');assert.equal(out.maintenanceChanged,true);const after=readContextJournalRuntime({journalPath:f.journal});assert.equal(after.tailEntryCount,0);assert.notEqual(after.generationId,before.generationId);assert.equal(after.entries.some(row=>row.event.subjectId==='hot'),true);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test('busy compaction is deferred without blocking healthy cognition',()=>{const f=fixture();let fd;let lock;try{syncSovereignContext({journalPath:f.journal,capsuleCachePath:path.join(f.root,'brain.json'),mountCachePath:path.join(f.root,'mount.json'),generatedAt:'2026-09-12T04:10:00Z',autoMigrateEntries:1,autoCompactTailEntries:50});appendContextJournalRuntime({journalPath:f.journal,compiledEvent:event('hot-busy',21)});const active=readContextJournalRuntime({journalPath:f.journal});const tail=path.join(f.root,'journal-store','generations',active.generationId,'tail.jsonl');lock=`${tail}.lock`;fd=fs.openSync(lock,'wx',0o600);const out=syncSovereignContext({journalPath:f.journal,capsuleCachePath:path.join(f.root,'brain.json'),mountCachePath:path.join(f.root,'mount.json'),generatedAt:'2026-09-12T04:21:00Z',autoMigrateEntries:1,autoCompactTailEntries:1});assert.equal(out.ok,true);assert.equal(out.maintenanceStatus,'CONTEXT_MAINTENANCE_DEFERRED_BUSY');assert.equal(out.maintenanceDeferred,true);assert.equal(readContextJournalRuntime({journalPath:f.journal}).ok,true);}finally{if(fd!=null)fs.closeSync(fd);if(lock)fs.rmSync(lock,{force:true});fs.rmSync(f.root,{recursive:true,force:true});}});

test('invalid maintenance thresholds fail closed before touching storage',()=>{const f=fixture();try{const before=fs.readFileSync(f.journal,'utf8');const out=syncSovereignContext({journalPath:f.journal,autoMigrateEntries:0,autoCompactTailEntries:1});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('bounded-context-maintenance-thresholds-required'));assert.equal(fs.readFileSync(f.journal,'utf8'),before);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
