import test from 'node:test';
import assert from 'node:assert/strict';
import { bindReferenceIntegrityToTruthReceipt } from '../src/current-truth-reference-integrity.mjs';

const goodReference=()=>({ok:true,version:'uberbond.evidence-reference-integrity.v1.1',status:'INTERNAL_EVIDENCE_REFERENCES_RESOLVE_ON_EXACT_REPOSITORY_TREE',referenceDigest:'a'.repeat(64),trackedPathCount:100,checkedRepositoryPaths:['src/a.mjs'],bindingCounts:{rows:1,requirements:1,leafAssignments:1}});
const goodBase=()=>({ok:true,version:'uberbond.current-truth-regeneration.v1.7',status:'CURRENT_TRUTH_AND_ZERO_ORPHAN_GRAPH_REGENERATED_FOR_EXACT_SOURCE_HEAD',closureBoundary:{commercialTruth:'NOT_INFERRED',asiTruth:'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED'},businessEffectAuthority:'NONE',externalEffectLedger:{}});

test('successful truth receipt carries load-bearing reference integrity digest without replacing parent schema',()=>{const out=bindReferenceIntegrityToTruthReceipt({baseReceipt:goodBase(),referenceIntegrity:goodReference()});assert.equal(out.ok,true);assert.equal(out.version,'uberbond.current-truth-regeneration.v1.7');assert.equal(out.evidenceReferenceIntegrity.wrapperVersion,'uberbond.current-truth-reference-integrity.v1');assert.equal(out.evidenceReferenceIntegrity.verifierVersion,'uberbond.evidence-reference-integrity.v1.1');assert.equal(out.evidenceReferenceIntegrity.referenceDigest,'a'.repeat(64));assert.deepEqual(out.evidenceReferenceIntegrity.bindingCounts,{rows:1,requirements:1,leafAssignments:1});assert.equal(out.closureBoundary.internalEvidenceReferenceTruth,'EXACT_REPOSITORY_REFERENCES_RESOLVED_AND_EXACT_ROW_REQUIREMENT_LEAF_ASSIGNMENTS_BOUND_TO_CANONICAL_COVERAGE_STATE');assert.equal(out.closureBoundary.commercialTruth,'NOT_INFERRED');assert.equal(out.closureBoundary.asiTruth,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');});
test('missing reference integrity blocks an otherwise green truth receipt',()=>{const out=bindReferenceIntegrityToTruthReceipt({baseReceipt:goodBase(),referenceIntegrity:{ok:false,reasonCodes:['missing-source-module-reference:R:src/ghost.mjs']}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('internal-evidence-reference-integrity-required'));assert.ok(out.reasonCodes.includes('missing-source-module-reference:R:src/ghost.mjs'));});
test('reference integrity cannot overwrite an existing base refusal',()=>{const base={ok:false,status:'CURRENT_TRUTH_REGENERATION_REFUSED',reasonCodes:['coverage-head-mismatch'],businessEffectAuthority:'NONE'};const out=bindReferenceIntegrityToTruthReceipt({baseReceipt:base,referenceIntegrity:goodReference()});assert.deepEqual(out,base);});
