import test from 'node:test';
import assert from 'node:assert/strict';
import { compileDistributionPortfolio, evaluateReferralCommission, motionEvidenceFromCommercialLearning, normalizeDistributionMotion } from '../src/distribution-control-plane.mjs';

const now='2026-08-28T20:00:00Z';
function motion(overrides={}){return {id:'owned-content',type:'OWNED_CONTENT',capabilityRef:'src/content-engine.mjs',configured:true,evidence:{verifiedOutcomeCount:0,clearedPaymentCount:0,contributionProfitPerOwnerMinuteCents:null,quality:'NO_VERIFIED_OUTCOMES',measuredAt:null},safety:{suppressionClear:true,complaintClear:true,senderHealthClear:true},...overrides};}
function measured(id,type,profit,count=10){return motion({id,type,evidence:{verifiedOutcomeCount:count,clearedPaymentCount:count,contributionProfitPerOwnerMinuteCents:profit,quality:'MEASURED_LOCAL_RECEIPTS',measuredAt:'2026-08-28T19:00:00Z'}});}

test('synthetic or model score cannot become economic weight',()=>{const r=normalizeDistributionMotion(motion({evidence:{verifiedOutcomeCount:10,clearedPaymentCount:10,contributionProfitPerOwnerMinuteCents:999,quality:'MODEL_ESTIMATE',measuredAt:'2026-08-28T19:00:00Z'}}));assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('economic-score-requires-measured-local-receipts'));});
test('unconfigured channel is blocked rather than treated as an experiment success',()=>{const r=compileDistributionPortfolio({motions:[motion({configured:false})],now});assert.equal(r.ok,true);assert.equal(r.plan.length,0);assert.ok(r.blockers[0].reasonCodes.includes('provider-or-channel-not-configured'));});
test('paid media requires budget authority, economics proof and measured positive payments',()=>{const base=measured('paid','PAID_MEDIA',100,3);const blocked=compileDistributionPortfolio({motions:[base],now});assert.equal(blocked.plan.length,0);assert.ok(blocked.blockers[0].reasonCodes.includes('paid-media-budget-authority-required'));const ok=compileDistributionPortfolio({motions:[{...base,budgetAuthorityRef:'budget:1',economicsProofRef:'econ:1'}],now});assert.equal(ok.plan.length,1);assert.equal(ok.plan[0].externalAction,'DISABLED');});
test('outbound complaint suppression and sender-health gates dominate economics',()=>{const out=measured('out','OUTBOUND_EMAIL',500,30);for(const safety of [{suppressionClear:false,complaintClear:true,senderHealthClear:true},{suppressionClear:true,complaintClear:false,senderHealthClear:true},{suppressionClear:true,complaintClear:true,senderHealthClear:false}]){const r=compileDistributionPortfolio({motions:[{...out,safety}],now});assert.equal(r.plan.length,0);assert.ok(r.blockers[0].reasonCodes.includes('outbound-safety-gate-not-clear'));}});
test('stale measured economics cannot drive exploitation',()=>{const old=measured('old','PARTNER_WHITE_LABEL',300,30);old.evidence.measuredAt='2026-01-01T00:00:00Z';const r=compileDistributionPortfolio({motions:[old],now});assert.equal(r.plan.length,0);assert.ok(r.blockers[0].reasonCodes.includes('economic-evidence-stale'));});
test('future-dated economics evidence fails closed instead of appearing fresh',()=>{const m=measured('future','PARTNER_WHITE_LABEL',100,10);m.evidence.measuredAt='2026-08-29T20:00:00Z';const r=compileDistributionPortfolio({motions:[m],now});assert.equal(r.plan.length,0);assert.ok(r.blockers[0].reasonCodes.includes('economic-evidence-future-dated'));});
test('measured non-positive economics is explicitly blocked rather than silently omitted or re-explored',()=>{for(const profit of [0,-1,-500]){const r=compileDistributionPortfolio({motions:[measured(`loss-${profit}`,'OWNED_CONTENT',profit,10)],now});assert.equal(r.plan.length,0);assert.ok(r.blockers[0].reasonCodes.includes('measured-economics-non-positive'));}});
test('portfolio imposes a hard 50 percent single-motion concentration cap',()=>{const r=compileDistributionPortfolio({motions:[measured('a','PARTNER_WHITE_LABEL',1000,30),measured('b','OWNED_CONTENT',10,30),motion({id:'c',type:'PRODUCT_LED_DIAGNOSTIC'})],now,explorationSlots:1});assert.ok(r.plan.every(x=>x.allocationShare<=0.5));assert.equal(r.concentrationCap,0.5);});
test('exploration of unproven low-consequence channels is preparation-only and never economic truth',()=>{const r=compileDistributionPortfolio({motions:[motion({id:'content'}),motion({id:'diagnostic',type:'PRODUCT_LED_DIAGNOSTIC'})],now,explorationSlots:2});assert.equal(r.plan.length,2);assert.ok(r.plan.every(x=>x.role==='EXPLORE'&&x.measuredScore===null&&x.externalAction==='DISABLED'));});
test('portfolio is deterministic for same evidence apart from timestamp input',()=>{const motions=[measured('a','PARTNER_WHITE_LABEL',100,10),measured('b','OWNED_CONTENT',80,10)];const a=compileDistributionPortfolio({motions,now});const b=compileDistributionPortfolio({motions,now});assert.equal(a.portfolioId,b.portfolioId);assert.deepEqual(a.plan,b.plan);});
test('raw PII content and secrets are rejected from allocator state',()=>{const r=normalizeDistributionMotion(motion({email:'x@example.com',apiToken:'x'}));assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('raw-pii-content-or-secret-prohibited'));});
test('referral commission basis exists only after canonical cleared payment',()=>{const no=evaluateReferralCommission({referralAttributionRef:'ref:1',canonicalPaymentTruth:{truthLevel:'OBSERVED_OUTCOME',amountCents:5000,providerEventId:'x'}});assert.equal(no.status,'NO_REFERRAL_COMMISSION_BASIS');const yes=evaluateReferralCommission({referralAttributionRef:'ref:1',canonicalPaymentTruth:{truthLevel:'CLEARED_PAYMENT',amountCents:5000,providerEventId:'pay_evt_1'}});assert.equal(yes.status,'REFERRAL_COMMISSION_BASIS_PROVEN');assert.equal(yes.commissionAuthority,'NONE_REQUIRES_SEPARATE_CONTRACT_AND_PAYMENT_PROCESS');});
test('unknown or contradictory outcome does not count as success',()=>{const m=motion({id:'x',evidence:{verifiedOutcomeCount:5,clearedPaymentCount:0,contributionProfitPerOwnerMinuteCents:null,quality:'NO_VERIFIED_OUTCOMES',measuredAt:null}});const r=compileDistributionPortfolio({motions:[m],now});assert.equal(r.plan[0].role,'EXPLORE');assert.equal(r.plan[0].measuredScore,null);});
test('all planner operations have a canonical zero external-effect ledger',()=>{const r=compileDistributionPortfolio({motions:[motion()],now});assert.equal(r.businessEffectAuthority,'NONE');assert.deepEqual(r.externalEffectLedger,{providerCalls:0,messages:0,purchases:0,deployments:0,credentialChanges:0,dnsChanges:0,productionMutations:0,spendCents:0});assert.equal(r.authorization.messages,'DISABLED');assert.equal(r.authorization.spend,'DISABLED');});
test('commercial-learning bridge accepts only canonical measured local receipt groups',()=>{const summary={ok:true,learningId:'learn_1',timestamp:'2026-08-28T19:00:00Z',groups:[{channelId:'partner',quality:'MEASURED_LOCAL_RECEIPTS',verifiedOutcomeCount:5,clearedPaymentCount:5,contributionProfitPerOwnerMinuteCents:250}]};const good=motionEvidenceFromCommercialLearning(summary,'partner');assert.equal(good.status,'VERIFIED_CHANNEL_ECONOMICS_READY');assert.equal(good.evidence.contributionProfitPerOwnerMinuteCents,250);const synthetic=motionEvidenceFromCommercialLearning({ok:true,timestamp:'2026-08-28T19:00:00Z',groups:[{channelId:'partner',quality:'MODEL_ESTIMATE',verifiedOutcomeCount:5,clearedPaymentCount:5,contributionProfitPerOwnerMinuteCents:9999}]},'partner');assert.equal(synthetic.status,'NO_VERIFIED_CHANNEL_ECONOMICS');assert.equal(synthetic.evidence.contributionProfitPerOwnerMinuteCents,null);});
