import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {compileExecutionLeafContinuation,recordExecutionLeafResult,requestExecutionLeafRetry,buildExecutionLeafContinuationCheckpoint,resumeExecutionLeafContinuation,EXECUTION_LEAF_RESULT_ATTESTATION_VERSION} from '../src/execution-leaf-continuation.mjs';
const d=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const HEAD='a'.repeat(40),R='b'.repeat(64),E='e'.repeat(64),S='1'.repeat(64),B='2'.repeat(64),S2='3'.repeat(64),B2='4'.repeat(64),NOW=Date.parse('2026-09-09T12:00:00Z'),EXP='2026-09-09T13:00:00.000Z';
const {publicKey:pub,privateKey:priv}=crypto.generateKeyPairSync('ed25519');const PUBLIC=pub.export({type:'spki',format:'pem'});
function graph(){const requirements=[{id:'r1'}],leaves=[{leafId:'a',predecessors:[]},{leafId:'b',predecessors:['a']}],topologicalWaves=[['a'],['b']],criticalPath=['a','b'];const g={ok:true,status:'ZERO_ORPHAN_EXECUTION_LEAF_GRAPH_COMPILED',sourceCommit:HEAD,requirements,leaves,topologicalWaves,criticalPath};g.graphDigest=d({sourceCommit:g.sourceCommit,requirements,leaves,topologicalWaves,criticalPath});return g;}
function signed(g,leafId,status,{receiptDigest=R,evidenceRefs=['ev:1'],authorityEpoch=E,expiresAt=EXP,strategyFingerprint=S,blockerFingerprint=B,key=priv,fingerprintKey=pub}={}){const envelope={version:EXECUTION_LEAF_RESULT_ATTESTATION_VERSION,sourceCommit:g.sourceCommit,graphDigest:g.graphDigest,leafId,status,receiptDigest,evidenceRefs:[...new Set(evidenceRefs)].sort(),authorityEpoch,expiresAt,strategyFingerprint,blockerFingerprint};const fp=d(fingerprintKey.export({type:'spki',format:'der'}));return{status,receiptDigest,evidenceRefs,authorityEpoch,expiresAt,strategyFingerprint,blockerFingerprint,attestation:{version:EXECUTION_LEAF_RESULT_ATTESTATION_VERSION,publicKeyFingerprint:fp,signatureBase64:crypto.sign(null,Buffer.from(JSON.stringify(envelope)),key).toString('base64')}};}
function compiled(g,maxAttempts=3){return compileExecutionLeafContinuation({graph:g,maxAttempts,trustedVerifierPublicKeyPem:PUBLIC});}
test('canonical DAG initializes only predecessor-free leaves runnable',()=>{const x=compiled(graph());assert.equal(x.ok,true);assert.deepEqual(x.state.runnableLeafIds,['a']);assert.equal(x.businessEffectAuthority,'NONE');});
test('verified completion unlocks dependent leaf',()=>{const g=graph(),x=compiled(g);const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:signed(g,'a','COMPLETED'),verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(y.ok,true);assert.deepEqual(y.state.runnableLeafIds,['b']);});
test('arbitrary digest plus COMPLETED cannot unlock dependency',()=>{const g=graph(),x=compiled(g);const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:{status:'COMPLETED',receiptDigest:R,evidenceRefs:['ev:1'],authorityEpoch:E,expiresAt:EXP,strategyFingerprint:S,blockerFingerprint:B},verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(y.ok,false);assert.deepEqual(x.state.runnableLeafIds,['a']);assert.ok(y.reasonCodes.includes('independent-result-attestation-required'));});
test('attacker key cannot replace pinned verifier',()=>{const g=graph(),x=compiled(g);const attacker=crypto.generateKeyPairSync('ed25519');const r=signed(g,'a','COMPLETED',{key:attacker.privateKey,fingerprintKey:attacker.publicKey});const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:r,verifierPublicKeyPem:attacker.publicKey.export({type:'spki',format:'pem'}),now:NOW});assert.equal(y.ok,false);assert.ok(y.reasonCodes.includes('trusted-verifier-key-required'));});
test('expired evidence cannot complete',()=>{const g=graph(),x=compiled(g);const r=signed(g,'a','COMPLETED',{expiresAt:'2026-09-09T11:59:59.000Z'});const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:r,verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(y.ok,false);assert.ok(y.reasonCodes.includes('fresh-bounded-evidence-expiry-required'));});
test('same terminal replay is idempotent and conflicting replay refuses',()=>{const g=graph(),x=compiled(g);const r=signed(g,'a','COMPLETED');const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:r,verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(recordExecutionLeafResult({graph:g,state:y.state,leafId:'a',result:r,verifierPublicKeyPem:PUBLIC,now:NOW}).status,'EXECUTION_LEAF_RESULT_IDEMPOTENT');const c=signed(g,'a','COMPLETED',{receiptDigest:'c'.repeat(64)});assert.ok(recordExecutionLeafResult({graph:g,state:y.state,leafId:'a',result:c,verifierPublicKeyPem:PUBLIC,now:NOW}).reasonCodes.includes('conflicting-terminal-replay'));});
test('failed strategy blocks rather than auto-retrying',()=>{const g=graph(),x=compiled(g,2);const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:signed(g,'a','FAILED'),verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(y.state.nodes.a.status,'BLOCKED');assert.deepEqual(y.state.runnableLeafIds,[]);});
test('identical failed strategy with no new evidence cannot reopen',()=>{const g=graph(),x=compiled(g,2);const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:signed(g,'a','FAILED'),verifierPublicKeyPem:PUBLIC,now:NOW});const retry=signed(g,'a','RETRY_APPROVED',{receiptDigest:'c'.repeat(64)});const z=requestExecutionLeafRetry({graph:g,state:y.state,leafId:'a',retry,verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(z.ok,false);assert.ok(z.reasonCodes.includes('new-evidence-and-changed-strategy-or-blocker-required'));});
test('new evidence plus changed strategy admits one fenced retry',()=>{const g=graph(),x=compiled(g,2);const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:signed(g,'a','FAILED'),verifierPublicKeyPem:PUBLIC,now:NOW});const retry=signed(g,'a','RETRY_APPROVED',{receiptDigest:'c'.repeat(64),evidenceRefs:['ev:1','ev:2'],strategyFingerprint:S2,blockerFingerprint:B2});const z=requestExecutionLeafRetry({graph:g,state:y.state,leafId:'a',retry,verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(z.ok,true);assert.equal(z.state.nodes.a.status,'PENDING_RETRY');const bad=recordExecutionLeafResult({graph:g,state:z.state,leafId:'a',result:signed(g,'a','COMPLETED',{receiptDigest:'d'.repeat(64),evidenceRefs:['ev:2'],strategyFingerprint:S,blockerFingerprint:B}),verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(bad.ok,false);assert.ok(bad.reasonCodes.includes('result-does-not-match-admitted-retry-strategy'));const good=recordExecutionLeafResult({graph:g,state:z.state,leafId:'a',result:signed(g,'a','COMPLETED',{receiptDigest:'d'.repeat(64),evidenceRefs:['ev:2'],strategyFingerprint:S2,blockerFingerprint:B2}),verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(good.ok,true);assert.deepEqual(good.state.runnableLeafIds,['b']);});
test('dependency skipping is refused',()=>{const g=graph(),x=compiled(g);const out=recordExecutionLeafResult({graph:g,state:x.state,leafId:'b',result:signed(g,'b','COMPLETED'),verifierPublicKeyPem:PUBLIC,now:NOW});assert.ok(out.reasonCodes.includes('leaf-not-currently-runnable'));});
test('tampered canonical graph is refused',()=>{const g=graph();g.leaves[0].predecessors=['b'];assert.equal(compileExecutionLeafContinuation({graph:g,trustedVerifierPublicKeyPem:PUBLIC}).ok,false);});
test('tampered continuation state cannot unlock a dependency',()=>{const g=graph(),x=compiled(g);const forged=structuredClone(x.state);forged.nodes.a.status='COMPLETED';forged.runnableLeafIds=['b'];const out=recordExecutionLeafResult({graph:g,state:forged,leafId:'b',result:signed(g,'b','COMPLETED'),verifierPublicKeyPem:PUBLIC,now:NOW});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('valid-untampered-continuation-state-required'));});
test('retry ceiling is part of state identity and cannot be inflated after compile',()=>{const g=graph(),x=compiled(g,2);const forged=structuredClone(x.state);forged.maxAttempts=20;assert.equal(recordExecutionLeafResult({graph:g,state:forged,leafId:'a',result:signed(g,'a','FAILED'),verifierPublicKeyPem:PUBLIC,now:NOW}).ok,false);});
test('checkpoint binds exact state and exact source revision',()=>{const g=graph(),x=compiled(g);const cp=buildExecutionLeafContinuationCheckpoint({graph:g,state:x.state});assert.equal(cp.ok,true);assert.equal(resumeExecutionLeafContinuation({graph:g,state:x.state,checkpoint:cp.checkpoint,currentSourceCommit:HEAD}).ok,true);assert.ok(resumeExecutionLeafContinuation({graph:g,state:x.state,checkpoint:cp.checkpoint,currentSourceCommit:'d'.repeat(40)}).reasonCodes.includes('source-revision-changed-reconciliation-required'));});
test('checkpoint mutation cannot resume',()=>{const g=graph(),x=compiled(g);const cp=buildExecutionLeafContinuationCheckpoint({graph:g,state:x.state}).checkpoint;cp.status='COMPLETED';assert.equal(resumeExecutionLeafContinuation({graph:g,state:x.state,checkpoint:cp,currentSourceCommit:HEAD}).ok,false);});
test('checkpoint cannot be minted from mutated state',()=>{const g=graph(),x=compiled(g);const forged=structuredClone(x.state);forged.status='COMPLETED';assert.equal(buildExecutionLeafContinuationCheckpoint({graph:g,state:forged}).ok,false);});
test('continuation never creates quota, identity-cycle, provider or business authority',()=>{const g=graph(),x=compiled(g);assert.equal(x.resourceLaw.quotaEvasionAllowed,false);assert.equal(x.resourceLaw.identityCyclingAllowed,false);assert.equal(x.resourceLaw.providerAuthorityCreated,false);assert.equal(x.businessEffectAuthority,'NONE');});
