import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {compileExecutionLeafContinuation,recordExecutionLeafResult,buildExecutionLeafContinuationCheckpoint,resumeExecutionLeafContinuation} from '../src/execution-leaf-continuation.mjs';
const d=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const HEAD='a'.repeat(40),R='b'.repeat(64);
function graph(){const requirements=[{id:'r1'}],leaves=[{leafId:'a',predecessors:[]},{leafId:'b',predecessors:['a']}],topologicalWaves=[['a'],['b']],criticalPath=['a','b'];const g={ok:true,status:'ZERO_ORPHAN_EXECUTION_LEAF_GRAPH_COMPILED',sourceCommit:HEAD,requirements,leaves,topologicalWaves,criticalPath};g.graphDigest=d({sourceCommit:g.sourceCommit,requirements,leaves,topologicalWaves,criticalPath});return g;}
test('canonical DAG initializes only predecessor-free leaves runnable',()=>{const x=compileExecutionLeafContinuation({graph:graph()});assert.equal(x.ok,true);assert.deepEqual(x.state.runnableLeafIds,['a']);assert.equal(x.businessEffectAuthority,'NONE');});
test('completion unlocks dependent leaf with proof receipt',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:{status:'COMPLETED',receiptDigest:R,evidenceRefs:['t']}});assert.deepEqual(y.state.runnableLeafIds,['b']);assert.equal(y.state.receipts.a.receiptDigest,R);});
test('same terminal replay is idempotent and conflicting replay refuses',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:{status:'COMPLETED',receiptDigest:R}});assert.equal(recordExecutionLeafResult({graph:g,state:y.state,leafId:'a',result:{status:'COMPLETED',receiptDigest:R}}).status,'EXECUTION_LEAF_RESULT_IDEMPOTENT');assert.ok(recordExecutionLeafResult({graph:g,state:y.state,leafId:'a',result:{status:'COMPLETED',receiptDigest:'c'.repeat(64)}}).reasonCodes.includes('conflicting-terminal-replay'));});
test('failed leaf retries locally then terminates at bound',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g,maxAttempts:2});const y=recordExecutionLeafResult({graph:g,state:x.state,leafId:'a',result:{status:'FAILED',receiptDigest:R}});assert.equal(y.state.nodes.a.status,'PENDING_RETRY');const z=recordExecutionLeafResult({graph:g,state:y.state,leafId:'a',result:{status:'FAILED',receiptDigest:'c'.repeat(64)}});assert.equal(z.state.nodes.a.status,'FAILED_TERMINAL');assert.equal(z.state.status,'DEGRADED');});
test('dependency skipping is refused',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});assert.ok(recordExecutionLeafResult({graph:g,state:x.state,leafId:'b',result:{status:'COMPLETED',receiptDigest:R}}).reasonCodes.includes('leaf-not-currently-runnable'));});
test('tampered canonical graph is refused',()=>{const g=graph();g.leaves[0].predecessors=['b'];assert.equal(compileExecutionLeafContinuation({graph:g}).ok,false);});
test('tampered continuation state cannot unlock a dependency',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});const forged=structuredClone(x.state);forged.nodes.a.status='COMPLETED';forged.runnableLeafIds=['b'];const out=recordExecutionLeafResult({graph:g,state:forged,leafId:'b',result:{status:'COMPLETED',receiptDigest:R}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('valid-untampered-continuation-state-required'));});
test('retry ceiling is part of state identity and cannot be inflated after compile',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g,maxAttempts:2});const forged=structuredClone(x.state);forged.maxAttempts=20;assert.equal(recordExecutionLeafResult({graph:g,state:forged,leafId:'a',result:{status:'FAILED',receiptDigest:R}}).ok,false);});
test('checkpoint binds exact state and exact source revision',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});const cp=buildExecutionLeafContinuationCheckpoint({graph:g,state:x.state});assert.equal(cp.ok,true);assert.equal(resumeExecutionLeafContinuation({graph:g,state:x.state,checkpoint:cp.checkpoint,currentSourceCommit:HEAD}).ok,true);assert.ok(resumeExecutionLeafContinuation({graph:g,state:x.state,checkpoint:cp.checkpoint,currentSourceCommit:'d'.repeat(40)}).reasonCodes.includes('source-revision-changed-reconciliation-required'));});
test('checkpoint mutation cannot resume',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});const cp=buildExecutionLeafContinuationCheckpoint({graph:g,state:x.state}).checkpoint;cp.status='COMPLETED';assert.equal(resumeExecutionLeafContinuation({graph:g,state:x.state,checkpoint:cp,currentSourceCommit:HEAD}).ok,false);});
test('checkpoint cannot be minted from mutated state',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});const forged=structuredClone(x.state);forged.status='COMPLETED';assert.equal(buildExecutionLeafContinuationCheckpoint({graph:g,state:forged}).ok,false);});
test('continuation never creates quota, identity-cycle, provider or business authority',()=>{const g=graph(),x=compileExecutionLeafContinuation({graph:g});assert.equal(x.resourceLaw.quotaEvasionAllowed,false);assert.equal(x.resourceLaw.identityCyclingAllowed,false);assert.equal(x.resourceLaw.providerAuthorityCreated,false);assert.equal(x.businessEffectAuthority,'NONE');});
