import test from 'node:test';
import assert from 'node:assert/strict';
import {
  CRM_PROVIDER_CAPABILITIES, compileCrmIngestPatch, compileCrmWriteCommand, createUnconfiguredCrmProviderAdapter,
  normalizeCrmObservation, normalizeCrmWriteOutcome, validateCrmProviderAdapter
} from '../src/external-crm-sync-contract.mjs';

function observation(overrides = {}) { return { provider: 'twenty', providerEventId: 'evt_1', objectType: 'OPPORTUNITY', externalObjectRef: 'opp_1', providerVersionRef: 'v7', fields: [{ field: 'pipeline-stage', valueRef: 'stage_qualified' }], providerReceiptRef: 'provider_receipt_1', observedAt: '2026-08-28T15:50:00.000Z', receivedAt: '2026-08-28T15:50:01.000Z', ...overrides }; }
function command(overrides = {}) { return { operation: 'UPDATE', occurrenceKey: 'crm_sync_123', objectType: 'OPPORTUNITY', canonicalObjectRef: 'opportunity_123', externalObjectRef: 'opp_1', fields: [{ field: 'pipeline-stage', valueRef: 'stage_won' }], authorityReceiptRef: 'authority_receipt_1', idempotencyKey: 'crm_sync_123_v1', ...overrides }; }

test('CRM observations are provider-evidenced reference-only facts with no canonical truth authority', () => { const result = normalizeCrmObservation(observation()); assert.equal(result.ok, true); assert.equal(result.observation.canonicalTruthAuthority, 'NONE'); assert.equal(result.businessEffectAuthority, 'NONE'); });

test('CRM cannot author payment, accepted delivery, renewal, consent, suppression, or authority truth inbound', () => { for (const field of ['payment-status','delivery-accepted','renewal-status','consent-status','suppression-status','authority-status']) { const normalized = normalizeCrmObservation(observation({ fields: [{ field, valueRef: 'claimed_true' }] })); assert.equal(normalized.ok, true, field); const patch = compileCrmIngestPatch({ observation: normalized.observation, allowedOperationalFields: [field] }); assert.equal(patch.ok, false, field); assert.ok(patch.reasonCodes.includes('crm-cannot-author-canonical-truth'), field); } });

test('operational CRM fields can be ingested only through an explicit allowlist', () => { const normalized = normalizeCrmObservation(observation()); const denied = compileCrmIngestPatch({ observation: normalized.observation, allowedOperationalFields: [] }); assert.equal(denied.ok, false); const allowed = compileCrmIngestPatch({ observation: normalized.observation, allowedOperationalFields: ['pipeline-stage'] }); assert.equal(allowed.ok, true); assert.equal(allowed.patch.canonicalTruthAuthority, 'NONE'); });

test('raw CRM PII and secrets cannot enter durable observations', () => { const result = normalizeCrmObservation(observation({ email: 'person@example.com', apiKey: 'secret' })); assert.equal(result.ok, false); assert.ok(result.reasonCodes.includes('raw-crm-pii-or-secret-prohibited')); });

test('CRM observations require provider receipt, object version, and freshness', () => { const missing = normalizeCrmObservation(observation({ providerReceiptRef: null, providerVersionRef: null })); assert.equal(missing.ok, false); assert.ok(missing.reasonCodes.includes('provider-receipt-ref-required-for-crm-observation')); assert.ok(missing.reasonCodes.includes('provider-version-ref-required')); const future = normalizeCrmObservation(observation({ observedAt: '2026-08-28T16:30:00.000Z', receivedAt: '2026-08-28T15:50:00.000Z' })); assert.equal(future.ok, false); assert.ok(future.reasonCodes.includes('future-dated-crm-observation')); });

test('external CRM writes require authority, idempotency, and stable references', () => { const result = compileCrmWriteCommand(command({ authorityReceiptRef: null, idempotencyKey: null })); assert.equal(result.ok, false); assert.ok(result.reasonCodes.includes('authority-receipt-ref-required-for-crm-write')); assert.ok(result.reasonCodes.includes('idempotency-key-required-for-crm-write')); const valid = compileCrmWriteCommand(command()); assert.equal(valid.ok, true); assert.equal(valid.businessEffectAuthority, 'NONE'); });

test('protected canonical fields may flow outward only with canonical evidence references', () => { const noEvidence = compileCrmWriteCommand(command({ fields: [{ field: 'payment-status', valueRef: 'paid' }] })); assert.equal(noEvidence.ok, false); assert.ok(noEvidence.reasonCodes.some(code => code.startsWith('canonical-evidence-ref-required-for-protected-field'))); const valid = compileCrmWriteCommand(command({ fields: [{ field: 'payment-status', valueRef: 'paid', evidenceRef: 'canonical_payment_receipt_1' }] })); assert.equal(valid.ok, true); });

test('field values remain references and duplicate field claims fail closed', () => { const duplicate = compileCrmWriteCommand(command({ fields: [{ field: 'pipeline-stage', valueRef: 'one' }, { field: 'pipeline-stage', valueRef: 'two' }] })); assert.equal(duplicate.ok, false); assert.ok(duplicate.reasonCodes.includes('valid-field-reference-array-required')); const valid = compileCrmWriteCommand(command()); assert.equal(Object.hasOwn(valid.command.fields[0], 'value'), false); });

test('confirmed CRM write truth requires provider receipt and resulting external identity', () => { const base = { commandId: 'crm_cmd_1', provider: 'twenty', providerEventId: 'evt_write_1', status: 'WRITE_CONFIRMED', observedAt: '2026-08-28T15:51:00.000Z', receivedAt: '2026-08-28T15:51:01.000Z' }; const result = normalizeCrmWriteOutcome(base); assert.equal(result.ok, false); assert.ok(result.reasonCodes.includes('provider-receipt-ref-required-for-crm-write-truth')); assert.ok(result.reasonCodes.includes('external-object-ref-required-for-confirmed-write')); });

test('uncertain CRM write blocks blind replay by disposition', () => { const result = normalizeCrmWriteOutcome({ commandId: 'crm_cmd_1', provider: 'twenty', providerEventId: 'evt_write_2', status: 'UNCERTAIN_EXTERNAL_STATE', observedAt: '2026-08-28T15:51:00.000Z', receivedAt: '2026-08-28T15:51:01.000Z' }); assert.equal(result.ok, true); assert.equal(result.retryDisposition, 'BLOCK_RETRY_UNTIL_RECONCILED'); });

test('overlong occurrence and idempotency keys fail closed instead of truncating', () => { const a = compileCrmWriteCommand(command({ occurrenceKey: 'x'.repeat(301) })); assert.equal(a.ok, false); const b = compileCrmWriteCommand(command({ idempotencyKey: 'y'.repeat(301) })); assert.equal(b.ok, false); });

test('unconfigured CRM adapter is complete but performs no I/O', async () => { const adapter = createUnconfiguredCrmProviderAdapter('twenty'); const valid = validateCrmProviderAdapter(adapter); assert.equal(valid.ok, true); for (const capability of CRM_PROVIDER_CAPABILITIES) assert.equal(typeof adapter[capability], 'function'); const live = await adapter.liveSupported(); assert.equal(live.ok, false); assert.equal(live.externalEffectLedger.providerCalls, 0); });
