import test from 'node:test';
import assert from 'node:assert/strict';
import { canonicalizePublicUrl, normalizeGamechangerObservation, fingerprintGamechangerObservation, dedupeGamechangerObservations, scoreGamechangerCandidate, classifyGamechangerAttention, buildCoverageReceipt, buildSourceFetchPlan, buildGamechangerTournament, buildFrontierSignalFromGamechanger } from '../src/gamechanger-mesh.mjs';

const observedAt='2026-09-03T09:00:00Z';
function observation(overrides={}){return {id:'x-1',sourceId:'official-x',sourceTier:'PRIMARY_OFFICIAL',sourceType:'CHANGELOG',url:'https://example.com/release?utm_source=x',title:'New autonomous agent runtime released',summary:'New agent runtime adds durable loops, lower cost and an API.',observedAt,domains:['AGENT_RUNTIME','PRICING_FREE_TIERS'],evidenceRefs:['https://example.com/release'],claims:['durable loops','lower cost'],...overrides};}

test('public URL canonicalization strips trackers and rejects non-https',()=>{assert.equal(canonicalizePublicUrl('http://example.com/a'),null);assert.equal(canonicalizePublicUrl('https://example.com/a/?utm_source=x&x=1#z'),'https://example.com/a?x=1');});
test('observation normalization requires evidence and recognized domains',()=>{assert.equal(normalizeGamechangerObservation({...observation(),evidenceRefs:[]}).ok,false);assert.equal(normalizeGamechangerObservation({...observation(),domains:['NOPE']}).ok,false);assert.equal(normalizeGamechangerObservation(observation()).businessEffectAuthority,'NONE');});
test('fingerprint ignores tracking parameters',()=>{const a=fingerprintGamechangerObservation(observation({url:'https://example.com/release?utm_source=a'})),b=fingerprintGamechangerObservation(observation({url:'https://example.com/release?utm_source=b'}));assert.equal(a.fingerprint,b.fingerprint);});
test('dedupe merges independent sources and evidence',()=>{const r=dedupeGamechangerObservations([observation(),observation({id:'x-2',sourceId:'research-y',sourceTier:'PRIMARY_RESEARCH',evidenceRefs:['https://research.example/paper']})]);assert.equal(r.uniqueCount,1);assert.equal(r.observations[0].corroboratingSourceIds.length,2);assert.equal(r.observations[0].evidenceRefs.length,2);});
test('risk and uncertainty reduce score',()=>{const base={novelty:90,enablingPower:90,economicUpside:90,founderMinutesSaved:90,distributionLeverage:90,costCurveShift:90,crossIndustryTransfer:90,evidenceQuality:90,implementationEase:90,timeSensitivity:90,maintenanceBurden:10,regulatoryFriction:10,commoditizationRisk:10,sourceTrust:90,corroboratingSources:2};assert.ok(scoreGamechangerCandidate({...base,risk:10,uncertainty:10}).score>scoreGamechangerCandidate({...base,risk:95,uncertainty:95}).score);});
test('high score cannot become experiment candidate with weak evidence',()=>{assert.equal(classifyGamechangerAttention(95,{evidenceQuality:30,sourceTrust:95}),'RESEARCH');assert.equal(classifyGamechangerAttention(95,{evidenceQuality:90,sourceTrust:90}),'EXPERIMENT_CANDIDATE');});
test('coverage receipt exposes blind spots',()=>{const r=buildCoverageReceipt({sources:[{id:'a',domains:['AI_MODELS']},{id:'b',domains:['AI_MODELS']},{id:'c',domains:['AGENT_RUNTIME']}],requiredDomains:['AI_MODELS','AGENT_RUNTIME'],minIndependentSourcesPerDomain:2});assert.equal(r.status,'GAMECHANGER_COVERAGE_GAPS');assert.deepEqual(r.gaps,['AGENT_RUNTIME']);});
test('source plan separates search lanes from direct reads',()=>{const r=buildSourceFetchPlan({now:observedAt,sources:[{id:'feed',mode:'DIRECT_PUBLIC_READ',url:'https://example.com/feed',cadenceMinutes:60,domains:['AI_MODELS'],sourceTier:'PRIMARY_OFFICIAL'},{id:'search',mode:'SEARCH_LANE',query:'latest open model runtime releases',cadenceMinutes:60,domains:['OPEN_SOURCE']}]});assert.equal(r.directReads.length,1);assert.equal(r.searchLanes.length,1);assert.equal(r.directReadAuthority,'PUBLIC_READ_ONLY');});
test('source plan rejects non-https direct sources',()=>{const r=buildSourceFetchPlan({now:observedAt,sources:[{id:'bad',mode:'DIRECT_PUBLIC_READ',url:'http://example.com/feed',cadenceMinutes:60,domains:['AI_MODELS']}]});assert.equal(r.ok,false);assert.equal(r.directReads.length,0);});
test('tournament excludes known fingerprints and preserves zero authority',()=>{const fp=fingerprintGamechangerObservation(observation()).fingerprint,r=buildGamechangerTournament({observations:[observation()],knownFingerprints:[fp]});assert.equal(r.ranked.length,0);assert.equal(r.businessEffectAuthority,'NONE');});
test('frontier handoff is research-only and does not self-promote',()=>{const t=buildGamechangerTournament({observations:[observation()]});assert.ok(t.ranked.length>=1);const s=buildFrontierSignalFromGamechanger(t.ranked[0]);assert.equal(s.ok,true);assert.equal(s.handoff.promotionAuthority,'NONE');assert.equal(s.businessEffectAuthority,'NONE');});
