import test from 'node:test';
import assert from 'node:assert/strict';
import { compileInstitutionalFinancialLedger, admitInstitutionalEffect, reconcileInstitutionalEvidence } from '../src/institutional-financial-sovereignty.mjs';

const now='2026-09-09T00:00:00.000Z';
const evidence=(evidenceClass,evidenceRef='evidence:1',extra={})=>({evidenceClass,evidenceRef,origin:'EXTERNAL',observedAt:now,...extra});
function goodInput(){return{now,entity:{entityRef:'entity:uberbond',legalName:'UberBond Owner Operation',entityType:'SOLE_OWNER_OPERATION',jurisdictionRefs:['EG']},obligations:[{id:'tax-review',kind:'TAX_FILING',jurisdiction:'EG',accountableRole:'OWNER_OR_QUALIFIED_DELEGATE',sourceRef:'authority:tax-source',sourceDate:'2026-09-01',validThrough:'2026-12-31',dueEvent:'Before any filing/payment under the scoped obligation',preEffectRequiredClasses:['COMPLIANCE_EVIDENCE','PROFESSIONAL_OPINION','LEGAL_AUTHORITY'],postEffectRequiredClasses:['ACTUAL_FILING_OR_PAYMENT'],declaredAmountCents:10000,currency:'EGP',evidence:[evidence('COMPLIANCE_EVIDENCE','evidence:scope'),evidence('PROFESSIONAL_OPINION','evidence:professional'),evidence('LEGAL_AUTHORITY','evidence:authority')] }],treasury:{availableCashCents:100000,reservedCashCents:10000,committedObligationsCents:10000,reserveFloorCents:30000,maxSingleProcurementCents:20000,currency:'EGP'},reconciliations:[{id:'close-1',bookNetCents:50000,externalNetCents:50000,toleranceCents:0,currency:'EGP',evidenceRef:'provider:statement-1'}]};}

test('clean institutional state compiles while post-effect proof remains pending',()=>{const c=compileInstitutionalFinancialLedger(goodInput());assert.equal(c.ok,true);assert.equal(c.status,'INSTITUTIONAL_STATE_COMPILED');assert.equal(c.ledger.obligations[0].status,'READY_FOR_EFFECT_GATE__POST_EVIDENCE_PENDING');assert.deepEqual(c.ledger.obligations[0].missingPostEffectEvidence,['ACTUAL_FILING_OR_PAYMENT']);assert.equal(c.businessEffectAuthority,'NONE');});

test('software capability cannot masquerade as compliance evidence',()=>{const i=goodInput();i.obligations[0].evidence=[evidence('SOFTWARE_CAPABILITY'),evidence('PROFESSIONAL_OPINION'),evidence('LEGAL_AUTHORITY')];const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ledger.obligations[0].status,'BLOCKED_PRE_EFFECT');assert.ok(c.ledger.obligations[0].reasonCodes.includes('pre-effect-evidence-missing:COMPLIANCE_EVIDENCE'));});

test('professional opinion cannot masquerade as legal authority',()=>{const i=goodInput();i.obligations[0].evidence=[evidence('COMPLIANCE_EVIDENCE'),evidence('PROFESSIONAL_OPINION')];const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ledger.obligations[0].status,'BLOCKED_PRE_EFFECT');assert.ok(c.ledger.obligations[0].reasonCodes.includes('pre-effect-evidence-missing:LEGAL_AUTHORITY'));});

test('stale obligation source blocks effects',()=>{const i=goodInput();i.obligations[0].validThrough='2026-09-01';const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ledger.obligations[0].status,'BLOCKED_PRE_EFFECT');assert.ok(c.ledger.obligations[0].reasonCodes.includes('obligation-source-stale'));const a=admitInstitutionalEffect({compiled:c,action:{kind:'PAY_TAX',amountCents:10000,currency:'EGP',obligationIds:['tax-review']}});assert.equal(a.ok,false);});

test('jurisdiction must be declared on the entity',()=>{const i=goodInput();i.obligations[0].jurisdiction='US';const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ok,false);assert.ok(c.reasonCodes.includes('obligation-jurisdiction-not-declared:tax-review'));});

test('max-three exception queue never deletes fourth blocker',()=>{const i=goodInput();i.obligations=Array.from({length:4},(_,n)=>({...i.obligations[0],id:`o-${n}`,evidence:[]}));const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ledger.exceptionQueue.total,4);assert.equal(c.ledger.exceptionQueue.visible.length,3);assert.equal(c.ledger.exceptionQueue.hiddenCount,1);assert.equal(c.ledger.obligations.length,4);});

test('effect that breaches reserve floor is refused',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const a=admitInstitutionalEffect({compiled:c,action:{kind:'PAY_TAX',amountCents:60000,currency:'EGP',obligationIds:['tax-review']}});assert.equal(a.ok,false);assert.ok(a.reasonCodes.includes('effect-would-breach-reserve-floor'));});

test('procurement cap is independent from reserve floor',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const a=admitInstitutionalEffect({compiled:c,action:{kind:'PROCUREMENT',amountCents:25000,currency:'EGP',obligationIds:['tax-review']}});assert.equal(a.ok,false);assert.ok(a.reasonCodes.includes('procurement-exceeds-declared-single-action-cap'));});

test('cross-currency effect needs a separate FX evidence path',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const a=admitInstitutionalEffect({compiled:c,action:{kind:'PROCUREMENT',amountCents:1000,currency:'USD',obligationIds:['tax-review']}});assert.equal(a.ok,false);assert.ok(a.reasonCodes.includes('cross-currency-effect-requires-separate-fx-evidence'));});

test('unresolved reconciliation blocks financial effects',()=>{const i=goodInput();i.reconciliations[0].externalNetCents=49900;const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ledger.reconciliations[0].status,'UNRESOLVED');const a=admitInstitutionalEffect({compiled:c,action:{kind:'PAY_TAX',amountCents:10000,currency:'EGP',obligationIds:['tax-review']}});assert.equal(a.ok,false);assert.ok(a.reasonCodes.includes('unresolved-financial-reconciliation-blocks-effect'));});

test('institutional readiness never becomes effect authority',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const a=admitInstitutionalEffect({compiled:c,action:{kind:'PAY_TAX',amountCents:10000,currency:'EGP',obligationIds:['tax-review']}});assert.equal(a.ok,true);assert.equal(a.status,'READY_FOR_SEPARATE_EFFECT_AUTHORITY_GATE');assert.equal(a.businessEffectAuthority,'NONE');});

test('C25-B refuses internal or synthetic filing evidence',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const r=reconcileInstitutionalEvidence({compiled:c,obligationId:'tax-review',evidence:{evidenceClass:'ACTUAL_FILING_OR_PAYMENT',evidenceRef:'internal:fake',origin:'INTERNAL',observedAt:now,amountCents:10000,currency:'EGP'}});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('institutional-effect-evidence-must-be-external'));});

test('actual filing/payment evidence must match declared amount and currency',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const r=reconcileInstitutionalEvidence({compiled:c,obligationId:'tax-review',evidence:evidence('ACTUAL_FILING_OR_PAYMENT','external:receipt',{amountCents:9999,currency:'USD'})});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('institutional-evidence-amount-mismatch'));assert.ok(r.reasonCodes.includes('institutional-evidence-currency-mismatch'));});

test('valid external filing/payment receipt can be reconciled but does not assert legal correctness',()=>{const c=compileInstitutionalFinancialLedger(goodInput());const r=reconcileInstitutionalEvidence({compiled:c,obligationId:'tax-review',evidence:evidence('ACTUAL_FILING_OR_PAYMENT','external:receipt',{amountCents:10000,currency:'EGP'})});assert.equal(r.ok,true);assert.equal(r.status,'INSTITUTIONAL_EVIDENCE_RECONCILED__RECOMPILE_LEDGER_REQUIRED');assert.equal(r.businessEffectAuthority,'NONE');assert.match(r.truthBoundary,/does not itself establish legal correctness/);});

test('recompiling with the bound external receipt moves the obligation to satisfied evidence state',()=>{const i=goodInput();i.obligations[0].evidence.push(evidence('ACTUAL_FILING_OR_PAYMENT','external:receipt',{obligationId:'tax-review',amountCents:10000,currency:'EGP'}));const c=compileInstitutionalFinancialLedger(i);assert.equal(c.ledger.obligations[0].status,'SATISFIED_BY_DECLARED_EVIDENCE');assert.deepEqual(c.ledger.obligations[0].missingPostEffectEvidence,[]);});
