import test from 'node:test';
import assert from 'node:assert/strict';
import { admitModelAdaptation } from '../src/model-adaptation-admission.mjs';
const D=c=>c.repeat(64),B=D('a'),H=D('b'),ZERO_ROUTES=['PROMPT','RETRIEVAL','TOOLS','DECOMPOSITION','COMPOSITION','AUTHORIZED_EXISTING_MODEL'];
const routes=()=>ZERO_ROUTES.map((route,i)=>({route,status:'MEASURED_INSUFFICIENT',evidenceRef:`evidence://route/${i}`,bottleneckDigest:B,matchedBudgetRef:'budget://matched/1'}));
const base=()=>({
 bottleneck:{bottleneckDigest:B,evidenceRef:'evidence://bottleneck/1'},cheaperRoutes:routes(),
 dataset:{datasetDigest:D('c'),sources:[{provenanceRef:'source://public/1',license:'CC-BY-4.0',licenseStatus:'ALLOWED',containsPrivateData:false,collectionAuthorized:true}],partitions:{trainHash:D('d'),devHash:D('e'),heldoutHash:H,identityOverlapCount:0},contamination:{evidenceClass:'OBSERVED_SCAN',knownBenchmarkMatchCount:0,heldoutLeakCount:0,evidenceRef:'evidence://contamination/1'},syntheticDataPresent:false,adversarialDatasetRef:'dataset://adversarial/1'},
 trainingPlan:{baseModelId:'model.alpha',baseModelRevision:'rev-1',baseModelLicenseStatus:'ALLOWED',method:'LORA',isolation:{productionCredentialsMounted:false,privateLifeStateMounted:false,productionMutationReachable:false,networkEgressMode:'DATASET_AND_MODEL_REGISTRY_ALLOWLIST'},budget:{maxComputeUnits:100,maxSpendCents:0},reproducibility:{seedRef:'seed://1',environmentDigest:D('f')},heldoutHash:H},
 evaluationPlan:{c13EvaluationContractRef:'c13://eval/1',strongestBaselineRef:'baseline://strongest/1',heldoutHash:H,evaluatorIndependent:true,frozenBeforeTraining:true,trainingDataAccessibleToEvaluator:false},
 servingPlan:{candidateArtifactDigest:D('1'),rollbackArtifactRef:'artifact://prior/1',priorServingRevision:'serve-0',canaryPlanRef:'canary://1',c26SecurityAdmissionRef:'c26://1',maxAllowedRegression:0.01,quantizationCandidates:[{format:'Q8',artifactDigest:D('2'),mustRebenchmark:true}],automaticProductionPromotion:false}
});
test('fully evidenced adaptation is only admissible for separate isolated-training authority',()=>{const r=admitModelAdaptation(base());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.status,'MODEL_ADAPTATION_ADMISSIBLE_FOR_SEPARATE_ISOLATED_TRAINING_AUTHORITY');assert.equal(r.trainingAuthority,'NONE');assert.equal(r.deploymentAuthority,'NONE');assert.equal(r.asiStatus,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');assert.match(r.admissionDigest,/^[0-9a-f]{64}$/);});
test('adaptation cannot skip a cheaper prompt or tool route',()=>{const x=base();x.cheaperRoutes=x.cheaperRoutes.filter(r=>r.route!=='PROMPT');const r=admitModelAdaptation(x);assert.equal(r.status,'MODEL_ADAPTATION_DEFER_TO_CHEAPER_ROUTE');assert.ok(r.reasonCodes.includes('cheaper-route-missing:PROMPT'));});
test('cheaper routes must be measured insufficient rather than merely attempted',()=>{const x=base();x.cheaperRoutes[2].status='FAILED_TO_RUN';const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('cheaper-route-not-proven-insufficient:TOOLS'));});
test('cheaper route evidence must bind the same residual bottleneck and matched budget',()=>{const x=base();x.cheaperRoutes[1].bottleneckDigest=D('9');delete x.cheaperRoutes[1].matchedBudgetRef;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('cheaper-route-bottleneck-mismatch:RETRIEVAL'));assert.ok(r.reasonCodes.includes('cheaper-route-matched-budget-required:RETRIEVAL'));});
test('route duplication reordering and unknown routes fail closed',()=>{const x=base();x.cheaperRoutes=[x.cheaperRoutes[1],x.cheaperRoutes[0],...x.cheaperRoutes.slice(2),{...x.cheaperRoutes[0],route:'MAGIC'}];const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('all-cheaper-routes-must-be-measured-exactly-once'));assert.ok(r.reasonCodes.includes('cheaper-routes-must-follow-canonical-order'));assert.ok(r.reasonCodes.includes('unknown-cheaper-route'));});
test('training data requires provenance allowed license and collection authority',()=>{const x=base();delete x.dataset.sources[0].provenanceRef;x.dataset.sources[0].licenseStatus='UNKNOWN';x.dataset.sources[0].collectionAuthorized=false;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('dataset-source-provenance-required'));assert.ok(r.reasonCodes.includes('dataset-source-license-must-be-allowed'));assert.ok(r.reasonCodes.includes('dataset-source-collection-authority-required'));});
test('private training data requires explicit consent evidence',()=>{const x=base();Object.assign(x.dataset.sources[0],{containsPrivateData:true,explicitConsent:false});const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('private-training-data-requires-explicit-consent'));assert.ok(r.reasonCodes.includes('private-training-data-consent-evidence-required'));});
test('train dev and heldout partitions must be cryptographically distinct with zero identity overlap',()=>{const x=base();x.dataset.partitions.devHash=x.dataset.partitions.trainHash;x.dataset.partitions.identityOverlapCount=1;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('train-dev-heldout-must-be-distinct'));assert.ok(r.reasonCodes.includes('partition-identity-overlap-must-be-zero'));});
test('contamination evidence must be observed and exactly zero',()=>{const x=base();x.dataset.contamination.evidenceClass='SYNTHETIC';x.dataset.contamination.knownBenchmarkMatchCount=1;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('observed-zero-contamination-evidence-required'));});
test('synthetic data cannot hide its synthetic provenance',()=>{const x=base();x.dataset.syntheticDataPresent=true;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('synthetic-training-data-must-be-labeled-and-provenanced'));});
test('training isolation cannot mount production credentials or private life state',()=>{const x=base();x.trainingPlan.isolation.productionCredentialsMounted=true;x.trainingPlan.isolation.privateLifeStateMounted=true;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('isolated-training-boundary-required'));});
test('training budgets reject strings null and missing reproducibility evidence',()=>{const x=base();x.trainingPlan.budget.maxComputeUnits='100';x.trainingPlan.budget.maxSpendCents=null;x.trainingPlan.reproducibility.environmentDigest='bad';const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('explicit-training-resource-limits-required'));assert.ok(r.reasonCodes.includes('training-reproducibility-contract-required'));});
test('heldout identity must bind both training and frozen independent evaluation',()=>{const x=base();x.trainingPlan.heldoutHash=D('7');x.evaluationPlan.heldoutHash=D('8');x.evaluationPlan.evaluatorIndependent=false;x.evaluationPlan.frozenBeforeTraining=false;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('training-plan-heldout-binding-mismatch'));assert.ok(r.reasonCodes.includes('evaluation-heldout-binding-mismatch'));assert.ok(r.reasonCodes.includes('independent-evaluator-required'));assert.ok(r.reasonCodes.includes('evaluation-protocol-must-be-frozen-before-training'));});
test('serving cannot exist without rollback canary C26 and explicit regression threshold',()=>{const x=base();delete x.servingPlan.rollbackArtifactRef;delete x.servingPlan.canaryPlanRef;delete x.servingPlan.c26SecurityAdmissionRef;x.servingPlan.maxAllowedRegression=null;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('serving-rollback-contract-required'));assert.ok(r.reasonCodes.includes('canary-and-c26-security-gates-required'));assert.ok(r.reasonCodes.includes('serving-regression-threshold-required'));});
test('every quantization variant must be independently digested and rebenchmarked',()=>{const x=base();x.servingPlan.quantizationCandidates=[{format:'Q4',artifactDigest:'bad',mustRebenchmark:false}];const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('every-quantization-needs-digest-and-rebenchmark'));});
test('admission can never authorize automatic production promotion',()=>{const x=base();x.servingPlan.automaticProductionPromotion=true;const r=admitModelAdaptation(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('automatic-production-promotion-prohibited'));assert.equal(r.deploymentAuthority,'NONE');});
