import test from 'node:test';
import assert from 'node:assert/strict';
import { admitModelAdaptation } from '../src/model-adaptation-admission.mjs';
const D=c=>c.repeat(64),B=D('a'),H=D('b'),ROUTES=['PROMPT','RETRIEVAL','TOOLS','DECOMPOSITION','COMPOSITION','AUTHORIZED_EXISTING_MODEL'];
const routes=()=>ROUTES.map((route,i)=>({route,status:'MEASURED_INSUFFICIENT',evidenceRef:`evidence://route/${i}`,bottleneckDigest:B,matchedBudgetRef:'budget://matched/1'}));
const base=()=>({
 bottleneck:{bottleneckDigest:B,evidenceRef:'evidence://bottleneck/1'},cheaperRoutes:routes(),
 dataset:{datasetDigest:D('c'),sources:[{provenanceRef:'source://public/1',license:'CC-BY-4.0',licenseStatus:'ALLOWED',licenseEvidenceRef:'license://1',privacyClass:'PUBLIC_NONPERSONAL',collectionAuthorized:true,collectionAuthorityRef:'authority://collect/1'}],partitions:{trainHash:D('d'),devHash:D('e'),heldoutHash:H,identityOverlapCount:0,overlapScanEvidenceRef:'evidence://overlap/1'},contamination:{evidenceClass:'OBSERVED_SCAN',knownBenchmarkMatchCount:0,heldoutLeakCount:0,evidenceRef:'evidence://contamination/1',datasetDigest:D('c'),heldoutHash:H},syntheticDataPresent:false,adversarialDatasetRef:'dataset://adversarial/1'},
 trainingPlan:{baseModelId:'model.alpha',baseModelRevision:'rev-1',baseModelLicenseStatus:'ALLOWED',baseModelLicenseEvidenceRef:'license://model/1',method:'LORA',isolation:{productionCredentialsMounted:false,privateLifeStateMounted:false,productionMutationReachable:false,networkEgressMode:'DATASET_AND_MODEL_REGISTRY_ALLOWLIST',networkAllowlistRef:'network://allowlist/1'},budget:{maxComputeUnits:100,maxSpendCents:0},reproducibility:{seedRef:'seed://1',environmentDigest:D('f')},heldoutHash:H},
 evaluationPlan:{c13EvaluationContractRef:'c13://eval/1',strongestBaselineRef:'baseline://strongest/1',heldoutHash:H,evaluatorIndependent:true,frozenBeforeTraining:true,trainingDataAccessibleToEvaluator:false,candidateArtifactDigestRequiredBeforeEvaluation:true},
 servingPlan:{candidateArtifactDigest:null,candidateArtifactDigestRequiredBeforeCanary:true,rollbackArtifactRef:'artifact://prior/1',priorServingRevision:'serve-0',canaryPlanRef:'canary://1',c26SecurityAdmissionRef:'c26://1',maxAllowedRegression:0.01,quantizationPlan:[{format:'Q8',artifactDigest:null,mustRebenchmark:true}],automaticProductionPromotion:false}
});
test('fully evidenced pretraining adaptation is only admissible for separate authority',()=>{const r=admitModelAdaptation(base());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.status,'MODEL_ADAPTATION_ADMISSIBLE_FOR_SEPARATE_ISOLATED_TRAINING_AUTHORITY');assert.equal(r.trainingAuthority,'NONE');assert.equal(r.deploymentAuthority,'NONE');assert.equal(r.asiStatus,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');assert.equal(r.admission.futureArtifactBindingRequired,true);assert.match(r.truthBoundary,/NO_FUTURE_MODEL/);});
test('adaptation cannot skip a cheaper prompt route',()=>{const x=base();x.cheaperRoutes=x.cheaperRoutes.filter(r=>r.route!=='PROMPT');const r=admitModelAdaptation(x);assert.equal(r.status,'MODEL_ADAPTATION_DEFER_TO_CHEAPER_ROUTE');assert.ok(r.reasonCodes.includes('cheaper-route-missing:PROMPT'));});
test('cheaper routes must be measured insufficient rather than merely attempted',()=>{const x=base();x.cheaperRoutes[2].status='FAILED_TO_RUN';assert.ok(admitModelAdaptation(x).reasonCodes.includes('cheaper-route-not-proven-insufficient:TOOLS'));});
test('cheaper route evidence binds same residual bottleneck and matched budget',()=>{const x=base();x.cheaperRoutes[1].bottleneckDigest=D('9');delete x.cheaperRoutes[1].matchedBudgetRef;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('cheaper-route-bottleneck-mismatch:RETRIEVAL'));assert.ok(r.reasonCodes.includes('cheaper-route-matched-budget-required:RETRIEVAL'));});
test('route duplication reordering and unknown routes fail closed',()=>{const x=base();x.cheaperRoutes=[x.cheaperRoutes[1],x.cheaperRoutes[0],...x.cheaperRoutes.slice(2),{...x.cheaperRoutes[0],route:'MAGIC'}];const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('all-cheaper-routes-must-be-measured-exactly-once'));assert.ok(r.reasonCodes.includes('cheaper-routes-must-follow-canonical-order'));assert.ok(r.reasonCodes.includes('unknown-cheaper-route'));});
test('dataset privacy class cannot be omitted to masquerade personal data as public',()=>{const x=base();delete x.dataset.sources[0].privacyClass;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('dataset-source-privacy-class-required'));});
test('training data requires provenance evidenced license and collection authority',()=>{const x=base();delete x.dataset.sources[0].provenanceRef;delete x.dataset.sources[0].licenseEvidenceRef;delete x.dataset.sources[0].collectionAuthorityRef;x.dataset.sources[0].licenseStatus='UNKNOWN';x.dataset.sources[0].collectionAuthorized=false;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('dataset-source-provenance-required'));assert.ok(r.reasonCodes.includes('dataset-source-license-must-be-allowed-and-evidenced'));assert.ok(r.reasonCodes.includes('dataset-source-collection-authority-evidence-required'));});
test('personal training data requires explicit consent evidence',()=>{const x=base();Object.assign(x.dataset.sources[0],{privacyClass:'PERSONAL_WITH_CONSENT',explicitConsent:false,consentRef:null});assert.ok(admitModelAdaptation(x).reasonCodes.includes('personal-training-data-requires-explicit-consent-evidence'));});
test('train dev heldout require distinct hashes and observed zero overlap evidence',()=>{const x=base();x.dataset.partitions.devHash=x.dataset.partitions.trainHash;x.dataset.partitions.identityOverlapCount=1;delete x.dataset.partitions.overlapScanEvidenceRef;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('train-dev-heldout-must-be-distinct'));assert.ok(r.reasonCodes.includes('observed-zero-partition-overlap-evidence-required'));});
test('contamination receipt binds exact dataset and heldout and must observe zero',()=>{const x=base();x.dataset.contamination.datasetDigest=D('9');x.dataset.contamination.heldoutHash=D('8');x.dataset.contamination.evidenceClass='SYNTHETIC';x.dataset.contamination.knownBenchmarkMatchCount=1;assert.ok(admitModelAdaptation(x).reasonCodes.includes('observed-zero-contamination-evidence-must-bind-dataset-and-heldout'));});
test('synthetic data cannot hide its synthetic provenance',()=>{const x=base();x.dataset.syntheticDataPresent=true;assert.ok(admitModelAdaptation(x).reasonCodes.includes('synthetic-training-data-must-be-labeled-and-provenanced'));});
test('training isolation cannot mount production credentials or private life state',()=>{const x=base();x.trainingPlan.isolation.productionCredentialsMounted=true;x.trainingPlan.isolation.privateLifeStateMounted=true;assert.ok(admitModelAdaptation(x).reasonCodes.includes('isolated-training-boundary-required'));});
test('training network is explicit allowlist with evidence',()=>{const x=base();delete x.trainingPlan.isolation.networkAllowlistRef;assert.ok(admitModelAdaptation(x).reasonCodes.includes('training-network-must-be-evidenced-allowlist'));});
test('training budgets reject strings null and malformed reproducibility',()=>{const x=base();x.trainingPlan.budget.maxComputeUnits='100';x.trainingPlan.budget.maxSpendCents=null;x.trainingPlan.reproducibility.environmentDigest='bad';const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('explicit-training-resource-limits-required'));assert.ok(r.reasonCodes.includes('training-reproducibility-contract-required'));});
test('heldout identity binds training and frozen independent evaluation',()=>{const x=base();x.trainingPlan.heldoutHash=D('7');x.evaluationPlan.heldoutHash=D('8');x.evaluationPlan.evaluatorIndependent=false;x.evaluationPlan.frozenBeforeTraining=false;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('training-plan-heldout-binding-mismatch'));assert.ok(r.reasonCodes.includes('evaluation-heldout-binding-mismatch'));assert.ok(r.reasonCodes.includes('independent-evaluator-required'));assert.ok(r.reasonCodes.includes('evaluation-protocol-must-be-frozen-before-training'));});
test('future trained artifact digest must be absent pretraining but mandatory before evaluation and canary',()=>{const fake=base();fake.servingPlan.candidateArtifactDigest=D('1');assert.ok(admitModelAdaptation(fake).reasonCodes.includes('pretraining-cannot-claim-future-candidate-artifact-digest'));const missing=base();missing.evaluationPlan.candidateArtifactDigestRequiredBeforeEvaluation=false;missing.servingPlan.candidateArtifactDigestRequiredBeforeCanary=false;const r=admitModelAdaptation(missing);assert.ok(r.reasonCodes.includes('post-training-artifact-digest-required-before-evaluation'));assert.ok(r.reasonCodes.includes('candidate-artifact-digest-required-before-canary'));});
test('serving contracts require rollback canary C26 and explicit regression threshold',()=>{const x=base();delete x.servingPlan.rollbackArtifactRef;delete x.servingPlan.canaryPlanRef;delete x.servingPlan.c26SecurityAdmissionRef;x.servingPlan.maxAllowedRegression=null;const r=admitModelAdaptation(x);assert.ok(r.reasonCodes.includes('serving-rollback-contract-required'));assert.ok(r.reasonCodes.includes('canary-and-c26-security-gates-required'));assert.ok(r.reasonCodes.includes('serving-regression-threshold-required'));});
test('quantization plan names future variants but cannot preclaim their hashes and must rebenchmark',()=>{const x=base();x.servingPlan.quantizationPlan=[{format:'Q4',artifactDigest:D('2'),mustRebenchmark:false},{format:'Q4',artifactDigest:null,mustRebenchmark:true}];assert.ok(admitModelAdaptation(x).reasonCodes.includes('quantization-plan-requires-unique-format-future-digest-and-rebenchmark'));});
test('admission can never authorize automatic production promotion',()=>{const x=base();x.servingPlan.automaticProductionPromotion=true;const r=admitModelAdaptation(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('automatic-production-promotion-prohibited'));assert.equal(r.deploymentAuthority,'NONE');});
