import test from 'node:test';
import assert from 'node:assert/strict';
import { compilePostgresBackupRestoreReceipt } from '../src/postgres-backup-restore-receipt.mjs';
import { compileDurableWorkloadReceipt,compileCutoverRollbackReceipt,compileProviderLossReceipt } from '../src/runtime-transition-receipts.mjs';
import { verifyProviderNeutralRuntimeAcceptance } from '../src/provider-neutral-runtime-acceptance.mjs';

const sha='a'.repeat(40), d='sha256:'+'b'.repeat(64), obs={sourceCommit:sha,runtimeIdentity:'host:alt',verifierIdentity:'auditor:external',observedAt:'2026-09-09T03:10:00Z',evidenceClass:'OBSERVED_RUNTIME'};
const pg=()=>compilePostgresBackupRestoreReceipt({sourceCommit:sha,environment:'POSTGRES',primaryDatabaseIdentity:'db:primary',restoreDatabaseIdentity:'db:restore',backupDigest:d,sourceFingerprint:d,restoreFingerprint:d,dumpBytes:10,dumpExitCode:0,restoreExitCode:0,schemaMigrationsMatch:true,tableSetMatch:true,rowCountFingerprintMatch:true,boundedReadWriteVerified:true,primaryDatabaseMutated:false,cleanupOk:true,runtimeIdentity:'host:alt/db:restore',rollbackRef:'receipt:drop-restore',evidenceRef:'receipt:restore',observerRef:'observer:a',independentVerifierRef:'verifier:b',evidenceClass:'OBSERVED_RUNTIME',businessEffectAuthority:'NONE'});
const workload=()=>compileDurableWorkloadReceipt({...obs,evidenceRef:'receipt:workload',workloadId:'job:1',beforeStateDigest:d,afterStateDigest:d,restartObserved:true,replacementWorkerObserved:true,persistedAcrossRestart:true,duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});
const cutover=()=>compileCutoverRollbackReceipt({...obs,evidenceRef:'receipt:cutover',fromRuntimeIdentity:'host:primary',toRuntimeIdentity:'host:alt',cutoverSucceeded:true,boundedWorkloadSucceeded:true,rollbackExercised:true,rollbackSucceeded:true,rollbackRuntimeIdentity:'host:primary',duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});
const loss=()=>compileProviderLossReceipt({...obs,evidenceRef:'receipt:loss',manifestDigest:d,failedProvider:'PRIMARY',alternateProvider:'ALT',primaryUnavailable:true,alternateRestoreSucceeded:true,boundedWorkloadSucceeded:true,recoveryUsedPrimaryProvider:false,duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});
const good=()=>({sourceCommit:sha,host:{runtimeIdentity:'host:alt',provider:'ALT',region:'r1',imageDigest:d,configDigest:d,dataSchemaDigest:d,sourceCommit:sha,authenticatedHealthObserved:true},postgresRestoreReceipt:pg(),restartRecoveryReceipt:{ok:true,status:'RESTART_RECOVERY_REHEARSAL_PASSED',sourceCommit:sha,noDuplicateEffectClaim:'QUEUE_REPLAY_SAFE_WORK_RECLAIMED_ONCE__UNCERTAIN_RECONCILE_WORK_NOT_REPLAYED',commands:['node drill']},durableWorkloadReceipt:workload(),cutoverRollbackReceipt:cutover(),continuityRehearsal:{ok:true,status:'CONTINUITY_REHEARSAL_VERIFIED_WITHIN_DECLARED_SCOPE',manifestDigest:d},providerLossReceipt:loss(),controlPlaneReceipt:{evidenceClass:'OBSERVED_RUNTIME',sourceCommit:sha,runtimeIdentity:'host:alt',authenticatedReadSucceeded:true,privateLifeStateExposed:false,writeAuthorityGranted:false,evidenceRef:'receipt:control',independentVerifierRef:'verifier:f'}});

test('postgres restore receipt requires isolated exact-source observed restore',()=>{const r=pg();assert.equal(r.ok,true);assert.equal(r.independentlyVerified,true);assert.equal(r.c23RestoreReceipt.receiptClass,'RESTORE');});
test('restore cannot target primary database',()=>{const x=good();x.postgresRestoreReceipt=compilePostgresBackupRestoreReceipt({...pg(),primaryDatabaseIdentity:'same',restoreDatabaseIdentity:'same'});assert.equal(x.postgresRestoreReceipt.ok,false);});
test('observer cannot self-certify independence',()=>{const x=compilePostgresBackupRestoreReceipt({...pg(),observerRef:'same',independentVerifierRef:'same'});assert.equal(x.ok,true);assert.equal(x.independentlyVerified,false);});
test('all canonical observed runtime leaves compose into named runtime verification',()=>{const r=verifyProviderNeutralRuntimeAcceptance(good());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.status,'NAMED_RUNTIME_VERIFIED_WITHIN_REHEARSED_SCOPE');assert.equal(r.businessEffectAuthority,'NONE');assert.equal(r.asiTruth,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');});
test('source drift fails closed and breaks receipt integrity',()=>{const x=good();x.durableWorkloadReceipt.sourceCommit='c'.repeat(40);const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('durable-workload-source-mismatch'));assert.ok(r.reasonCodes.includes('canonical-durable-workload-receipt-integrity-required'));});
test('restart recovery cannot omit no-duplicate-effect proof',()=>{const x=good();delete x.restartRecoveryReceipt.noDuplicateEffectClaim;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('cutover must actually exercise rollback and tamper invalidates digest',()=>{const x=good();x.cutoverRollbackReceipt.rollbackExercised=false;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('canonical-cutover-rollback-receipt-integrity-required'));});
test('same-provider loss rehearsal is refused and tamper invalidates digest',()=>{const x=good();x.providerLossReceipt.alternateProvider='PRIMARY';const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('canonical-provider-loss-receipt-integrity-required'));});
test('provider-loss duplicate effects are refused',()=>{const x=good();x.providerLossReceipt.duplicateExternalEffects=1;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('merely sha-shaped forged transition digest is refused',()=>{const x=good();x.durableWorkloadReceipt.receiptDigest='sha256:'+'f'.repeat(64);const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('canonical-durable-workload-receipt-integrity-required'));});
test('control plane may not expose founder-private life state',()=>{const x=good();x.controlPlaneReceipt.privateLifeStateExposed=true;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('control plane may not silently gain write authority',()=>{const x=good();x.controlPlaneReceipt.writeAuthorityGranted=true;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('structural continuity alone cannot mint runtime verification',()=>{const x=good();x.continuityRehearsal={ok:true,status:'CONTINUITY_PLAN_READY_FOR_REHEARSAL',manifestDigest:d};const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
