import test from 'node:test';
import assert from 'node:assert/strict';
import { compilePostgresBackupRestoreReceipt } from '../src/postgres-backup-restore-receipt.mjs';
import { independentlyVerifyPostgresBackupRestoreReceipt } from '../src/postgres-backup-restore-verifier.mjs';
import { compileDurableWorkloadReceipt, compileCutoverRollbackReceipt, compileProviderLossReceipt } from '../src/runtime-transition-receipts.mjs';
import { verifyProviderNeutralRuntimeAcceptance } from '../src/provider-neutral-runtime-acceptance.mjs';

const sha='a'.repeat(40), d='sha256:'+'b'.repeat(64);
const observedPg=()=>compilePostgresBackupRestoreReceipt({sourceCommit:sha,environment:'POSTGRES',primaryDatabaseIdentity:'db:primary',restoreDatabaseIdentity:'db:restore',backupDigest:d,sourceFingerprint:d,restoreFingerprint:d,dumpBytes:10,dumpExitCode:0,restoreExitCode:0,schemaMigrationsMatch:true,tableSetMatch:true,rowCountFingerprintMatch:true,boundedReadWriteVerified:true,primaryDatabaseMutated:false,cleanupOk:true,runtimeIdentity:'host:alt',rollbackRef:'receipt:drop-restore',evidenceRef:'receipt:restore',observerRef:'observer:a',manifestDigest:d,evidenceClass:'OBSERVED_RUNTIME',businessEffectAuthority:'NONE'});
const pg=()=>independentlyVerifyPostgresBackupRestoreReceipt({observedReceipt:observedPg(),verifierRef:'verifier:b',verificationEvidenceRef:'verification:pg:1'});
const common={sourceCommit:sha,runtimeIdentity:'host:alt',verifierIdentity:'verifier:c',evidenceRef:'receipt:runtime',observedAt:'2026-09-09T04:30:00Z',evidenceClass:'OBSERVED_RUNTIME'};
const workload=()=>compileDurableWorkloadReceipt({...common,workloadId:'job:1',beforeStateDigest:d,afterStateDigest:d,restartObserved:true,replacementWorkerObserved:true,persistedAcrossRestart:true,duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});
const cutover=()=>compileCutoverRollbackReceipt({...common,fromRuntimeIdentity:'host:primary',toRuntimeIdentity:'host:alt',cutoverSucceeded:true,boundedWorkloadSucceeded:true,rollbackExercised:true,rollbackSucceeded:true,rollbackRuntimeIdentity:'host:primary',duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});
const loss=()=>compileProviderLossReceipt({...common,manifestDigest:d,failedProvider:'PRIMARY',alternateProvider:'ALT',primaryUnavailable:true,alternateRestoreSucceeded:true,boundedWorkloadSucceeded:true,recoveryUsedPrimaryProvider:false,duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});
const good=()=>({sourceCommit:sha,host:{runtimeIdentity:'host:alt',provider:'ALT',region:'r1',imageDigest:d,configDigest:d,dataSchemaDigest:d,sourceCommit:sha,authenticatedHealthObserved:true},postgresRestoreReceipt:pg(),restartRecoveryReceipt:{ok:true,status:'RESTART_RECOVERY_REHEARSAL_PASSED',sourceCommit:sha,noDuplicateEffectClaim:'QUEUE_REPLAY_SAFE_WORK_RECLAIMED_ONCE__UNCERTAIN_RECONCILE_WORK_NOT_REPLAYED',commands:['node drill']},durableWorkloadReceipt:workload(),cutoverRollbackReceipt:cutover(),continuityRehearsal:{ok:true,status:'CONTINUITY_REHEARSAL_VERIFIED_WITHIN_DECLARED_SCOPE',manifestDigest:d},providerLossReceipt:loss(),controlPlaneReceipt:{evidenceClass:'OBSERVED_RUNTIME',sourceCommit:sha,runtimeIdentity:'host:alt',authenticatedReadSucceeded:true,privateLifeStateExposed:false,writeAuthorityGranted:false,evidenceRef:'receipt:control',independentVerifierRef:'verifier:f'}});

test('postgres observer receipt cannot claim independent verification',()=>{const r=observedPg();assert.equal(r.ok,true);assert.equal(r.independentlyVerified,false);assert.equal(r.c23RestoreReceipt,null);});
test('postgres observer is refused when it tries to assert a verifier',()=>{const r=compilePostgresBackupRestoreReceipt({...observedPg(),environment:'POSTGRES',dumpExitCode:0,restoreExitCode:0,independentVerifierRef:'verifier:forged',evidenceClass:'OBSERVED_RUNTIME'});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('observer-cannot-assert-independent-verifier'));});
test('separate verifier turns exact observed digest into C23 restore proof',()=>{const r=pg();assert.equal(r.ok,true);assert.equal(r.independentlyVerified,true);assert.equal(r.c23RestoreReceipt.receiptClass,'RESTORE');assert.match(r.verificationDigest,/^sha256:[0-9a-f]{64}$/);});
test('observer cannot self-certify through verifier stage',()=>{const r=independentlyVerifyPostgresBackupRestoreReceipt({observedReceipt:observedPg(),verifierRef:' OBSERVER:A ',verificationEvidenceRef:'verification:1'});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('observer-cannot-self-verify'));});
test('all observed runtime leaves compose into named runtime verification',()=>{const r=verifyProviderNeutralRuntimeAcceptance(good());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.status,'NAMED_RUNTIME_VERIFIED_WITHIN_REHEARSED_SCOPE');assert.equal(r.businessEffectAuthority,'NONE');assert.equal(r.asiTruth,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');});
test('forged postgres independent flag cannot satisfy parent acceptance',()=>{const x=good();x.postgresRestoreReceipt={...observedPg(),status:'POSTGRES_BACKUP_RESTORE_REHEARSAL_INDEPENDENTLY_VERIFIED',independentlyVerified:true,independentVerifierRef:'verifier:fake'};const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('cryptographically-independent-postgres-restore-required'));});
test('source drift fails closed',()=>{const x=good();x.durableWorkloadReceipt.sourceCommit='c'.repeat(40);const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('restart recovery cannot omit no-duplicate-effect proof',()=>{const x=good();delete x.restartRecoveryReceipt.noDuplicateEffectClaim;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('cutover must actually exercise rollback',()=>{const x=good();x.cutoverRollbackReceipt.rollbackExercised=false;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('same-provider loss rehearsal is refused even through formatting alias',()=>{const x=good();x.providerLossReceipt={...x.providerLossReceipt,alternateProvider:' primary '};const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('control plane may not expose founder-private life state',()=>{const x=good();x.controlPlaneReceipt.privateLifeStateExposed=true;const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
test('structural continuity alone cannot mint runtime verification',()=>{const x=good();x.continuityRehearsal={ok:true,status:'CONTINUITY_PLAN_READY_FOR_REHEARSAL',manifestDigest:d};const r=verifyProviderNeutralRuntimeAcceptance(x);assert.equal(r.ok,false);});
