import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {compileDirectFrontierCounterfactual} from '../src/frontier-counterfactual-compiler.mjs';
import {createProvableExecutionLedger,appendProvableExecution,summarizeProvableExecutions} from '../src/provable-execution-ledger.mjs';
const hs=x=>'sha256:'+crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const prompt='Solve typed obligation O17 under quality contract Q17';const output='42';
function contract(extra={}){
 return compileDirectFrontierCounterfactual({model:'frontier/model',providerRoute:'openrouter:best-current',canonicalPrompt:prompt,matchedOutput:output,
  tokenizerReceipt:{verified:true,inputTokens:10,outputTokens:1,promptHash:hs(prompt),outputHash:hs(output),tokenizerHash:hs('tokenizer-v1'),evidenceRef:'tokenizer://v1'},
  priceReceipt:{verified:true,model:'frontier/model',providerRoute:'openrouter:best-current',inputUsdPerMillion:4,outputUsdPerMillion:20,cacheReadUsdPerMillion:.2,evidenceRef:'price://dated'},
  economics:{cheapestLegitimateRouteVerified:true,batchEconomicsConsidered:true,promptCacheEconomicsConsidered:true,responseCacheEconomicsConsidered:true,retryEconomicsConsidered:true,evidenceRef:'optimizer://dated',...extra}});
}
function receipt(id,c=contract()){return{executionId:id,taskId:'task-'+id,completedAt:'2026-09-30T12:00:00Z',equivalenceClass:'E1',proofVerified:true,matchedObligationHash:hs('o'),qualityContractHash:hs('q'),proofRef:'proof://'+id,referenceContractHash:c.referenceContractHash,directReference:c.directReference};}
test('counterfactual compiler binds canonical prompt/output to verified tokenization and current route economics',()=>{const c=contract();assert.equal(c.ok,true);assert.equal(c.directReference.promptHash,hs(prompt));assert.equal(c.semanticAuthority,'NONE');});
test('counterfactual compiler refuses token counts not bound to exact content',()=>{const c=compileDirectFrontierCounterfactual({model:'m',providerRoute:'r',canonicalPrompt:prompt,matchedOutput:output,tokenizerReceipt:{verified:true,inputTokens:1,outputTokens:1,promptHash:hs('wrong'),outputHash:hs(output),tokenizerHash:hs('t'),evidenceRef:'tok'},priceReceipt:{verified:true,model:'m',providerRoute:'r',inputUsdPerMillion:1,outputUsdPerMillion:1,evidenceRef:'p'},economics:{cheapestLegitimateRouteVerified:true,batchEconomicsConsidered:true,promptCacheEconomicsConsidered:true,responseCacheEconomicsConsidered:true,retryEconomicsConsidered:true}});assert.equal(c.ok,false);});
test('E0-E4 execution ledger rejects duplicates and forged counterfactual binding',()=>{let l=createProvableExecutionLedger({period:'2026-09'});l=appendProvableExecution(l,receipt('x'));assert.throws(()=>appendProvableExecution(l,receipt('x')),/duplicate/);assert.throws(()=>appendProvableExecution(l,{...receipt('y'),referenceContractHash:hs('forged')}),/reference-contract-hash-mismatch/);});
test('E5 cannot enter the provable execution ledger',()=>{const l=createProvableExecutionLedger({period:'2026-09'});assert.throws(()=>appendProvableExecution(l,{...receipt('e5'),equivalenceClass:'E5'}),/unprovable-execution/);});
test('quality is structural for E0-E4 while multiplier is arithmetic from unique executions and observed spend',()=>{let l=createProvableExecutionLedger({period:'2026-09'});for(let i=0;i<100;i++)l=appendProvableExecution(l,receipt('x'+i));const s=summarizeProvableExecutions({ledger:l,actualAllInMicrousd:100});assert.equal(s.ok,true);assert.equal(s.uniqueExecutionCount,100);assert.equal(s.qualityRetestRequired,false);assert.ok(s.referenceCompressionFactor>1);});
