import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { admitRecursiveSecurityEvolution } from '../src/recursive-governance-security.mjs';

const D=x=>`sha256:${String(x).repeat(64).slice(0,64)}`;
const H=x=>`sha256:${crypto.createHash('sha256').update(String(x)).digest('hex')}`;
const admission={ok:true,status:'C26_SECURITY_ADMISSION_READY_FOR_SEPARATE_EFFECT_GATE',subjectDigest:D('a'),subject:{composition:{selfModifying:true}}};
const roleControl=(generation,role)=>({principalId:`principal:${generation}:${role.toLowerCase()}`,credentialFingerprint:H(`${generation}:${role}`),custodyDomain:`custody:${generation}:${role.toLowerCase()}`,controlDomain:`control:${generation}:${role.toLowerCase()}`});
const controls=id=>Object.fromEntries(['PROPOSER','EVALUATOR','HOLDOUT','APPROVER','DEPLOYER','MONITOR','EVIDENCE_STORE','ROLLBACK','CANON_WRITER','SECURITY_POLICY'].map(role=>[role,roleControl(id,role)]));
const gen=(id,parent=null,policy=D('b'))=>({generationId:id,parentGenerationId:parent,proposerId:`${id}:p`,approverId:`${id}:a`,deployerId:`${id}:d`,verifierId:`${id}:v`,monitorId:`${id}:m`,policyDigest:policy,constitutionalDigest:D('c'),riskTier:'CRITICAL',securityEnvelopeTier:'CRITICAL',constitutionalMutationApproved:false,ownerAuthorityRef:null,verifierTrustEpoch:D('7'),principalControls:controls(id)});
const evidence=(generationId,fromPolicyDigest,toPolicyDigest,over={})=>({generationId,admissionSubjectDigest:admission.subjectDigest,fromPolicyDigest,toPolicyDigest,explicitlyAuthorized:true,authorityRef:'authority://founder/security-policy',independentVerifierId:'actor:independent-security-verifier',securityEnvelopeNotWeakened:true,rollbackPreserved:true,rollbackRef:'rollback://policy/previous',evidenceRef:'evidence://policy-mutation',immutableRef:'sha256://policy-mutation',...over});

test('recursive self-improvement must be explicitly declared before policy evolution',()=>{const out=admitRecursiveSecurityEvolution({admission:{...admission,subject:{composition:{selfModifying:false}}},generations:[gen('g1')]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('recursive-evolution-requires-explicit-self-modifying-composition-declaration'));});

test('unchanged security policy across generations needs no mutation receipt',()=>{const out=admitRecursiveSecurityEvolution({admission,generations:[gen('g1'),gen('g2','g1')]});assert.equal(out.ok,true,JSON.stringify(out));assert.equal(out.businessEffectAuthority,'NONE');assert.equal(out.runtimeProof,undefined);assert.equal(out.receipt.runtimeProof,'NONE__STRUCTURAL_AND_EVIDENCE_CONTRACT_ONLY');assert.equal(out.receipt.lineageSeparationChecked,true);assert.equal(out.receipt.principalCredentialCustodySeparationChecked,true);});

test('ancestor proposer cannot become descendant verifier even when policy is unchanged',()=>{const g1=gen('g1'),g2=gen('g2','g1');g2.verifierId=g1.proposerId;const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('ancestor-builder-cannot-verify-descendant:g2'));});

test('ancestor deployer cannot become descendant monitor even when policy is unchanged',()=>{const g1=gen('g1'),g2=gen('g2','g1');g2.monitorId=g1.deployerId;const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('ancestor-builder-cannot-monitor-descendant:g2'));});

test('renaming an actor cannot let ancestor builder principal capture descendant evaluator',()=>{const g1=gen('g1'),g2=gen('g2','g1');g2.principalControls.EVALUATOR={...g1.principalControls.PROPOSER};const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('ancestor-builder-cannot-control-descendant-independent-role:g2:EVALUATOR'));});

test('new actor id with inherited builder credential cannot capture descendant monitor',()=>{const g1=gen('g1'),g2=gen('g2','g1');g2.principalControls.MONITOR.credentialFingerprint=g1.principalControls.DEPLOYER.credentialFingerprint;const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('ancestor-builder-credential-cannot-control-descendant-independent-role:g2:MONITOR'));});

test('new actor and credential still cannot inherit builder custody for evidence store',()=>{const g1=gen('g1'),g2=gen('g2','g1');g2.principalControls.EVIDENCE_STORE.custodyDomain=g1.principalControls.CANON_WRITER.custodyDomain;const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('ancestor-builder-custody-cannot-control-descendant-independent-role:g2:EVIDENCE_STORE'));});

test('verifier trust-root change requires explicit transition evidence',()=>{const g1=gen('g1'),g2=gen('g2','g1');g2.verifierTrustEpoch=D('8');let out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('verifier-trust-root-transition-evidence-required:g2'));g2.verifierTrustTransitionRef='evidence://verifier-root-transition/g2';out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2]});assert.equal(out.ok,true,JSON.stringify(out));});

test('silent security policy swap is refused even when tier remains critical',()=>{const out=admitRecursiveSecurityEvolution({admission,generations:[gen('g1'),gen('g2','g1',D('d'))]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('security-policy-mutation-evidence-required:g2'));});

test('policy mutation receipt must bind to exact C26 composition admission',()=>{const g1=gen('g1'),g2=gen('g2','g1',D('d'));const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2],policyMutationEvidence:[evidence('g2',g1.policyDigest,g2.policyDigest,{admissionSubjectDigest:D('e')})]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('security-policy-mutation-admission-binding-mismatch:g2'));});

test('current proposer approver or deployer cannot verify their own security policy mutation',()=>{const g1=gen('g1'),g2=gen('g2','g1',D('d'));const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2],policyMutationEvidence:[evidence('g2',g1.policyDigest,g2.policyDigest,{independentVerifierId:g2.proposerId})]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('security-policy-mutation-independent-verifier-required:g2'));});

test('ancestor builder or approver cannot verify descendant policy mutation',()=>{const g1=gen('g1'),g2=gen('g2','g1',D('d'));for(const prior of [g1.proposerId,g1.approverId,g1.deployerId]){const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2],policyMutationEvidence:[evidence('g2',g1.policyDigest,g2.policyDigest,{independentVerifierId:prior})]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('security-policy-mutation-independent-verifier-required:g2'));}});

test('policy mutation must prove no weaker envelope and preserve rollback',()=>{const g1=gen('g1'),g2=gen('g2','g1',D('d'));const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2],policyMutationEvidence:[evidence('g2',g1.policyDigest,g2.policyDigest,{securityEnvelopeNotWeakened:false,rollbackPreserved:false})]});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('security-policy-mutation-no-weaker-envelope-proof-required:g2'));assert.ok(out.reasonCodes.includes('security-policy-mutation-rollback-proof-required:g2'));});

test('authorized independently verified policy evolution remains structurally non-authoritative',()=>{const g1=gen('g1'),g2=gen('g2','g1',D('d'));const out=admitRecursiveSecurityEvolution({admission,generations:[g1,g2],policyMutationEvidence:[evidence('g2',g1.policyDigest,g2.policyDigest)]});assert.equal(out.ok,true,JSON.stringify(out));assert.equal(out.status,'RECURSIVE_SECURITY_EVOLUTION_ADMISSIBLE_FOR_SEPARATE_EXECUTION_AUTHORITY');assert.equal(out.businessEffectAuthority,'NONE');assert.equal(out.asiClaim,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');assert.match(out.receiptDigest,/^sha256:[0-9a-f]{64}$/);assert.equal(out.receipt.lineageSeparationChecked,true);assert.equal(out.receipt.principalCredentialCustodySeparationChecked,true);});
