import test from 'node:test';
import assert from 'node:assert/strict';
import { ZERO_EXTERNAL_EFFECTS } from '../src/effect-ledgers.mjs';
import { evaluateRecursiveImprovementRetention } from '../src/recursive-improvement-retention.mjs';

const REV='a'.repeat(40), DIG='b'.repeat(64), FP='c'.repeat(64), SEC=`sha256:${'d'.repeat(64)}`, ZERO=()=>structuredClone(ZERO_EXTERNAL_EFFECTS);
const base=()=>({
  candidate:{candidateId:'uberbond.next',candidateRevision:REV,compositionDigest:DIG},
  selfMaintenance:{ok:true,status:'VERIFIED_CHANGESET_PROMOTED_TO_REVIEW',verifiedReceipt:{verifiedFingerprint:FP},businessEffectAuthority:'NONE'},
  promotionReceipt:{evidenceClass:'OBSERVED_REPOSITORY_PROMOTION',synthetic:false,candidateId:'uberbond.next',candidateRevision:REV,compositionDigest:DIG,testedFingerprint:FP,promotionClass:'MERGED_REVIEWED_CHANGESET',evidenceRef:'github://commit/a'},
  compoundEvaluation:{ok:true,status:'COMPOUND_INTELLIGENCE_GAIN_SUPPORTED_WITHIN_DEFINED_SCOPE',compositionDigest:DIG,receipt:{compositionRevision:REV},receiptHash:'e'.repeat(64),asiStatus:'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED',promotionAuthority:'NONE'},
  securityAdmission:{ok:true,status:'C26_SECURITY_ADMISSION_READY_FOR_SEPARATE_EFFECT_GATE',subjectDigest:SEC,subject:{sourceRevision:REV,composition:{id:'uberbond.next'}}},
  securityRehearsal:{ok:true,status:'C26_SECURITY_REHEARSAL_VERIFIED_WITHIN_DECLARED_SCOPE',subjectDigest:SEC},
  recursiveGovernance:{ok:true,status:'RECURSIVE_SECURITY_EVOLUTION_ADMISSIBLE_FOR_SEPARATE_EXECUTION_AUTHORITY',receipt:{admissionSubjectDigest:SEC},businessEffectAuthority:'NONE'},
  runtimeObservation:{evidenceClass:'OBSERVED_RUNTIME',synthetic:false,candidateId:'uberbond.next',candidateRevision:REV,candidateDigest:DIG,observedAt:'2026-09-09T03:00:00.000Z',evidenceRef:'receipt://runtime/1',observerId:'runtime-monitor',observerLineageRef:'lineage:monitor',hiddenConversationStateUsed:false,unauthorizedEffectLedger:ZERO(),behaviorRetained:true},
  rollbackRehearsal:{evidenceClass:'OBSERVED_RUNTIME',synthetic:false,candidateId:'uberbond.next',candidateRevision:REV,candidateDigest:DIG,priorRevision:'9'.repeat(40),rollbackSucceeded:true,candidateReactivatableAfterRollback:false,duplicateEffectLedger:ZERO(),observedAt:'2026-09-09T03:10:00.000Z',evidenceRef:'receipt://rollback/1',verifierId:'rollback-verifier',verifierLineageRef:'lineage:rollback'},
  revocationReadiness:{candidateId:'uberbond.next',candidateRevision:REV,candidateDigest:DIG,revocationReady:true,evidenceRef:'receipt://revoke/1',verifiedAt:'2026-09-09T03:15:00.000Z',verifierId:'revoke-verifier',verifierLineageRef:'lineage:revoke'},
  actors:{proposerId:'builder',deployerId:'deployer',builderLineages:['lineage:builder','lineage:deployer']},
  promotedAt:'2026-09-09T02:00:00.000Z',now:'2026-09-09T04:00:00.000Z'
});

test('exact evaluated secured observed revision can support retain without gaining authority',()=>{const r=evaluateRecursiveImprovementRetention(base());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.status,'C16_RETAIN_SUPPORTED_WITHIN_DECLARED_SCOPE');assert.equal(r.retainAuthority,'NONE');assert.equal(r.promotionAuthority,'NONE');assert.equal(r.asiStatus,'SYSTEM_LEVEL_ASI_NOT_ESTABLISHED');assert.match(r.receiptDigest,/^[0-9a-f]{64}$/);});
test('tests and self-maintenance alone can never be called retained improvement',()=>{const x=base();delete x.compoundEvaluation;delete x.runtimeObservation;const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('independent-compound-gain-evidence-required'));assert.ok(r.reasonCodes.includes('observed-runtime-receipt-required'));});
test('repository promotion must bind the exact tested fingerprint and exact candidate revision',()=>{const x=base();x.promotionReceipt.testedFingerprint='f'.repeat(64);x.promotionReceipt.candidateRevision='1'.repeat(40);const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('promotion-must-bind-exact-tested-fingerprint'));assert.ok(r.reasonCodes.includes('promotion-candidate-identity-mismatch'));});
test('compound evaluation for another revision or composition cannot launder gain',()=>{const x=base();x.compoundEvaluation.receipt.compositionRevision='1'.repeat(40);x.compoundEvaluation.compositionDigest='2'.repeat(64);const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('compound-evaluation-candidate-revision-mismatch'));assert.ok(r.reasonCodes.includes('compound-evaluation-composition-digest-mismatch'));});
test('C26 admission and rehearsal must bind the candidate and the exact same security subject',()=>{const x=base();x.securityAdmission.subject.sourceRevision='1'.repeat(40);x.securityRehearsal.subjectDigest=`sha256:${'f'.repeat(64)}`;const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('security-admission-candidate-identity-mismatch'));assert.ok(r.reasonCodes.includes('exact-c26-security-rehearsal-required'));});
test('recursive governance must bind the same C26 admission, not an unrelated safe generation',()=>{const x=base();x.recursiveGovernance.receipt.admissionSubjectDigest=`sha256:${'f'.repeat(64)}`;const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('recursive-governance-security-subject-mismatch'));});
test('synthetic or pre-promotion runtime evidence cannot retain the candidate',()=>{const x=base();x.runtimeObservation.synthetic=true;x.runtimeObservation.observedAt='2026-09-09T01:00:00.000Z';const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('runtime-evidence-must-be-observed-nonsynthetic'));assert.ok(r.reasonCodes.includes('runtime-observation-must-follow-promotion'));});
test('runtime unauthorized effects force rollback or revocation rather than retain',()=>{const x=base();x.runtimeObservation.unauthorizedEffectLedger.providerCalls=1;const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.equal(r.status,'C16_ROLLBACK_OR_REVOCATION_REQUIRED');assert.ok(r.reasonCodes.includes('runtime-unauthorized-effects-must-be-proven-zero'));});
test('runtime regression after a prior benchmark win is not retained',()=>{const x=base();x.runtimeObservation.behaviorRetained=false;const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('runtime-behavior-retention-not-observed'));});
test('builder cannot become its own runtime monitor, rollback verifier, or revocation verifier',()=>{const x=base();x.runtimeObservation.observerId='builder';x.rollbackRehearsal.verifierId='deployer';x.revocationReadiness.verifierId='builder';const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('runtime-monitor-must-be-independent-of-proposer-and-deployer'));assert.ok(r.reasonCodes.includes('rollback-verifier-must-be-independent-of-proposer-and-deployer'));assert.ok(r.reasonCodes.includes('revocation-verifier-must-be-independent-of-proposer-and-deployer'));});
test('ancestor builder lineage cannot recapture monitoring even under a new actor id',()=>{const x=base();x.runtimeObservation.observerLineageRef='lineage:builder';const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('runtime-monitor-lineage-must-be-independent-of-builder-lineage'));});
test('missing or mismatched rollback evidence blocks retention',()=>{const missing=base();delete missing.rollbackRehearsal;assert.ok(evaluateRecursiveImprovementRetention(missing).reasonCodes.includes('rollback-rehearsal-receipt-required'));const wrong=base();wrong.rollbackRehearsal.candidateRevision='1'.repeat(40);assert.ok(evaluateRecursiveImprovementRetention(wrong).reasonCodes.includes('rollback-candidate-identity-mismatch'));});
test('rollback must prove duplicate effects stayed zero and candidate did not silently reactivate',()=>{const x=base();x.rollbackRehearsal.duplicateEffectLedger.messages=1;x.rollbackRehearsal.candidateReactivatableAfterRollback=true;const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('rollback-duplicate-effects-must-be-proven-zero'));assert.ok(r.reasonCodes.includes('rollback-must-not-silently-reactivate-candidate'));});
test('revocation readiness for another candidate cannot protect this one',()=>{const x=base();x.revocationReadiness.candidateDigest='f'.repeat(64);const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('revocation-candidate-identity-mismatch'));});
test('future-dated runtime rollback and revocation evidence fail closed',()=>{const x=base();x.runtimeObservation.observedAt='2026-09-10T00:00:00.000Z';x.rollbackRehearsal.observedAt='2026-09-10T00:00:00.000Z';x.revocationReadiness.verifiedAt='2026-09-10T00:00:00.000Z';const r=evaluateRecursiveImprovementRetention(x);assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('runtime-observation-must-not-be-future-dated'));assert.ok(r.reasonCodes.includes('valid-nonfuture-rollback-observation-required'));assert.ok(r.reasonCodes.includes('valid-nonfuture-revocation-verification-required'));});
test('a positive verdict still explicitly withholds ASI promotion execution and business authority',()=>{const r=evaluateRecursiveImprovementRetention(base());assert.equal(r.ok,true);assert.equal(r.executionAuthority,'NONE');assert.equal(r.businessEffectAuthority,'NONE');assert.equal(r.externalEffectLedger.providerCalls,0);assert.match(r.receipt.truthBoundary,/NOT_ASI/);});
