import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileRemainingCutEvidence, verifyRemainingCutEvidenceIntegrity, loadRemainingCutEvidence } from '../src/remaining-cut-evidence.mjs';
import { applyRemainingCutEvidenceOverlay } from '../src/remaining-cut-evidence-overlay.mjs';

const SHA='a'.repeat(40),DIG=`sha256:${'b'.repeat(64)}`;
const ref=n=>`evidence://${n}`;
function messaging(){return{providerIndependenceObserved:true,paths:[{provider:'GMAIL',authorized:true,callable:true,senderIdentityEvidenceRef:ref('gmail-sender'),policyEvidenceRef:ref('gmail-policy'),activationEvidenceRef:ref('gmail-active'),canaryEvidenceRef:ref('gmail-canary')},{provider:'POSTAL',authorized:true,callable:true,senderIdentityEvidenceRef:ref('postal-sender'),policyEvidenceRef:ref('postal-policy'),activationEvidenceRef:ref('postal-active'),canaryEvidenceRef:ref('postal-canary')}]};}
function compile(cutId,observed){return compileRemainingCutEvidence({sourceCommit:SHA,cutId,observed,evidenceRefs:[ref(cutId.toLowerCase())]});}

test('messaging closes only with two distinct authorized callable evidence-bearing paths',()=>{const good=compile('MESSAGING_PROVIDER',messaging());assert.equal(good.ok,true);assert.equal(verifyRemainingCutEvidenceIntegrity(good),true);const one=structuredClone(messaging());one.paths.pop();assert.equal(compile('MESSAGING_PROVIDER',one).ok,false);const clone=structuredClone(messaging());clone.paths[1].provider='gmail';assert.equal(compile('MESSAGING_PROVIDER',clone).ok,false);});
test('payment requires live second rail or live PayPal recovery, never sandbox naming',()=>{assert.equal(compile('PAYMENT_PROVIDER',{mode:'PAYPAL_RECOVERY',provider:'PAYPAL',environment:'SANDBOX',authorized:true,callable:true,settlementOrRecoveryObserved:true,evidenceRef:ref('sandbox')}).ok,false);assert.equal(compile('PAYMENT_PROVIDER',{mode:'PAYPAL_RECOVERY',provider:'PAYPAL',environment:'LIVE',authorized:true,callable:true,settlementOrRecoveryObserved:true,evidenceRef:ref('paypal-recovery')}).ok,true);assert.equal(compile('PAYMENT_PROVIDER',{mode:'SECOND_RAIL',provider:'PAYPAL',environment:'LIVE',authorized:true,callable:true,settlementOrRecoveryObserved:true,evidenceRef:ref('not-independent')}).ok,false);assert.equal(compile('PAYMENT_PROVIDER',{mode:'SECOND_RAIL',provider:'PADDLE',environment:'LIVE',authorized:true,callable:true,settlementOrRecoveryObserved:true,evidenceRef:ref('paddle')}).ok,true);});
test('deployment requires a distinct provider plus exact boot cutover and rollback evidence',()=>{const observed={primaryProvider:'VERCEL',independentProvider:'OWNED_HOST',releaseId:'release-1',exactSourceBootObserved:true,cutoverObserved:true,rollbackObserved:true,healthEvidenceRef:ref('health'),cutoverEvidenceRef:ref('cutover'),rollbackEvidenceRef:ref('rollback')};assert.equal(compile('DEPLOYMENT_PROVIDER',observed).ok,true);assert.equal(compile('DEPLOYMENT_PROVIDER',{...observed,independentProvider:'VERCEL'}).ok,false);assert.equal(compile('DEPLOYMENT_PROVIDER',{...observed,rollbackObserved:false}).ok,false);});
test('credential custody requires factor-type and custody-domain diversity without secret material',()=>{const observed={ownerEnrollmentObserved:true,secretMaterialIncluded:false,threshold:2,factors:[{factorType:'hardware-key',custodyDomain:'owner-offline',evidenceRef:ref('factor-a')},{factorType:'recovery-code',custodyDomain:'independent-vault',evidenceRef:ref('factor-b')}]};assert.equal(compile('CREDENTIAL_CUSTODY',observed).ok,true);const oneDomain=structuredClone(observed);oneDomain.factors[1].custodyDomain='owner-offline';assert.equal(compile('CREDENTIAL_CUSTODY',oneDomain).ok,false);assert.equal(compile('CREDENTIAL_CUSTODY',{...observed,secretMaterialIncluded:true}).ok,false);});
test('sovereign identity requires same-identity rehearsal, liveness, consent, epoch and no successor authority',()=>{const observed={identityIdDigest:DIG,authorityEpoch:7,sameIdentityRecoveryObserved:true,ownerConsentObserved:true,livenessEvidenceRef:ref('liveness'),rehearsalEvidenceRef:ref('rehearsal'),successorAuthority:'NONE'};assert.equal(compile('SOVEREIGN_IDENTITY',observed).ok,true);assert.equal(compile('SOVEREIGN_IDENTITY',{...observed,successorAuthority:'SELF_APPOINTED'}).ok,false);assert.equal(compile('SOVEREIGN_IDENTITY',{...observed,sameIdentityRecoveryObserved:false}).ok,false);});
test('receipt source binding and digest integrity fail closed',()=>{const receipt=compile('MESSAGING_PROVIDER',messaging());const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ub-cut-evidence-'));try{const file=path.join(dir,'receipt.json');fs.writeFileSync(file,JSON.stringify(receipt));assert.equal(loadRemainingCutEvidence({path:file,expectedSourceCommit:SHA,expectedCutId:'MESSAGING_PROVIDER'}).accepted,true);assert.equal(loadRemainingCutEvidence({path:file,expectedSourceCommit:'c'.repeat(40),expectedCutId:'MESSAGING_PROVIDER'}).accepted,false);const forged=structuredClone(receipt);forged.observed.paths[0].callable=false;fs.writeFileSync(file,JSON.stringify(forged));assert.equal(loadRemainingCutEvidence({path:file,expectedSourceCommit:SHA,expectedCutId:'MESSAGING_PROVIDER'}).accepted,false);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('cut evidence is non-transitive and cannot close another provider or owner cut',()=>{const base={externalProviderCuts:['MESSAGING_PROVIDER','PAYMENT_PROVIDER','DEPLOYMENT_PROVIDER'],ownerCustodyCuts:['CREDENTIAL_CUSTODY','SOVEREIGN_IDENTITY']};const msg=compile('MESSAGING_PROVIDER',messaging());const accepted={accepted:true,cutId:'MESSAGING_PROVIDER',evidenceRef:ref('msg'),receiptDigest:msg.receiptDigest,sourceCommit:SHA};const out=applyRemainingCutEvidenceOverlay({cutSetReport:base,evidenceByCut:{MESSAGING_PROVIDER:accepted}});assert.deepEqual(out.externalProviderCuts,['PAYMENT_PROVIDER','DEPLOYMENT_PROVIDER']);assert.deepEqual(out.ownerCustodyCuts,base.ownerCustodyCuts);assert.deepEqual(out.remainingCutEvidenceOverlay.acceptedCuts,['MESSAGING_PROVIDER']);});
test('missing or mismatched evidence closes nothing',()=>{const base={externalProviderCuts:['MESSAGING_PROVIDER','PAYMENT_PROVIDER'],ownerCustodyCuts:['CREDENTIAL_CUSTODY']};assert.deepEqual(applyRemainingCutEvidenceOverlay({cutSetReport:base,evidenceByCut:{}}).externalProviderCuts,base.externalProviderCuts);const out=applyRemainingCutEvidenceOverlay({cutSetReport:base,evidenceByCut:{MESSAGING_PROVIDER:{accepted:true,cutId:'PAYMENT_PROVIDER',evidenceRef:ref('x'),receiptDigest:DIG,sourceCommit:SHA}}});assert.deepEqual(out.externalProviderCuts,base.externalProviderCuts);assert.ok(out.remainingCutEvidenceOverlay.rejectedClaims.includes('MESSAGING_PROVIDER:cut-id-mismatch'));});
test('secret-like evidence refs are refused',()=>{const receipt=compileRemainingCutEvidence({sourceCommit:SHA,cutId:'PAYMENT_PROVIDER',observed:{mode:'PAYPAL_RECOVERY',provider:'PAYPAL',environment:'LIVE',authorized:true,callable:true,settlementOrRecoveryObserved:true,evidenceRef:'https://provider.example/receipt?token=leak'},evidenceRefs:[ref('payment')]});assert.equal(receipt.ok,false);});
