import test from 'node:test';
import assert from 'node:assert/strict';
import { compileRestartRecoveryReceipt } from '../src/deploy-restart-recovery-receipt.mjs';
import { compileSourceRepositoryHostReceipt } from '../src/source-repository-host-receipt.mjs';
import { compileWebRuntimeHostReceipt } from '../src/web-runtime-host-receipt.mjs';
import { validateRestartRecoveryRuntimeEvidence, validateSourceRepositoryHostRuntimeEvidence, validateWebRuntimeHostRuntimeEvidence } from '../src/runtime-proof-ingestion.mjs';
const sha='a'.repeat(40),tree='b'.repeat(40),dig=`sha256:${'c'.repeat(64)}`;
const restartReceipt=()=>compileRestartRecoveryReceipt({sourceCommit:sha,environment:'POSTGRES',crashExitCode:91,replaySafeRecovered:1,replacementClaimCount:1,reconcileDeadLettered:true,reconcileReplacementClaimCount:0,cleanupOk:true,commands:['node scripts/deploy-restart-recovery-drill.mjs']});
const sourceReceipt=()=>compileSourceRepositoryHostReceipt({sourceCommit:sha,primaryHost:'GITHUB',independentHost:'MACALY_CLOUD',bundleDigest:dig,originalTree:tree,restoredCommit:sha,restoredTree:tree,trackedFileCount:2191,exportExitCode:0,restoreExitCode:0,cutoverExitCode:0,rollbackExitCode:0,cutoverStateDigest:dig,rollbackStateDigest:dig,cleanupOk:true,commands:['export','restore','cutover','rollback']});
const webReceipt=()=>compileWebRuntimeHostReceipt({sourceCommit:sha,primaryHost:'VERCEL',independentHost:'MACALY_CLOUD',healthHttpStatus:200,healthOk:true,healthBodyDigest:dig,processRole:'web',storeBackend:'json',version:'revenue-engine-1.4.0',outboundDisabled:true,discoveryDisabled:true,isolatedStateObserved:true,shutdownObserved:true,portReleased:true,primaryRouteMutated:false,cleanupOk:true,command:'node server.mjs'});

test('exact canonical restart receipt can become runtime evidence without authority',()=>{const result=validateRestartRecoveryRuntimeEvidence({receipt:restartReceipt(),expectedSourceCommit:sha,evidenceRef:'runtime:test'});assert.equal(result.accepted,true);assert.equal(result.businessEffectAuthority,'NONE');});
test('stale or mutated restart receipt cannot close a cut',()=>{assert.equal(validateRestartRecoveryRuntimeEvidence({receipt:restartReceipt(),expectedSourceCommit:'d'.repeat(40),evidenceRef:'runtime:test'}).accepted,false);const forged=restartReceipt();forged.observed.replacementClaimCount=2;assert.equal(validateRestartRecoveryRuntimeEvidence({receipt:forged,expectedSourceCommit:sha,evidenceRef:'runtime:test'}).accepted,false);});
test('exact source repository receipt is accepted and stale or mutated evidence fails closed',()=>{assert.equal(validateSourceRepositoryHostRuntimeEvidence({receipt:sourceReceipt(),expectedSourceCommit:sha,evidenceRef:'runtime:source'}).accepted,true);assert.equal(validateSourceRepositoryHostRuntimeEvidence({receipt:sourceReceipt(),expectedSourceCommit:'d'.repeat(40),evidenceRef:'runtime:source'}).accepted,false);const forged=sourceReceipt();forged.observed.restoredTree='e'.repeat(40);assert.equal(validateSourceRepositoryHostRuntimeEvidence({receipt:forged,expectedSourceCommit:sha,evidenceRef:'runtime:source'}).accepted,false);});
test('exact web runtime receipt is accepted and stale or mutated evidence fails closed',()=>{assert.equal(validateWebRuntimeHostRuntimeEvidence({receipt:webReceipt(),expectedSourceCommit:sha,evidenceRef:'runtime:web'}).accepted,true);assert.equal(validateWebRuntimeHostRuntimeEvidence({receipt:webReceipt(),expectedSourceCommit:'d'.repeat(40),evidenceRef:'runtime:web'}).accepted,false);const forged=webReceipt();forged.observed.primaryRouteMutated=true;assert.equal(validateWebRuntimeHostRuntimeEvidence({receipt:forged,expectedSourceCommit:sha,evidenceRef:'runtime:web'}).accepted,false);});
