import test from 'node:test';
import assert from 'node:assert/strict';
import {compileDurableWorkloadReceipt,compileCutoverRollbackReceipt,compileProviderLossReceipt} from '../src/runtime-transition-receipts.mjs';
const sha='a'.repeat(40), d='sha256:'+'b'.repeat(64), common={sourceCommit:sha,runtimeIdentity:'host:alternate',verifierIdentity:'auditor:1',evidenceRef:'receipt:obs',observedAt:'2026-09-09T03:10:00Z',evidenceClass:'OBSERVED_RUNTIME'};

test('durable workload compiles only from observed restart-preserved state',()=>{const r=compileDurableWorkloadReceipt({...common,workloadId:'job:1',beforeStateDigest:d,afterStateDigest:d,restartObserved:true,replacementWorkerObserved:true,persistedAcrossRestart:true,duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:false});assert.equal(r.persistedAcrossRestart,true);assert.match(r.receiptDigest,/^sha256:[0-9a-f]{64}$/);});
test('durable workload refuses state drift',()=>{const r=compileDurableWorkloadReceipt({...common,workloadId:'job:1',beforeStateDigest:d,afterStateDigest:'sha256:'+'c'.repeat(64),restartObserved:true,replacementWorkerObserved:true,persistedAcrossRestart:true,duplicateExternalEffects:0});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('workload-state-must-survive-restart'));});
test('durable workload refuses blind uncertain replay',()=>{const r=compileDurableWorkloadReceipt({...common,workloadId:'job:1',beforeStateDigest:d,afterStateDigest:d,restartObserved:true,replacementWorkerObserved:true,persistedAcrossRestart:true,duplicateExternalEffects:0,uncertainEffectBlindReplayObserved:true});assert.equal(r.ok,false);});
test('runtime cannot verify itself',()=>{const r=compileDurableWorkloadReceipt({...common,verifierIdentity:'host:alternate',workloadId:'job:1',beforeStateDigest:d,afterStateDigest:d,restartObserved:true,replacementWorkerObserved:true,persistedAcrossRestart:true,duplicateExternalEffects:0});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('runtime-cannot-self-verify'));});

test('cutover receipt requires actual return rollback',()=>{const r=compileCutoverRollbackReceipt({...common,fromRuntimeIdentity:'host:primary',toRuntimeIdentity:'host:alternate',cutoverSucceeded:true,boundedWorkloadSucceeded:true,rollbackExercised:true,rollbackSucceeded:true,rollbackRuntimeIdentity:'host:primary',duplicateExternalEffects:0});assert.equal(r.cutoverSucceeded,true);assert.equal(r.rollbackSucceeded,true);});
test('cutover refuses fake rollback destination',()=>{const r=compileCutoverRollbackReceipt({...common,fromRuntimeIdentity:'host:primary',toRuntimeIdentity:'host:alternate',cutoverSucceeded:true,boundedWorkloadSucceeded:true,rollbackExercised:true,rollbackSucceeded:true,rollbackRuntimeIdentity:'host:third',duplicateExternalEffects:0});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('rollback-must-return-to-source-runtime'));});
test('cutover refuses same runtime renamed as migration',()=>{const r=compileCutoverRollbackReceipt({...common,fromRuntimeIdentity:'host:alternate',toRuntimeIdentity:'host:alternate',cutoverSucceeded:true,boundedWorkloadSucceeded:true,rollbackExercised:true,rollbackSucceeded:true,rollbackRuntimeIdentity:'host:alternate',duplicateExternalEffects:0});assert.equal(r.ok,false);});

test('provider loss requires observed recovery on distinct provider',()=>{const r=compileProviderLossReceipt({...common,manifestDigest:d,failedProvider:'provider-a',alternateProvider:'provider-b',primaryUnavailable:true,alternateRestoreSucceeded:true,boundedWorkloadSucceeded:true,recoveryUsedPrimaryProvider:false,duplicateExternalEffects:0});assert.equal(r.receiptClass,'PROVIDER_LOSS');assert.equal(r.alternateProvider,'provider-b');});
test('provider loss refuses logical alias on same provider',()=>{const r=compileProviderLossReceipt({...common,manifestDigest:d,failedProvider:'provider-a',alternateProvider:'provider-a',primaryUnavailable:true,alternateRestoreSucceeded:true,boundedWorkloadSucceeded:true,recoveryUsedPrimaryProvider:false,duplicateExternalEffects:0});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('distinct-provider-boundary-required'));});
test('provider loss refuses recovery that secretly used failed provider',()=>{const r=compileProviderLossReceipt({...common,manifestDigest:d,failedProvider:'provider-a',alternateProvider:'provider-b',primaryUnavailable:true,alternateRestoreSucceeded:true,boundedWorkloadSucceeded:true,recoveryUsedPrimaryProvider:true,duplicateExternalEffects:0});assert.equal(r.ok,false);assert.ok(r.reasonCodes.includes('recovery-must-not-use-failed-provider'));});
test('provider loss refuses duplicate effects',()=>{const r=compileProviderLossReceipt({...common,manifestDigest:d,failedProvider:'provider-a',alternateProvider:'provider-b',primaryUnavailable:true,alternateRestoreSucceeded:true,boundedWorkloadSucceeded:true,recoveryUsedPrimaryProvider:false,duplicateExternalEffects:1});assert.equal(r.ok,false);});
