import test from 'node:test';
import assert from 'node:assert/strict';
import { applyRuntimeCutEvidenceOverlay } from '../src/runtime-cut-evidence-overlay.mjs';
const base={runtimeProofRequiredCuts:['SOURCE_REPOSITORY_HOST','DATABASE_STATE','WEB_RUNTIME_HOST','WORKER_SCHEDULER_PROCESS'],externalProviderCuts:['MODEL_PROVIDER'],ownerCustodyCuts:['CREDENTIAL_CUSTODY']};
const evidence=(ref)=>({accepted:true,evidenceRef:`runtime:${ref}`,receiptDigest:`sha256:${'a'.repeat(64)}`,sourceCommit:'b'.repeat(40)});

test('restart evidence closes only database and worker runtime cuts',()=>{const result=applyRuntimeCutEvidenceOverlay({cutSetReport:base,restartRecoveryEvidence:evidence('restart')});assert.deepEqual(result.runtimeProofRequiredCuts,['SOURCE_REPOSITORY_HOST','WEB_RUNTIME_HOST']);assert.deepEqual(result.runtimeEvidenceOverlay.closedRuntimeCuts,['DATABASE_STATE','WORKER_SCHEDULER_PROCESS']);assert.deepEqual(result.externalProviderCuts,['MODEL_PROVIDER']);});
test('source repository evidence closes only source host cut',()=>{const result=applyRuntimeCutEvidenceOverlay({cutSetReport:base,sourceRepositoryEvidence:evidence('source')});assert.deepEqual(result.runtimeProofRequiredCuts,['DATABASE_STATE','WEB_RUNTIME_HOST','WORKER_SCHEDULER_PROCESS']);assert.deepEqual(result.runtimeEvidenceOverlay.closedRuntimeCuts,['SOURCE_REPOSITORY_HOST']);});
test('web evidence closes only web runtime host cut',()=>{const result=applyRuntimeCutEvidenceOverlay({cutSetReport:base,webRuntimeEvidence:evidence('web')});assert.deepEqual(result.runtimeProofRequiredCuts,['SOURCE_REPOSITORY_HOST','DATABASE_STATE','WORKER_SCHEDULER_PROCESS']);assert.deepEqual(result.runtimeEvidenceOverlay.closedRuntimeCuts,['WEB_RUNTIME_HOST']);});
test('all three exact receipt classes close all runtime cuts but never provider or owner cuts',()=>{const result=applyRuntimeCutEvidenceOverlay({cutSetReport:base,sourceRepositoryEvidence:evidence('source'),restartRecoveryEvidence:evidence('restart'),webRuntimeEvidence:evidence('web')});assert.deepEqual(result.runtimeProofRequiredCuts,[]);assert.deepEqual(result.runtimeEvidenceOverlay.closedRuntimeCuts,base.runtimeProofRequiredCuts);assert.deepEqual(result.externalProviderCuts,base.externalProviderCuts);assert.deepEqual(result.ownerCustodyCuts,base.ownerCustodyCuts);});
test('rejected or absent runtime evidence closes nothing',()=>{const result=applyRuntimeCutEvidenceOverlay({cutSetReport:base,sourceRepositoryEvidence:{accepted:false},restartRecoveryEvidence:{accepted:false},webRuntimeEvidence:{accepted:false}});assert.deepEqual(result.runtimeProofRequiredCuts,base.runtimeProofRequiredCuts);assert.deepEqual(result.runtimeEvidenceOverlay.closedRuntimeCuts,[]);});
