import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {compileSandwichAutocatalyticDirective,compileSandwichAutocatalyticTask} from '../src/sandwich-autocatalytic-governor.mjs';

const HEAD='a'.repeat(40);
const closed={ok:true,status:'FINITE_ENGINEERING_ALREADY_CLOSED',baseRevision:HEAD,taskRequired:false};

test('post-finite governor refuses to compete with unfinished finite engineering',()=>{const result=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:{...closed,status:'FINITE_REQUIREMENT_TARGET_READY',taskRequired:true}});assert.equal(result.ok,false);assert.equal(result.status,'FINITE_COMPLETION_RETAINS_PRIORITY');});
test('exact-base finite closure audits connectome before future raid and topology',()=>{const result=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:closed});assert.equal(result.ok,true);assert.equal(result.status,'DESCENDANT_REQUIREMENT_GENESIS_READY');assert.equal(result.mode,'ONE_NEW_FINITE_REQUIREMENT_ONLY');assert.match(result.nextTransition,/AUDIT_CONNECTOME/);assert.match(result.nextTransition,/TEMPORAL_FOUNDRY/);assert.match(result.nextTransition,/TIMELINE_TOPOLOGY/);assert.match(result.connectomeLaw,/ISOLATED_CAPABILITY_IS_INCOMPLETE_CAPABILITY/);assert.match(result.connectomeLaw,/HEALTHY_CONNECTOME_MUST_NOT_MANUFACTURE_BRIDGE_WORK/);assert.match(result.futureRaidLaw,/FUTURE_LABEL_IS_NOT_A_WAITING_PERIOD/);assert.equal(result.externalEffectAuthority,'NONE');});
test('stale finite closure cannot drive a new descendant fold',()=>{const result=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:{...closed,baseRevision:'b'.repeat(40)}});assert.equal(result.ok,false);assert.match(result.reasonCodes.join(' '),/exact-base-finite-engineering-closure-required/);});
test('descendant task binds connectome, Future Raid and Wormhole without self-implementation',()=>{const directive=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:closed});const task=compileSandwichAutocatalyticTask({directive,date:new Date('2026-09-10T20:00:00Z')});assert.equal(task.taskId,`uberbond_sandwich_descendant_${HEAD.slice(0,24)}`);for(const c of ['connectome-autopoiesis-audit-required-before-descendant-selection','healthy-connectome-must-not-manufacture-bridge-work','isolated-capability-is-incomplete-capability','connectome-feature-still-requires-temporal-and-topology-binding','temporal-foundry-future-raid-required-before-topology','timeline-topology-challenge-required-before-admission','requirement-genesis-only-do-not-implement-same-cycle'])assert.ok(task.constraints.includes(c),c);for(const f of ['manufacture-connectome-debt-when-audit-is-healthy','treat-cognitive-edge-as-execution-authority','implement-newly-admitted-requirement-in-same-cycle','invent-founder-goal','claim-asi'])assert.ok(task.forbiddenActions.includes(f),f);for(const o of ['connectomeAudit','connectomeFeatureCandidate','futureCapabilityDecomposition','presentFunctionCapture','enablingPrimitive','timelineTopologyAnalysis','wormholeCandidates'])assert.ok(task.requiredOutputs.includes(o),o);for(const r of ['source:connectome-autopoiesis','source:uberbond-cognitive-graph','context:connectome-autopoiesis','doc:TEMPORAL_FOUNDRY_CANON','source:temporal-foundry','doc:TIMELINE_TOPOLOGY_ENGINE_CANON','source:timeline-topology-engine'])assert.ok(task.contextRefs.includes(r),r);assert.equal(task.consequenceClass,'LOCAL_PREPARATION');});
test('descendant objective survives canonical 1200-character relay ceiling with Connectome Future Raid and Wormhole intact',()=>{const directive=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:closed});const task=compileSandwichAutocatalyticTask({directive,date:new Date('2026-09-10T20:00:00Z')});assert.ok(task.objective.length<=1200,`objective was ${task.objective.length}`);assert.match(task.objective,/Connectome Autopoiesis/);assert.match(task.objective,/Temporal Foundry/);assert.match(task.objective,/Timeline Topology/);assert.match(task.objective,/NO_NOVEL_INTERNAL_GAP/);assert.match(task.objective,/do not implement it this cycle/i);assert.match(task.objective,/Never weaken requirements/);assert.match(task.objective,/Return one bounded AgentCodeChangeSet/);});
test('hosted Sandwich workflow is manual fallback only',()=>{const workflow=readFileSync(new URL('../.github/workflows/uberbond-sandwich-autocatalytic.yml',import.meta.url),'utf8');assert.match(workflow,/on:\s*\n\s*workflow_dispatch:/);assert.doesNotMatch(workflow,/\n\s*schedule:/);assert.doesNotMatch(workflow,/\n\s*workflow_run:/);assert.doesNotMatch(workflow,/cron:/);assert.match(workflow,/persist-credentials: false/);assert.match(workflow,/contents: read/);assert.doesNotMatch(workflow,/contents: write/);});
test('manual hosted fallback preserves truth regeneration before descendant seeding and dispatch',()=>{const workflow=readFileSync(new URL('../.github/workflows/uberbond-sandwich-autocatalytic.yml',import.meta.url),'utf8');const truth=workflow.indexOf('Regenerate exact-current terminal truth');const seed=workflow.indexOf('Seed one post-finite descendant requirement task');const dispatch=workflow.indexOf('Dispatch the next Sandwich fold to the trusted self-maintainer');assert.ok(truth>=0&&seed>truth&&dispatch>seed);assert.match(workflow,/node scripts\/terminal-realization\.mjs/);assert.match(workflow,/node scripts\/sandwich-autocatalytic-seed\.mjs/);});
