import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {compileSandwichAutocatalyticDirective,compileSandwichAutocatalyticTask} from '../src/sandwich-autocatalytic-governor.mjs';

const HEAD='a'.repeat(40);
const closed={ok:true,status:'FINITE_ENGINEERING_ALREADY_CLOSED',baseRevision:HEAD,taskRequired:false};

test('post-finite governor refuses to compete with unfinished finite engineering',()=>{const result=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:{...closed,status:'FINITE_REQUIREMENT_TARGET_READY',taskRequired:true}});assert.equal(result.ok,false);assert.equal(result.status,'FINITE_COMPLETION_RETAINS_PRIORITY');});
test('exact-base finite closure opens descendant genesis through timeline-topology challenge',()=>{const result=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:closed});assert.equal(result.ok,true);assert.equal(result.status,'DESCENDANT_REQUIREMENT_GENESIS_READY');assert.equal(result.mode,'ONE_NEW_FINITE_REQUIREMENT_ONLY');assert.match(result.nextTransition,/CHALLENGE_ITS_TIMELINE_TOPOLOGY/);assert.match(result.timelineLaw,/DELETE|SUBSTITUTED|PARALLELIZED/);assert.equal(result.externalEffectAuthority,'NONE');assert.equal(result.businessEffectAuthority,'NONE');});
test('stale finite closure cannot drive a new descendant fold',()=>{const result=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:{...closed,baseRevision:'b'.repeat(40)}});assert.equal(result.ok,false);assert.match(result.reasonCodes.join(' '),/exact-base-finite-engineering-closure-required/);});
test('descendant task requires topology challenge but still cannot implement in the same cycle',()=>{const directive=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:closed});const task=compileSandwichAutocatalyticTask({directive,date:new Date('2026-09-10T20:00:00Z')});assert.equal(task.taskId,`uberbond_sandwich_descendant_${HEAD.slice(0,24)}`);assert.ok(task.constraints.includes('timeline-topology-challenge-required-before-admission'));assert.ok(task.constraints.includes('preserve-terminal-contract-during-timeline-compression'));assert.ok(task.constraints.includes('evidence-bound-causal-floor-rebuttal-required-before-bypass'));assert.ok(task.constraints.includes('prefer-critical-path-elimination-over-local-duration-optimization'));assert.ok(task.constraints.includes('exactly-one-new-finite-requirement-maximum'));assert.ok(task.constraints.includes('requirement-genesis-only-do-not-implement-same-cycle'));assert.ok(task.constraints.includes('derive-only-from-existing-canonical-goals-and-invariants'));assert.ok(task.constraints.includes('stop-instead-of-manufacturing-work-when-no-novel-internal-gap-exists'));assert.ok(task.forbiddenActions.includes('change-terminal-contract-to-create-speedup'));assert.ok(task.forbiddenActions.includes('claim-causal-floor-bypass-without-rebuttal-evidence'));assert.ok(task.forbiddenActions.includes('implement-newly-admitted-requirement-in-same-cycle'));assert.ok(task.forbiddenActions.includes('invent-founder-goal'));assert.ok(task.forbiddenActions.includes('claim-asi'));assert.ok(task.requiredOutputs.includes('timelineTopologyAnalysis'));assert.ok(task.requiredOutputs.includes('wormholeCandidates'));assert.ok(task.contextRefs.includes('doc:TIMELINE_TOPOLOGY_ENGINE_CANON'));assert.ok(task.contextRefs.includes('source:timeline-topology-engine'));assert.equal(task.consequenceClass,'LOCAL_PREPARATION');});
test('descendant objective survives the canonical 1200-character relay ceiling with Wormhole and stop laws intact',()=>{const directive=compileSandwichAutocatalyticDirective({baseRevision:HEAD,finiteDirective:closed});const task=compileSandwichAutocatalyticTask({directive,date:new Date('2026-09-10T20:00:00Z')});assert.ok(task.objective.length<=1200,`objective was ${task.objective.length}`);assert.match(task.objective,/Timeline Topology Engine/);assert.match(task.objective,/critical-path time/i);assert.match(task.objective,/NO_NOVEL_INTERNAL_GAP/);assert.match(task.objective,/do not implement or claim it complete in this cycle/i);assert.match(task.objective,/Never weaken requirements/);assert.match(task.objective,/Return one bounded AgentCodeChangeSet/);});
test('hosted Sandwich workflow is manual fallback only',()=>{const workflow=readFileSync(new URL('../.github/workflows/uberbond-sandwich-autocatalytic.yml',import.meta.url),'utf8');assert.match(workflow,/on:\s*\n\s*workflow_dispatch:/);assert.doesNotMatch(workflow,/\n\s*schedule:/);assert.doesNotMatch(workflow,/\n\s*workflow_run:/);assert.doesNotMatch(workflow,/cron:/);assert.match(workflow,/persist-credentials: false/);assert.match(workflow,/contents: read/);assert.doesNotMatch(workflow,/contents: write/);});
test('manual hosted fallback preserves truth regeneration before descendant seeding and dispatch',()=>{const workflow=readFileSync(new URL('../.github/workflows/uberbond-sandwich-autocatalytic.yml',import.meta.url),'utf8');const truth=workflow.indexOf('Regenerate exact-current terminal truth');const seed=workflow.indexOf('Seed one post-finite descendant requirement task');const dispatch=workflow.indexOf('Dispatch the next Sandwich fold to the trusted self-maintainer');assert.ok(truth>=0&&seed>truth&&dispatch>seed);assert.match(workflow,/node scripts\/terminal-realization\.mjs/);assert.match(workflow,/node scripts\/sandwich-autocatalytic-seed\.mjs/);});
