import test from 'node:test';
import assert from 'node:assert/strict';
import { governVerifiedSelfMaintainerMerge } from '../.github/workflows/runtime/self-maintainer-merge-governor.mjs';

const BASE='a'.repeat(40);
const HEAD='b'.repeat(40);
const MERGED='c'.repeat(40);
const REPO='mohammedwessam2007/uberbondd';
const BEFORE='export const answer = 1;\n';
const AFTER='export const answer = 2;\n';

function response(status,payload){
  const raw=payload==null?'':JSON.stringify(payload);
  return {status,ok:status>=200&&status<300,async text(){return raw}};
}

function env(overrides={}){
  return {
    GITHUB_REPOSITORY:REPO,
    GITHUB_TOKEN:'test-token-not-a-real-secret',
    UBERBOND_VERIFICATION_MODE:'JOB_CHAIN',
    UBERBOND_VERIFICATION_JOB_RESULT:'success',
    UBERBOND_PR_NUMBER:'42',
    UBERBOND_VERIFY_HEAD_SHA:HEAD,
    UBERBOND_VERIFY_BASE_SHA:BASE,
    ...overrides
  };
}

function pr(filePath='src/autonomous-safe.mjs'){
  return {
    state:'open',draft:false,
    user:{login:'github-actions[bot]'},
    base:{ref:'main',sha:BASE},
    head:{ref:'uberbond/self-maintain/task_abc',sha:HEAD,repo:{full_name:REPO}},
    body:[
      'Generated by UberBond Self-Maintainer from a zero-network, credential-free verified change set.',
      '',
      'Task: task_safe_1',
      `Base: ${BASE}`,
      `Candidate commit: ${HEAD}`,
      `Change set: agent_changes_${'d'.repeat(24)}`,
      `Self-maintenance receipt: self_maint_${'e'.repeat(24)}`
    ].join('\n'),
    _filePath:filePath
  };
}

function harness({mainSha=BASE,filePath='src/autonomous-safe.mjs'}={}){
  const calls=[];
  const pull=pr(filePath);
  const fetchImpl=async(url,init={})=>{
    const u=new URL(url);calls.push({method:init.method||'GET',path:u.pathname,search:u.search,body:init.body||null});
    if(u.pathname.endsWith('/pulls/42')&&(init.method||'GET')==='GET')return response(200,pull);
    if(u.pathname.endsWith('/branches/main'))return response(200,{commit:{sha:mainSha}});
    if(u.pathname.endsWith('/pulls/42/commits'))return response(200,[{sha:HEAD,parents:[{sha:BASE}]}]);
    if(u.pathname.endsWith('/pulls/42/files'))return response(200,[{filename:filePath,status:'modified'}]);
    if(u.pathname.includes('/contents/')){
      const ref=u.searchParams.get('ref');
      return response(200,{type:'file',encoding:'base64',content:Buffer.from(ref===BASE?BEFORE:AFTER).toString('base64')});
    }
    if(u.pathname.endsWith('/pulls/42/merge')&&init.method==='PUT')return response(200,{merged:true,sha:MERGED,message:'merged'});
    if(u.pathname.endsWith('/dispatches')&&init.method==='POST')return response(204,null);
    throw new Error(`unexpected fetch ${init.method||'GET'} ${u.pathname}${u.search}`);
  };
  return {calls,fetchImpl};
}

test('exact independently verified local-preparation PR merges then wakes next cycle',async()=>{
  const h=harness();
  const result=await governVerifiedSelfMaintainerMerge({env:env(),fetchImpl:h.fetchImpl});
  assert.equal(result.ok,true);
  assert.equal(result.status,'SELF_MAINTAINER_CHANGE_MERGED_AND_CONTINUATION_DISPATCHED');
  assert.equal(result.mergedCommit,MERGED);
  assert.equal(result.continuation.dispatched,true);
  assert.equal(result.businessEffectAuthority,'NONE');
  assert.equal(result.externalEffectAuthority,'NONE');
  assert.equal(h.calls.filter(c=>c.method==='PUT'&&c.path.endsWith('/merge')).length,1);
  const dispatch=h.calls.find(c=>c.method==='POST'&&c.path.endsWith('/dispatches'));
  assert.ok(dispatch);
  assert.match(String(dispatch.body),/uberbond-self-maintainer-continuation/);
});

test('main movement after verification blocks merge rather than rebasing silently',async()=>{
  const h=harness({mainSha:'f'.repeat(40)});
  const result=await governVerifiedSelfMaintainerMerge({env:env(),fetchImpl:h.fetchImpl});
  assert.equal(result.ok,false);
  assert.equal(result.status,'STALE_BASE');
  assert.ok(result.reasonCodes.includes('main-advanced-revalidation-required'));
  assert.equal(h.calls.some(c=>c.method==='PUT'&&c.path.endsWith('/merge')),false);
});

test('autonomous modification of an existing evaluator requires human review',async()=>{
  const h=harness({filePath:'tests/existing-evaluator.test.mjs'});
  const result=await governVerifiedSelfMaintainerMerge({env:env(),fetchImpl:h.fetchImpl});
  assert.equal(result.ok,false);
  assert.ok(result.reasonCodes.includes('autonomous-existing-test-mutation-requires-human-review'));
  assert.equal(h.calls.some(c=>c.method==='PUT'&&c.path.endsWith('/merge')),false);
});

test('merge authority cannot be unlocked by caller claiming verification without job-chain success',async()=>{
  let calls=0;
  const result=await governVerifiedSelfMaintainerMerge({
    env:env({UBERBOND_VERIFICATION_JOB_RESULT:'failure'}),
    fetchImpl:async()=>{calls++;throw new Error('must not call GitHub')}
  });
  assert.equal(result.ok,false);
  assert.ok(result.reasonCodes.includes('successful-independent-verification-job-required'));
  assert.equal(calls,0);
});
