import test from 'node:test';
import assert from 'node:assert/strict';
import { admitSelfMaintainerPullRequest } from '../.github/workflows/runtime/self-maintainer-merge-governor.mjs';

const BASE = 'a'.repeat(40);
const HEAD = 'b'.repeat(40);
const REPO = 'mohammedwessam2007/uberbondd';

function pr(overrides = {}) {
  const base = {
    number: 777,
    state: 'open',
    draft: false,
    title: 'UberBond self-maintenance: bounded repair',
    body: [
      'Generated by UberBond Self-Maintainer from a zero-network, credential-free verified change set.', '',
      'Task: test-task', `Base: ${BASE}`, `Candidate commit: ${HEAD}`,
      'Change set: agent_changes_111111111111111111111111',
      'Self-maintenance receipt: self_maint_222222222222222222222222', '',
      'This PR has NOT been merged or deployed. Independent review and exact-head verification remain required.'
    ].join('\n'),
    commits: 1,
    base: { ref: 'main', sha: BASE, repo: { full_name: REPO } },
    head: { ref: 'uberbond/self-maintain/test-111111111111', sha: HEAD, repo: { full_name: REPO } }
  };
  return { ...base, ...overrides };
}
function files(overrides = {}) { return [{ filename: 'src/example-repair.mjs', status: 'modified', additions: 4, deletions: 2, patch: '@@ safe patch @@', ...overrides }]; }
function admit(p = pr(), f = files(), main = BASE, parents = [BASE]) {
  return admitSelfMaintainerPullRequest({ pullRequest: p, changedFiles: f, currentMainSha: main, repository: REPO, headParents: parents });
}

test('exact self-maintainer PR is admitted only for read-only verification', () => {
  const out = admit(); assert.equal(out.ok, true); assert.equal(out.status, 'ADMITTED_FOR_READ_ONLY_EXACT_HEAD_VERIFICATION');
  assert.equal(out.mergeAuthority, 'CONDITIONAL_AFTER_INDEPENDENT_READ_ONLY_VERIFICATION'); assert.equal(out.deploymentAuthority, 'NONE'); assert.equal(out.businessEffectAuthority, 'NONE');
});
test('stale base refuses instead of silently rebasing', () => { const out = admit(pr(), files(), 'c'.repeat(40)); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('pull-request-base-must-equal-current-main')); });
test('candidate commit parent must be exact admitted base', () => { const out = admit(pr(), files(), BASE, ['c'.repeat(40)]); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('candidate-commit-parent-must-equal-admitted-base')); });
test('merge commit ancestry is refused even if PR reports one commit', () => { const out = admit(pr(), files(), BASE, [BASE, 'c'.repeat(40)]); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('candidate-commit-parent-must-equal-admitted-base')); });
test('workflow edits are build protected', () => { const out = admit(pr(), files({ filename: '.github/workflows/evil.yml' })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('build-protected:'))); });
test('self-maintainer enforcement edits are sovereignty protected', () => { const out = admit(pr(), files({ filename: 'src/uberbond-self-maintainer.mjs' })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('sovereignty-protected:'))); });
test('existing deterministic tests cannot be weakened in an auto-merge candidate', () => { const out = admit(pr(), files({ filename: 'tests/example.test.mjs', status: 'modified' })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('existing-test-modification-refused:'))); });
test('new tests remain admissible as additive evidence', () => { const out = admit(pr(), files({ filename: 'tests/new-regression.test.mjs', status: 'added' })); assert.equal(out.ok, true); });
test('command-center API cannot be autonomously auto-merged', () => { const out = admit(pr(), files({ filename: 'api/command-center.mjs' })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('governor-high-consequence-surface:'))); });
test('public cockpit cannot be autonomously auto-merged', () => { const out = admit(pr(), files({ filename: 'public/command-center.js' })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('governor-high-consequence-surface:'))); });
test('fork PR cannot inherit autonomous merge authority', () => { const bad = pr({ head: { ref: 'uberbond/self-maintain/test-111111111111', sha: HEAD, repo: { full_name: 'attacker/fork' } } }); const out = admit(bad); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('same-repository-pull-request-required')); });
test('candidate SHA must be bound in PR body', () => { const bad = pr({ body: pr().body.replace(HEAD, 'c'.repeat(40)) }); const out = admit(bad); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('body-candidate-binding-required')); });
test('renames are refused rather than normalized into a bypass', () => { const out = admit(pr(), files({ status: 'renamed' })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('changed-file-status-refused:'))); });
test('non-removed files require textual GitHub patch evidence', () => { const out = admit(pr(), files({ patch: null })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.some(code => code.startsWith('textual-patch-required:'))); });
test('promotion remains a single atomic commit', () => { const out = admit(pr({ commits: 2 })); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('single-atomic-candidate-commit-required')); });
test('generic human PR cannot masquerade as self-maintainer promotion', () => { const bad = pr({ title: 'Fix a bug', head: { ref: 'feature/fix', sha: HEAD, repo: { full_name: REPO } } }); const out = admit(bad); assert.equal(out.ok, false); assert.ok(out.reasonCodes.includes('self-maintainer-branch-prefix-required')); assert.ok(out.reasonCodes.includes('self-maintainer-title-required')); });
