import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { compileSemanticRequirementTribunal } from '../src/semantic-requirement-tribunal.mjs';
const HEAD='a'.repeat(40);const H=v=>`sha256:${crypto.createHash('sha256').update(String(v)).digest('hex')}`;
const row=(id,state='VERIFIED_CURRENT')=>({canonicalId:id,literalNames:[id],class:'ORGAN',currentState:state,currentEvidence:{sourceModules:[`src/${id}.mjs`],testModules:[`tests/${id}.test.mjs`],reachability:'PRODUCTION'},sourceArtifacts:['artifacts/canon.json'],owningLane:'OMEGA-01'});
const coverage=rows=>({ok:true,status:'COVERAGE_MATRIX_COMPILED',sourceCommit:HEAD,rows,counts:{rows:rows.length}});
const finite=id=>({requirementId:id,requirementClass:'FINITE_BEHAVIOR',meaning:{sourceClass:'SECTION_BODY',sourceRef:`docs/canon.md#${id}`,bodyDigest:H(`body:${id}`),headingOnly:false},inputRefs:[`export:${id}`],observableBehaviorsOrRefusals:[`observable behavior for ${id}`],ownerRef:'OMEGA-01',callerRefs:['src/caller.mjs'],stateRefs:['state:ready'],sourceRefs:[`src/${id}.mjs`],testRefs:[`tests/${id}.test.mjs`],hostileFalsifiers:['wrong identity is refused'],recoveryBehavior:'stateless refusal remains deterministic after restart',runtimeEvidenceRequirement:'exact-source execution required',externalEvidenceRequirement:'NONE_FOR_INTERNAL_BEHAVIOR'});

test('complete behavior contract earns semantic zero-orphan receipt without runtime inflation',()=>{const out=compileSemanticRequirementTribunal({coverage:coverage([row('x')]),contracts:[finite('x')]});assert.equal(out.ok,true,JSON.stringify(out));assert.equal(out.status,'SEMANTIC_ZERO_ORPHAN_REQUIREMENTS_VERIFIED');assert.equal(out.counts.FINITE_BEHAVIOR,1);assert.equal(out.businessEffectAuthority,'NONE');});
test('heading or filename alone earns no semantic credit',()=>{const c=finite('x');c.meaning={sourceClass:'SECTION_BODY',sourceRef:'docs/canon.md#x',bodyDigest:H('x'),headingOnly:true};c.observableBehaviorsOrRefusals=['x'];const out=compileSemanticRequirementTribunal({coverage:coverage([row('x')]),contracts:[c]});assert.equal(out.ok,false);assert.ok(out.invalidContracts[0].reasonCodes.includes('heading-only-semantic-credit-prohibited:x'));assert.ok(out.invalidContracts[0].reasonCodes.includes('behavior-or-refusal-evidence-required:x'));});
test('generic contract without caller hostile recovery or test stays orphaned semantically',()=>{const c=finite('x');c.callerRefs=[];c.testRefs=[];c.hostileFalsifiers=[];delete c.recoveryBehavior;const out=compileSemanticRequirementTribunal({coverage:coverage([row('x')]),contracts:[c]});assert.equal(out.ok,false);const rs=out.invalidContracts[0].reasonCodes;assert.ok(rs.includes('caller-required:x'));assert.ok(rs.includes('behavior-test-required:x'));assert.ok(rs.includes('hostile-falsifier-required:x'));assert.ok(rs.includes('recovery-behavior-or-explicit-na-required:x'));});
test('test and source evidence cannot be rebound from another canonical row',()=>{const c=finite('x');c.sourceRefs=['src/y.mjs'];c.testRefs=['tests/y.test.mjs'];const out=compileSemanticRequirementTribunal({coverage:coverage([row('x')]),contracts:[c]});assert.equal(out.ok,false);const rs=out.invalidContracts[0].reasonCodes;assert.ok(rs.includes('semantic-source-must-bind-canonical-row-evidence:x'));assert.ok(rs.includes('semantic-test-must-bind-canonical-row-evidence:x'));});
test('semantic orphan and floating contract are both explicit',()=>{const out=compileSemanticRequirementTribunal({coverage:coverage([row('x'),row('y')]),contracts:[finite('x'),finite('z')]});assert.equal(out.ok,false);assert.deepEqual(out.semanticOrphans,['y']);assert.deepEqual(out.floatingContracts,['z']);});
test('external and elapsed boundaries cannot be closed by an implementation claim',()=>{for(const [state,klass,evidence] of [['EXTERNAL_BLOCKED','EXTERNAL','real provider/customer evidence required'],['ELAPSED_TIME_REQUIRED','ELAPSED','elapsed longitudinal observation required']]){const r=row('x',state);r.currentEvidence={sourceModules:[],testModules:[]};const c={requirementId:'x',requirementClass:klass,meaning:{sourceClass:'CANONICAL_RULE_BODY',sourceRef:'docs/canon.md#x',bodyDigest:H('body'),headingOnly:false},externalEvidenceRequirement:evidence,implementationClaim:true};const out=compileSemanticRequirementTribunal({coverage:coverage([r]),contracts:[c]});assert.equal(out.ok,false);assert.ok(out.invalidContracts[0].reasonCodes.some(x=>x.includes('boundary-cannot-be-closed-by-source')));}});
test('structural constitution requires semantic rationale and cannot invent build completion',()=>{const r=row('x','STRUCTURAL_NOT_A_BUILD_TARGET');r.currentEvidence={sourceModules:[],testModules:[]};const c={requirementId:'x',meaning:{sourceClass:'SECTION_BODY',sourceRef:'docs/canon.md#x',bodyDigest:H('body'),headingOnly:false},structuralRationale:'This is an ontology node arranging executable descendants.',implementationClaim:false};assert.equal(compileSemanticRequirementTribunal({coverage:coverage([r]),contracts:[c]}).ok,true);delete c.structuralRationale;assert.equal(compileSemanticRequirementTribunal({coverage:coverage([r]),contracts:[c]}).ok,false);});
test('parent-covered donor reference alias and structural terminal rows stay accounted without inflating finite work',()=>{for(const state of ['COVERED_BY_PARENT_ORGAN','HISTORICAL_DONOR_PRESERVED','REFERENCE_ONLY_BY_CANON','ALIAS_OF_CANONICAL_CONCEPT','DRAFT_DONOR']){const r=row(`x-${state}`,state);r.currentEvidence={sourceModules:[],testModules:[]};const c={requirementId:r.canonicalId,meaning:{sourceClass:'STRUCTURED_CANONICAL_VALUE',sourceRef:`artifacts/canon.json$.${state}`,bodyDigest:H(state),headingOnly:false},structuralRationale:`${state} is terminal accounting rather than an independent implementation target.`,implementationClaim:false};const out=compileSemanticRequirementTribunal({coverage:coverage([r]),contracts:[c]});assert.equal(out.ok,true,`${state}: ${JSON.stringify(out)}`);assert.equal(out.counts.STRUCTURAL_CONSTITUTION,1);assert.equal(out.counts.FINITE_BEHAVIOR,0);}});
test('open frontier remains nonterminal rather than entering finite denominator',()=>{const r=row('x','SPEC_ONLY');const c={requirementId:'x',requirementClass:'OPEN_ENDED_FRONTIER',meaning:{sourceClass:'SECTION_BODY',sourceRef:'docs/canon.md#x',bodyDigest:H('body'),headingOnly:false},frontierDefinition:'Continuing unknown-unknown discovery has no finite terminal state.'};const out=compileSemanticRequirementTribunal({coverage:coverage([r]),contracts:[c]});assert.equal(out.ok,true,JSON.stringify(out));assert.equal(out.counts.OPEN_ENDED_FRONTIER,1);assert.equal(out.counts.FINITE_BEHAVIOR,0);});
