import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compileAgentCodeChangeSet, contentSha256 } from '../src/agent-code-change-contract.mjs';
import { compileSovereignLocalPromotionAdmission, compileSovereignLocalPromotionReceipt, sovereignChangeFingerprint } from '../src/sovereign-local-promotion.mjs';
import { compileSovereignReleaseRequest, verifySovereignReleaseRequest } from '../src/sovereign-release-handoff.mjs';

const BASE='a'.repeat(40); const NEXT='b'.repeat(40); const BEFORE='export const value = 1;\n'; const AFTER='export const value = 2;\n';
function candidate(path='src/example.mjs', operation='UPDATE') {
  const change=operation==='CREATE'
    ? {operation,path,content:AFTER,rationale:'Add a bounded harmless module for local promotion testing.'}
    : {operation,path,beforeSha256:contentSha256(BEFORE),content:operation==='DELETE'?null:AFTER,rationale:'Repair a bounded harmless module after independent verification.'};
  return compileAgentCodeChangeSet({taskId:'task_local_promote_1',baseRevision:BASE,summary:'A bounded independently verified low-risk local source repair.',consequenceClass:'LOCAL_PREPARATION',verification:['node --check src/example.mjs'],changes:[change]});
}
function verified(cs=candidate(),overrides={}) {
  return {ok:true,status:'VERIFIED_CHANGESET_READY_FOR_SEPARATE_PROMOTION_AUTHORITY',baseRevision:BASE,taskId:cs.taskId,verifiedReceipt:{taskId:cs.taskId,changeSetId:cs.changeSetId,baseRevision:BASE,verifiedFingerprint:sovereignChangeFingerprint(cs),selfMaintenanceReceiptId:`self_maint_${'2'.repeat(24)}`},observedChangeSet:cs,promotion:'NOT_PERFORMED',signingAuthority:'NONE',deploymentAuthority:'NONE',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE',...overrides};
}
function admit(v=verified(),overrides={}) { return compileSovereignLocalPromotionAdmission({verifiedChange:v,currentHead:BASE,branchName:'main',worktreeClean:true,...overrides}); }

test('independently verified low-risk exact-base change is admitted',()=>{const out=admit();assert.equal(out.ok,true);assert.equal(out.status,'LOCAL_PROMOTION_ADMITTED_FOR_ISOLATED_STAGE_AND_FIXED_GATES');assert.deepEqual(out.fixedPostApplyChecks,['npm run check:syntax','npm run test:deterministic']);assert.equal(out.networkRequired,false);});
test('stale or dirty local main is refused',()=>{assert.ok(admit(verified(),{currentHead:'c'.repeat(40)}).reasonCodes.includes('verified-change-base-must-equal-current-head'));assert.ok(admit(verified(),{worktreeClean:false}).reasonCodes.includes('clean-local-main-required'));});
test('fingerprint substitution is refused',()=>{const v=verified();v.verifiedReceipt.verifiedFingerprint='f'.repeat(64);const out=admit(v);assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('verified-fingerprint-mismatch'));});
test('verified receipt cannot smuggle deployment authority',()=>{const out=admit(verified(candidate(),{deploymentAuthority:'GRANTED'}));assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('verified-change-cannot-carry-deployment-authority'));});
test('local promoter refuses its own control plane even if generic change contract admits it',()=>{const cs=candidate('ops/sovereign/new-helper.mjs','CREATE');assert.equal(cs.ok,true);const out=admit(verified(cs));assert.equal(out.ok,false);assert.ok(out.reasonCodes.some(code=>code.startsWith('local-promotion-control-surface-protected:')));});
test('existing test modification is refused by local promotion layer',()=>{const cs=candidate('tests/harmless-regression.test.mjs','UPDATE');assert.equal(cs.ok,true);const out=admit(verified(cs));assert.equal(out.ok,false);assert.ok(out.reasonCodes.some(code=>code.startsWith('existing-test-modification-refused:')));});
test('promotion receipt requires both fixed gates',()=>{const a=admit();const weak=compileSovereignLocalPromotionReceipt({admission:a,promotionCommitSha:NEXT,parentSha:BASE,verification:[{command:'npm run check:syntax',status:'PASS'}]});assert.equal(weak.ok,false);assert.ok(weak.reasonCodes.includes('fixed-post-apply-check-required:npm run test:deterministic'));});
test('verified local main promotion compiles an offline release request without PR fiction',()=>{const a=admit();const p=compileSovereignLocalPromotionReceipt({admission:a,promotionCommitSha:NEXT,parentSha:BASE,verification:[{command:'npm run check:syntax',status:'PASS'},{command:'npm run test:deterministic',status:'PASS'}]});assert.equal(p.ok,true);const r=compileSovereignReleaseRequest({promotionReceipt:p});assert.equal(r.ok,true);assert.equal(r.promotionClass,'LOCAL_MAIN_FAST_FORWARD');assert.equal(r.promotionRef,'refs/heads/main');assert.equal(r.prNumber,null);assert.equal(r.sourceCommit,NEXT);assert.equal(r.signingAuthority,'NOT_GRANTED_BY_REQUEST');assert.equal(verifySovereignReleaseRequest(r).ok,true);});
test('local release request tampering is detected',()=>{const a=admit();const p=compileSovereignLocalPromotionReceipt({admission:a,promotionCommitSha:NEXT,parentSha:BASE,verification:[{command:'npm run check:syntax',status:'PASS'},{command:'npm run test:deterministic',status:'PASS'}]});const r=compileSovereignReleaseRequest({promotionReceipt:p});r.promotionRef='refs/heads/evil';const v=verifySovereignReleaseRequest(r);assert.equal(v.ok,false);assert.ok(v.reasonCodes.includes('local-main-promotion-ref-required'));assert.ok(v.reasonCodes.includes('release-request-digest-mismatch'));});
test('runtime promoter is zero-network and installer separates identities',()=>{const runtime=readFileSync(new URL('../scripts/sovereign-local-promote.mjs',import.meta.url),'utf8');const service=readFileSync(new URL('../ops/sovereign/uberbond-local-promote.service',import.meta.url),'utf8');const installer=readFileSync(new URL('../ops/sovereign/install-authoring-node.sh',import.meta.url),'utf8');assert.doesNotMatch(runtime,/\bfetch\s*\(|https?:\/\//);assert.match(service,/^PrivateNetwork=true$/m);assert.match(service,/^User=uberbond-promoter$/m);assert.match(installer,/uberbond-promoter/);assert.match(installer,/chown -R uberbond-promoter:uberbond-autonomy/);assert.match(installer,/release signing authority must not live/i);});
test('promotion success wakes truth-first authoring without giving promoter network',()=>{const pathUnit=readFileSync(new URL('../ops/sovereign/uberbond-authoring-after-promotion.path',import.meta.url),'utf8');const promotePath=readFileSync(new URL('../ops/sovereign/uberbond-local-promote.path',import.meta.url),'utf8');assert.match(promotePath,/verified\.json/);assert.match(pathUnit,/promotion-receipt\.json/);assert.match(pathUnit,/Unit=uberbond-authoring\.service/);});
