import test from 'node:test';
import assert from 'node:assert/strict';
import {compileSovereignRuntimeGraduation,exactSovereignRuntimeGraduationReceipt,SOVEREIGN_RUNTIME_GRADUATION_VERSION,SOVEREIGN_RUNTIME_REHEARSAL_STATUS} from '../src/sovereign-runtime-graduation.mjs';

const commit='c'.repeat(40),digest='d'.repeat(64),releaseName=`release-${commit.slice(0,12)}-${digest.slice(0,16)}`,sequence='20260910143000';
const signer={ok:true,status:'SIGNED_RELEASE_READY_IN_OFFLINE_OUTBOX',requestDigest:digest,sourceCommit:commit,releaseName,signingAuthority:'SEPARATE_OFFLINE_SIGNER_ONLY',deploymentAuthority:'NONE',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE'};
const courier={ok:true,status:'SIGNED_RELEASE_COURIERED_TO_RUNTIME_INBOX',releaseName,signingAuthority:'NONE',deploymentAuthority:'NONE',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE'};
const base={signerReceipt:signer,courierReceipt:courier,appliedMarkerName:`APPLIED-${releaseName}-20260910T143100Z`,appliedMarkerContent:releaseName,releaseEnv:{SOURCE_COMMIT:commit,RELEASE_SEQUENCE:sequence},runtimeState:{CURRENT_SOURCE_COMMIT:commit,CURRENT_RELEASE_SEQUENCE:sequence},runtimeObserved:true,reconciliationObserved:true,containers:{postgres:{running:true,healthy:true},web:{running:true,healthy:true},worker:{running:true}}};

test('correlated physical runtime evidence compiles one narrow graduation receipt',()=>{const out=compileSovereignRuntimeGraduation(base);assert.equal(out.ok,true);assert.equal(out.schemaVersion,SOVEREIGN_RUNTIME_GRADUATION_VERSION);assert.equal(out.status,SOVEREIGN_RUNTIME_REHEARSAL_STATUS);assert.equal(out.rehearsalObserved,true);assert.equal(out.separateSignerObserved,true);assert.equal(out.releaseCourierObserved,true);assert.equal(exactSovereignRuntimeGraduationReceipt(out,commit),true);});
test('signer receipt cannot lie about separate authority',()=>{const out=compileSovereignRuntimeGraduation({...base,signerReceipt:{...signer,signingAuthority:'LOCAL_PROCESS_ONLY'}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('exact-offline-signer-receipt-required'));});
test('release name is cryptographically-shaped and bound to commit plus request digest',()=>{const out=compileSovereignRuntimeGraduation({...base,signerReceipt:{...signer,releaseName:`release-${'e'.repeat(12)}-${digest.slice(0,16)}`}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('exact-offline-signer-receipt-required'));});
test('courier receipt must identify the exact signer release and zero signing authority',()=>{const out=compileSovereignRuntimeGraduation({...base,courierReceipt:{...courier,releaseName:`release-${commit.slice(0,12)}-${'e'.repeat(16)}`,signingAuthority:'SEPARATE_OFFLINE_SIGNER_ONLY'}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('correlated-release-courier-receipt-required'));});
test('runtime APPLIED marker cannot be stale or point at another release',()=>{const out=compileSovereignRuntimeGraduation({...base,appliedMarkerContent:'release-deadbeefdead-deadbeefdeadbeef'});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('correlated-runtime-applied-marker-required'));});
test('runtime state cannot graduate a different source commit',()=>{const out=compileSovereignRuntimeGraduation({...base,runtimeState:{...base.runtimeState,CURRENT_SOURCE_COMMIT:'e'.repeat(40)}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('runtime-state-source-must-equal-signer-source'));});
test('runtime sequence cannot drift from the signed release sequence',()=>{const out=compileSovereignRuntimeGraduation({...base,runtimeState:{...base.runtimeState,CURRENT_RELEASE_SEQUENCE:'20260910143100'}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('runtime-state-sequence-must-equal-signed-release-sequence'));});
test('healthy processes without independent reconciliation are not a rehearsal',()=>{const out=compileSovereignRuntimeGraduation({...base,reconciliationObserved:false});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('independent-runtime-reconciliation-required'));});
test('unhealthy web or postgres blocks graduation',()=>{for(const containers of [{...base.containers,web:{running:true,healthy:false}},{...base.containers,postgres:{running:false,healthy:false}}]){const out=compileSovereignRuntimeGraduation({...base,containers});assert.equal(out.ok,false);}});
test('forged graduation receipt missing correlations is rejected by bootstrap verifier',()=>{assert.equal(exactSovereignRuntimeGraduationReceipt({ok:true,schemaVersion:SOVEREIGN_RUNTIME_GRADUATION_VERSION,status:SOVEREIGN_RUNTIME_REHEARSAL_STATUS,rehearsalObserved:true,separateSignerObserved:true,releaseCourierObserved:true,runtimeAppliedObserved:true,reconciliationObserved:false,sourceCommit:commit,releaseName,releaseSequence:sequence},commit),false);});
