import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { contentSha256 } from '../src/agent-code-change-contract.mjs';
import { compileNativeWorkerModelPrompt, compileNativeWorkerProposal } from '../src/sovereign-native-local-worker.mjs';
import { SANDWICH_DESCENDANT_CANON_PATH } from '../src/sandwich-descendant-admission.mjs';

const BASE='a'.repeat(40);
const BEFORE='export const value = 1;\n';
function task(overrides={}){return{taskId:'uberbond_native_worker_test',objective:'Repair one bounded source defect.',consequenceClass:'LOCAL_PREPARATION',acceptanceTests:['npm run check:syntax','npm run test:deterministic'],constraints:[`exact-base-revision:${BASE}`],...overrides};}
function proposal(overrides={}){return{decision:'CHANGE',summary:'Repair the bounded module without widening authority.',changes:[{operation:'UPDATE',path:'src/example.mjs',content:'export const value = 2;\n',rationale:'Fix the bounded local behavior.'}],...overrides};}
function sandwichTask(){return task({taskId:`uberbond_sandwich_descendant_${BASE.slice(0,24)}`,taskClass:'SANDWICH_DESCENDANT_GENESIS',objective:'Discover one stronger descendant gap.',constraints:[`exact-base-revision:${BASE}`,'sandwich-autocatalytic-descendant-genesis','requirement-genesis-only-do-not-implement-same-cycle','temporal-foundry-future-raid-required-before-topology','timeline-topology-challenge-required-before-admission']});}
const north={schemaVersion:'test',canonicalDefinition:'test',terminalTriad:['Mohamed provides will','UberBond provides intelligence','Reality provides feedback'],canonicalHierarchy:['SOVEREIGN_COGNITIVE_CONTINUUM'],terminalConcepts:['GENESIS','Wallbreaker'],containedPersonalCivilizationSystems:['Life Knowledge Graph'],supportingEconomicAndTechnicalDonors:['Capability Genome']};
const descendant={name:'Representation Escape Compiler',foldClass:'INTERNAL_SOURCE',canonicalGoalRefs:['GENESIS','Wallbreaker'],dependencies:[],acceptanceEvidence:['SOURCE: compiler produces bounded alternate representations','TEST: hostile test refuses duplicate or authority-widening representation'],rationale:'A missing reusable representation primitive limits existing GENESIS and Wallbreaker capability.'};
const futureCapability={futureCapabilityName:'Machine-native representation discovery',terminalContract:'Discover stronger representations without changing founder goals or truth boundaries.',horizonLabel:'future UberBond descendant',terminalFunctionIds:['serve'],functions:[
  {id:'canon',label:'Canonical goal and truth context',weight:20,requires:[],realizationState:'PRESENT_VERIFIED',evidenceRefs:['context:canonical-goals']},
  {id:'escape',label:'Reusable representation escape',weight:50,requires:['canon'],realizationState:'INTERNAL_PRIMITIVE_MISSING',evidenceRefs:[]},
  {id:'serve',label:'Feed stronger representation into bounded descendant search',weight:30,requires:['escape'],realizationState:'INTERNAL_PRIMITIVE_MISSING',evidenceRefs:[]}
]};
function temporalRaid(requirementName=descendant.name){return{futureCapability,primitiveCandidate:{requirementName,name:'Pull representation escape function into present descendant generation',unlockFunctionIds:['escape','serve'],evidenceRefs:['context:GENESIS-and-Wallbreaker'],rationale:'The missing internal representation primitive is downstream only of already evidenced canonical context and increases present future-function capture.'}};}
const topologyGraph={objective:'Preserve the same stronger-descendant terminal contract',terminalIds:['z'],nodes:[
  {id:'prep',label:'manual preparation',durationMs:100,requires:[],boundaryClass:'COORDINATION_OVERHEAD',necessity:'ASSUMPTION_ONLY',evidenceRefs:[]},
  {id:'z',label:'terminal capability requirement',durationMs:10,requires:['prep'],boundaryClass:'COMPUTE',necessity:'REQUIRED_BUT_COMPRESSIBLE',evidenceRefs:[]}
]};
function wormholeChallenge(subjectRequirementName=descendant.name){const projected=structuredClone(topologyGraph);projected.nodes=projected.nodes.filter(n=>n.id!=='prep');projected.nodes[0].requires=[];return{subjectRequirementName,baselineGraph:topologyGraph,decision:'WORMHOLE',name:'compile away manual preparation',mechanismClass:'DELETE_REQUIREMENT',projectedGraph:projected,evidenceRefs:['context:exact-current-topology'],transformations:[{targetId:'prep',kind:'DELETE_REQUIREMENT',evidenceRefs:['context:exact-current-topology'],causalBoundaryRebuttalRefs:[]},{targetId:'z',kind:'PARALLELIZE_DEPENDENCIES',evidenceRefs:['context:exact-current-topology'],causalBoundaryRebuttalRefs:[]}]};}

test('model prompt is bounded candidate-only authority',()=>{const out=compileNativeWorkerModelPrompt({task:task(),baseRevision:BASE,context:[{path:'src/example.mjs',content:BEFORE}]});assert.equal(out.ok,true);assert.match(out.system,/never merge, sign, deploy/i);assert.equal(out.businessEffectAuthority,'NONE');assert.equal(out.externalEffectAuthority,'NONE');});

test('trusted worker derives before hash and task-owned verification outside model',()=>{const out=compileNativeWorkerProposal({task:task(),baseRevision:BASE,proposal:{...proposal(),verification:['echo fake-pass']},sourceSnapshot:{'src/example.mjs':{exists:true,content:BEFORE}}});assert.equal(out.ok,true);assert.equal(out.codeChangeSet.changes[0].beforeSha256,contentSha256(BEFORE));assert.deepEqual(out.codeChangeSet.verification,['npm run check:syntax','npm run test:deterministic']);assert.equal(JSON.stringify(out).includes('echo fake-pass'),false);});

test('canonical code-change constitution still refuses protected paths',()=>{const out=compileNativeWorkerProposal({task:task(),baseRevision:BASE,proposal:proposal({changes:[{operation:'UPDATE',path:'package.json',content:'{}\n',rationale:'Try to rewrite the build graph.'}]}),sourceSnapshot:{'package.json':{exists:true,content:'{}\n'}}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.some(code=>code.includes('protected-path')));});

test('model STOP is evidence rather than a fabricated patch',()=>{const out=compileNativeWorkerProposal({task:task(),baseRevision:BASE,proposal:{decision:'STOP',summary:'No safe patch.',reasonCodes:['owner-gated-control-surface']},sourceSnapshot:{}});assert.equal(out.ok,false);assert.equal(out.status,'SOVEREIGN_NATIVE_LOCAL_WORKER_STOP');assert.ok(out.reasonCodes.includes('owner-gated-control-surface'));});

test('Sandwich genesis model cannot choose a file or implement its own requirement',()=>{const prompt=compileNativeWorkerModelPrompt({task:sandwichTask(),baseRevision:BASE,context:[]});assert.equal(prompt.ok,true);assert.match(prompt.system,/Do not return file changes/);assert.match(prompt.system,/trusted.*appends/i);assert.match(prompt.system,/cannot.*implement the requirement/i);assert.match(prompt.system,/Temporal Foundry/i);assert.match(prompt.system,/Timeline Topology/i);assert.match(prompt.system,/requirementName/);assert.match(prompt.system,/subjectRequirementName/);assert.equal(prompt.task.taskClass,'SANDWICH_DESCENDANT_GENESIS');const attempted=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'try bypass',descendantRequirement:descendant,changes:[{operation:'UPDATE',path:'src/anything.mjs',content:'bad'}]},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:`${JSON.stringify(north)}\n`}}});assert.equal(attempted.ok,false);assert.ok(attempted.reasonCodes.includes('sandwich-genesis-file-changes-forbidden'));});

test('Sandwich admission refuses a gap when the model skipped Temporal Foundry',()=>{const raw=`${JSON.stringify(north,null,2)}\n`;const out=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'skip future raid',timelineTopologyChallenge:wormholeChallenge(),descendantRequirement:descendant},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:raw}}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('temporal-foundry-raid-required-before-sandwich-admission'));});

test('Temporal Foundry receipt cannot be replayed beside a different descendant requirement',()=>{const raw=`${JSON.stringify(north,null,2)}\n`;const substituted={...descendant,name:'Different Capability'};const out=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'attempt future-raid replay',temporalFoundry:temporalRaid(descendant.name),timelineTopologyChallenge:wormholeChallenge(substituted.name),descendantRequirement:substituted},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:raw}}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('temporal-foundry-subject-must-match-descendant-requirement'));});

test('Sandwich admission refuses a gap when the model skipped Timeline Topology after a valid future raid',()=>{const raw=`${JSON.stringify(north,null,2)}\n`;const out=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'skip topology',temporalFoundry:temporalRaid(),descendantRequirement:descendant},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:raw}}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('timeline-topology-challenge-required-before-sandwich-admission'));});

test('trusted Sandwich compiler validates future-function capture then topology before one canonical append',()=>{const raw=`${JSON.stringify(north,null,2)}\n`;const out=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'admit one missing representation capability',temporalFoundry:temporalRaid(),timelineTopologyChallenge:wormholeChallenge(),descendantRequirement:descendant},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:raw}}});assert.equal(out.ok,true);assert.equal(out.codeChangeSet.changes.length,1);assert.equal(out.codeChangeSet.changes[0].path,SANDWICH_DESCENDANT_CANON_PATH);assert.equal(out.codeChangeSet.changes[0].beforeSha256,contentSha256(raw));const after=JSON.parse(out.codeChangeSet.changes[0].content);assert.equal(after.terminalConcepts.length,north.terminalConcepts.length+1);const admitted=after.terminalConcepts.at(-1);assert.equal(admitted.implementationForbiddenInAdmission,true);assert.equal(admitted.admittedFromBaseRevision,BASE);assert.equal(admitted.temporalFoundryEvidence.futureFunctionWeightPulledForward,80);assert.equal(admitted.temporalFoundryEvidence.presentFunctionCaptureRatio,0.2);assert.equal(admitted.temporalFoundryEvidence.projectedFunctionCaptureRatio,1);assert.equal(admitted.temporalFoundryEvidence.subjectRequirementName,descendant.name);assert.match(admitted.temporalFoundryEvidence.subjectRequirementSha256,/^[a-f0-9]{64}$/);assert.equal(admitted.timelineTopologyEvidence.decision,'WORMHOLE');assert.equal(admitted.timelineTopologyEvidence.terminalContractPreserved,true);assert.equal(admitted.timelineTopologyEvidence.criticalPathSavingsMs,100);assert.equal(admitted.timelineTopologyEvidence.subjectRequirementName,descendant.name);assert.equal(admitted.timelineTopologyEvidence.subjectRequirementSha256,admitted.temporalFoundryEvidence.subjectRequirementSha256);});

test('a valid topology receipt cannot be replayed beside a different descendant requirement',()=>{const raw=`${JSON.stringify(north,null,2)}\n`;const substituted={...descendant,name:'Different Capability'};const out=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'attempt challenge replay',temporalFoundry:temporalRaid(substituted.name),timelineTopologyChallenge:wormholeChallenge(descendant.name),descendantRequirement:substituted},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:raw}}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('timeline-topology-subject-must-match-descendant-requirement'));});

test('goalpost-moving topology challenge cannot reach Sandwich canon',()=>{const challenge=wormholeChallenge();challenge.projectedGraph.objective='A different easier terminal contract';const raw=`${JSON.stringify(north,null,2)}\n`;const out=compileNativeWorkerProposal({task:sandwichTask(),baseRevision:BASE,proposal:{decision:'CHANGE',summary:'cheat',temporalFoundry:temporalRaid(),timelineTopologyChallenge:challenge,descendantRequirement:descendant},sourceSnapshot:{[SANDWICH_DESCENDANT_CANON_PATH]:{exists:true,content:raw}}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('terminal-objective-mutation-refused'));});

test('sovereign Sandwich worker receives Temporal Foundry and Wormhole engines as context',()=>{const source=readFileSync(new URL('../scripts/sovereign-native-local-model-worker.mjs',import.meta.url),'utf8');assert.match(source,/docs\/TEMPORAL_FOUNDRY_CANON\.md/);assert.match(source,/src\/temporal-foundry\.mjs/);assert.match(source,/docs\/TIMELINE_TOPOLOGY_ENGINE_CANON\.md/);assert.match(source,/src\/timeline-topology-engine\.mjs/);});

test('worker has no IP network and reaches model only through Unix socket',()=>{const service=readFileSync(new URL('../ops/sovereign/uberbond-local-worker.service',import.meta.url),'utf8');assert.match(service,/^PrivateNetwork=true$/m);assert.match(service,/^RestrictAddressFamilies=AF_UNIX$/m);assert.match(service,/\/run\/uberbond-model/);assert.match(service,/^SupplementaryGroups=uberbond-model$/m);});

test('model proxy can reach host loopback but not public IP network and verifies model identity',()=>{const service=readFileSync(new URL('../ops/sovereign/uberbond-local-model-proxy.service',import.meta.url),'utf8');const source=readFileSync(new URL('../scripts/sovereign-local-model-proxy.mjs',import.meta.url),'utf8');assert.match(service,/^IPAddressDeny=any$/m);assert.match(service,/^IPAddressAllow=localhost$/m);assert.match(service,/^RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX$/m);assert.match(source,/model-proxy-endpoint-must-be-host-loopback-http/);assert.match(source,/MODEL_PROXY_IDENTITY_MISMATCH/);assert.doesNotMatch(source,/https:\/\/(api\.|www\.|github|vercel|openai|anthropic)/i);});

test('installer owns the native worker but keeps it disabled until a real local model is configured',()=>{const installer=readFileSync(new URL('../ops/sovereign/install-authoring-node.sh',import.meta.url),'utf8');assert.match(installer,/UBERBOND_LOCAL_WORKER_EXECUTABLE=\/opt\/uberbond\/control\/uberbond-native-local-worker/);assert.match(installer,/UBERBOND_ISOLATED_WORKER_ENABLED=false/);assert.match(installer,/configure-local-model\.sh/);assert.match(installer,/uberbond-model-proxy/);assert.match(installer,/release signing authority must not live/i);});

test('local model configuration only accepts owner-host loopback and explicitly enables the worker',()=>{const cfg=readFileSync(new URL('../ops/sovereign/configure-local-model.sh',import.meta.url),'utf8');assert.equal(cfg.includes('127\\.0\\.0\\.1|localhost|\\[::1\\]'),true);assert.match(cfg,/UBERBOND_ISOLATED_WORKER_ENABLED=true/);assert.match(cfg,/UBERBOND_FOUNDER_DIALOGUE_ENABLED=true/);assert.match(cfg,/OPEN_MODEL_AGENT_ENABLED=true/);assert.match(cfg,/usermod -a -G uberbond-model uberbond-author/);});

test('generic isolated runner preserves bounded worker failure reasons for strategy mutation',()=>{const runner=readFileSync(new URL('../scripts/sovereign-local-worker-runner.mjs',import.meta.url),'utf8');assert.match(runner,/boundedWorkerFailureObserved/);assert.match(runner,/boundedFailure\?\.reasonCodes/);assert.match(runner,/workerExitCode/);});
