import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const source=readFileSync(new URL('../scripts/sovereign-bootstrap-doctor.mjs',import.meta.url),'utf8');

test('doctor is local evidence collection rather than a cloud activation path',()=>{assert.doesNotMatch(source,/https:\/\//);assert.doesNotMatch(source,/api\.github|vercel\.com|openai\.com|anthropic\.com/i);assert.match(source,/systemctl/);assert.match(source,/http:\/\/\$\{host\}:\$\{port\}\/api\/status/);});
test('doctor requires real source contracts and exact local git truth',()=>{assert.match(source,/git',\['rev-parse','HEAD'\]/);assert.match(source,/git',\['status','--porcelain'\]/);assert.match(source,/REQUIRED_SOURCE_CONTRACTS/);assert.match(source,/continuousAuthoringPulse:'scripts\/sovereign-continuous-authoring-pulse\.mjs'/);assert.match(source,/lstat/);assert.match(source,/isSymbolicLink/);});
test('doctor verifies installed one-minute Sandwich-aware authoring rather than trusting repository text',()=>{assert.match(source,/systemctl',\['cat',UNIT_NAMES\.authoringTimer\]/);assert.match(source,/OnUnitInactiveSec=60s/);assert.match(source,/AccuracySec=1s/);assert.match(source,/RandomizedDelaySec=0/);assert.match(source,/\/opt\/uberbond\/control\/uberbond-authorctl/);assert.match(source,/scripts\/sovereign-continuous-authoring-pulse\.mjs/);assert.match(source,/continuousMinuteAuthoringObserved/);});
test('doctor requires receipt evidence instead of inferring signer or courier from service liveness',()=>{assert.match(source,/signer-receipt\.json/);assert.match(source,/courier-receipt\.json/);assert.match(source,/runtime-receipt\.json/);assert.match(source,/signerReceipt,courierReceipt,runtimeReceipt/);assert.doesNotMatch(source,/separateSignerObserved\s*:\s*(?:true|false)/);assert.doesNotMatch(source,/releaseCourierObserved\s*:\s*active/);assert.match(source,/never infers signer or courier proof from service liveness/i);});
test('doctor keeps external release/runtime evidence outside author-writable control state',()=>{assert.match(source,/UBERBOND_SOVEREIGN_EVIDENCE_ROOT/);assert.match(source,/\/var\/lib\/uberbond-evidence/);assert.doesNotMatch(source,/path\.join\(controlDir,'(?:signer|courier|runtime)-receipt\.json'\)/);});
test('doctor exits nonzero until the local self-completion loop is actually ready',()=>{assert.match(source,/selfCompletionLoopReady!==true/);assert.match(source,/process\.exitCode=2/);});
