import test from 'node:test';
import assert from 'node:assert/strict';
import {compileSovereignBootstrapReadiness,REQUIRED_SOURCE_CONTRACTS,REQUIRED_AUTHORING_UNITS,OFFLINE_MODEL_STATUS} from '../src/sovereign-bootstrap-readiness.mjs';
import {SOVEREIGN_RUNTIME_GRADUATION_VERSION,SOVEREIGN_RUNTIME_REHEARSAL_STATUS} from '../src/sovereign-runtime-graduation.mjs';

const all=xs=>Object.fromEntries(xs.map(x=>[x,true]));
const commit='c'.repeat(40),digest='d'.repeat(64),releaseName=`release-${commit.slice(0,12)}-${digest.slice(0,16)}`;
const receipt={status:OFFLINE_MODEL_STATUS,modelId:'qwen-local',observedModelId:'qwen-local',binarySha256:'a'.repeat(64),modelSha256:'b'.repeat(64),endpoint:'http://127.0.0.1:11439'};
const runtimeReceipt={ok:true,schemaVersion:SOVEREIGN_RUNTIME_GRADUATION_VERSION,status:SOVEREIGN_RUNTIME_REHEARSAL_STATUS,rehearsalObserved:true,separateSignerObserved:true,releaseCourierObserved:true,runtimeAppliedObserved:true,reconciliationObserved:true,sourceCommit:commit,releaseName,releaseSequence:'20260910143000'};
const base={sourceCommit:commit,cleanSource:true,sourceContracts:all(REQUIRED_SOURCE_CONTRACTS),authoringConfigPresent:true,configuredSourceRootMatches:true,installedSourceCommit:commit,services:{...all(REQUIRED_AUTHORING_UNITS),localModelRuntime:true,localModelProxy:true},founderConsoleReachable:true,modelReceipt:receipt,isolatedWorkerEnabled:true,founderDialogueEnabled:true,separateSignerObserved:false,releaseCourierObserved:false,runtimeReceipt};

test('fully observed engineering bootstrap stays separate from external reality',()=>{const out=compileSovereignBootstrapReadiness(base);assert.equal(out.ok,true);assert.equal(out.status,'SOVEREIGN_ENGINEERING_BOOTSTRAP_OBSERVED__EXTERNAL_REALITY_REMAINS');assert.equal(out.stages.selfCompletionLoopReady,true);assert.equal(out.stages.separateSignedReleasePathObserved,true);assert.equal(out.stages.ownedRuntimeRehearsalObserved,true);assert.equal(out.authority.businessEffectAuthority,'NONE');});
test('source-complete checkout never becomes host evidence',()=>{const out=compileSovereignBootstrapReadiness({sourceCommit:base.sourceCommit,cleanSource:true,sourceContracts:base.sourceContracts});assert.equal(out.status,'SOVEREIGN_SOURCE_STACK_COMPLETE__HOST_ACTIVATION_REQUIRED');assert.equal(out.stages.authoringHostInstalled,false);assert.ok(out.reasonCodes.includes('sovereign-authoring-host-install-not-observed'));});
test('missing one source contract fails source admission',()=>{const sourceContracts={...base.sourceContracts,releaseCourierInstaller:false};const out=compileSovereignBootstrapReadiness({...base,sourceContracts});assert.equal(out.ok,false);assert.equal(out.status,'SOVEREIGN_BOOTSTRAP_SOURCE_INCOMPLETE');assert.deepEqual(out.missing.sourceContracts,['releaseCourierInstaller']);});
test('runtime graduation observer is a required source contract',()=>{const sourceContracts={...base.sourceContracts,runtimeGraduationObserver:false};const out=compileSovereignBootstrapReadiness({...base,sourceContracts});assert.equal(out.ok,false);assert.deepEqual(out.missing.sourceContracts,['runtimeGraduationObserver']);});
test('host source commit mismatch blocks installed-host claim',()=>{const out=compileSovereignBootstrapReadiness({...base,installedSourceCommit:'d'.repeat(40)});assert.equal(out.stages.authoringHostInstalled,false);assert.equal(out.stages.selfCompletionLoopReady,false);});
test('a same-commit development clone cannot impersonate the configured authoring source root',()=>{const out=compileSovereignBootstrapReadiness({...base,configuredSourceRootMatches:false});assert.equal(out.stages.authoringHostInstalled,false);assert.equal(out.stages.selfCompletionLoopReady,false);assert.ok(out.reasonCodes.includes('configured-authoring-source-root-mismatch'));});
test('inactive verifier blocks the self-completion conveyor',()=>{const out=compileSovereignBootstrapReadiness({...base,services:{...base.services,verifierPath:false}});assert.equal(out.stages.authoringAutomationActive,false);assert.equal(out.stages.selfCompletionLoopReady,false);assert.ok(out.missing.authoringUnits.includes('verifierPath'));});
test('unattested model blocks worker and direct dialogue',()=>{const out=compileSovereignBootstrapReadiness({...base,modelReceipt:{...receipt,observedModelId:'other'}});assert.equal(out.stages.localModelAttested,false);assert.equal(out.stages.isolatedWorkerReady,false);assert.equal(out.stages.directFounderDialogueReady,false);assert.ok(out.reasonCodes.includes('owner-controlled-local-model-not-attested'));});
test('source self-completion never depends on GitHub Vercel or a public cloud model',()=>{const out=compileSovereignBootstrapReadiness(base);assert.equal(out.dependencyBoundary.githubRequiredForSelfCompletion,false);assert.equal(out.dependencyBoundary.vercelRequiredForSelfCompletion,false);assert.equal(out.dependencyBoundary.publicCloudModelRequiredForSelfCompletion,false);assert.equal(out.dependencyBoundary.requiresPhysicalCompute,true);});
test('self-completion can be ready while signer courier runtime proof remain separate',()=>{const out=compileSovereignBootstrapReadiness({...base,runtimeReceipt:null});assert.equal(out.status,'READY_TO_SELF_COMPLETE_LOCALLY__RELEASE_RUNTIME_PROOF_REMAINS');assert.equal(out.stages.selfCompletionLoopReady,true);assert.equal(out.stages.separateSignedReleasePathObserved,false);assert.equal(out.stages.ownedRuntimeRehearsalObserved,false);});
test('stale or structurally weak runtime receipt cannot graduate current source',()=>{for(const bad of [{...runtimeReceipt,sourceCommit:'e'.repeat(40)},{ok:true,rehearsalObserved:true,sourceCommit:commit,separateSignerObserved:true,releaseCourierObserved:true}]){const out=compileSovereignBootstrapReadiness({...base,runtimeReceipt:bad});assert.equal(out.status,'READY_TO_SELF_COMPLETE_LOCALLY__RELEASE_RUNTIME_PROOF_REMAINS');assert.equal(out.stages.ownedRuntimeRehearsalObserved,false);}});
test('explicit pre-runtime signer and courier observations can expose the intermediate stage without fabricating runtime rehearsal',()=>{const out=compileSovereignBootstrapReadiness({...base,runtimeReceipt:null,separateSignerObserved:true,releaseCourierObserved:true});assert.equal(out.status,'SELF_COMPLETION_AND_SIGNED_RELEASE_PATH_READY__RUNTIME_REHEARSAL_REQUIRED');assert.equal(out.stages.ownedRuntimeRehearsalObserved,false);});
