import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compileAgentCodeChangeSet, contentSha256 } from '../src/agent-code-change-contract.mjs';
import { compileSovereignLocalPromotionAdmission, compileSovereignLocalPromotionReceipt, sovereignChangeFingerprint } from '../src/sovereign-local-promotion.mjs';
import { compileSovereignReleaseRequest, verifySovereignReleaseRequest } from '../src/sovereign-release-handoff.mjs';
import { SANDWICH_DESCENDANT_CANON_PATH } from '../src/sandwich-descendant-admission.mjs';

const BASE='a'.repeat(40);const NEXT='b'.repeat(40);const BEFORE='export const value = 1;\n';const AFTER='export const value = 2;\n';
function candidate(){return compileAgentCodeChangeSet({taskId:'task_local_promote_1',baseRevision:BASE,summary:'A bounded independently verified low-risk local source repair.',consequenceClass:'LOCAL_PREPARATION',verification:['node --check src/example.mjs'],changes:[{operation:'UPDATE',path:'src/example.mjs',beforeSha256:contentSha256(BEFORE),content:AFTER,rationale:'Repair a bounded harmless module after independent verification.'}]});}
function verified(cs=candidate(),overrides={}){return{ok:true,status:'VERIFIED_CHANGESET_READY_FOR_SEPARATE_PROMOTION_AUTHORITY',baseRevision:BASE,taskId:cs.taskId,verifiedReceipt:{taskId:cs.taskId,changeSetId:cs.changeSetId,baseRevision:BASE,verifiedFingerprint:sovereignChangeFingerprint(cs),selfMaintenanceReceiptId:`self_maint_${'2'.repeat(24)}`},observedChangeSet:cs,promotion:'NOT_PERFORMED',signingAuthority:'NONE',deploymentAuthority:'NONE',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE',...overrides};}
function admit(v=verified(),overrides={}){return compileSovereignLocalPromotionAdmission({verifiedChange:v,currentHead:BASE,branchName:'main',worktreeClean:true,...overrides});}
function retarget(path){const cs=structuredClone(candidate());cs.changes[0].path=path;return cs;}
function fullPass(a=admit()){return compileSovereignLocalPromotionReceipt({admission:a,promotionCommitSha:NEXT,parentSha:BASE,verification:[{command:'npm run check:syntax',status:'PASS'},{command:'npm run test:deterministic',status:'PASS'}]});}
function sandwichCandidate(overrides={}){
  const entry={name:'Representation Escape Compiler',kind:'SANDWICH_DESCENDANT_REQUIREMENT',foldClass:'INTERNAL_SOURCE',admittedFromBaseRevision:BASE,canonicalGoalRefs:['GENESIS'],dependencies:[],acceptanceEvidence:['SOURCE: bounded representation compiler exists','TEST: hostile duplicate and authority case is refused'],rationale:'Unlock stronger problem-solving.',implementationStatus:'MISSING',terminalEvidenceClass:'IMPLEMENTATION_PLUS_INDEPENDENT_VERIFICATION',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE',implementationForbiddenInAdmission:true,...overrides};
  return compileAgentCodeChangeSet({taskId:`uberbond_sandwich_descendant_${BASE.slice(0,24)}`,baseRevision:BASE,summary:'Admit one descendant requirement only.',consequenceClass:'LOCAL_PREPARATION',verification:['npm run check:syntax','npm run test:deterministic'],changes:[{operation:'UPDATE',path:SANDWICH_DESCENDANT_CANON_PATH,beforeSha256:'1'.repeat(64),content:`${JSON.stringify({terminalConcepts:['GENESIS',entry]},null,2)}\n`,rationale:'One trusted descendant requirement append.'}]});
}

test('independently verified low-risk exact-base change is admitted',()=>{const out=admit();assert.equal(out.ok,true);assert.equal(out.status,'LOCAL_PROMOTION_ADMITTED_FOR_ISOLATED_STAGE_AND_FIXED_GATES');assert.deepEqual(out.fixedPostApplyChecks,['npm run check:syntax','npm run test:deterministic']);assert.equal(out.networkRequired,false);});
test('stale or dirty local main is refused',()=>{assert.ok(admit(verified(),{currentHead:'c'.repeat(40)}).reasonCodes.includes('verified-change-base-must-equal-current-head'));assert.ok(admit(verified(),{worktreeClean:false}).reasonCodes.includes('clean-local-main-required'));});
test('fingerprint substitution is refused',()=>{const v=verified();v.verifiedReceipt.verifiedFingerprint='f'.repeat(64);const out=admit(v);assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('verified-fingerprint-mismatch'));});
test('verified receipt cannot smuggle deployment authority',()=>{const out=admit(verified(candidate(),{deploymentAuthority:'GRANTED'}));assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('verified-change-cannot-carry-deployment-authority'));});
test('hyphenated sovereign control files cannot self-edit',()=>{const cs=retarget('src/sovereign-new-helper.mjs');const out=admit(verified(cs));assert.equal(out.ok,false);assert.ok(out.reasonCodes.some(code=>code==='local-promotion-control-surface-protected:src/sovereign-new-helper.mjs'));});
test('truth and canon surfaces cannot be rewritten by local promoter',()=>{for(const path of ['scripts/terminal-realization.mjs','docs/canon/constitution.md','artifacts/sovereign/terminal-realization.json',SANDWICH_DESCENDANT_CANON_PATH]){const out=admit(verified(retarget(path)));assert.equal(out.ok,false,path);assert.ok(out.reasonCodes.some(code=>code.includes(path)),path);}});
test('exact-base Sandwich task alone may carry one shaped descendant append through promotion admission',()=>{const cs=sandwichCandidate();const out=admit(verified(cs));assert.equal(out.ok,true,JSON.stringify(out.reasonCodes||[]));assert.deepEqual(out.changedPaths,[SANDWICH_DESCENDANT_CANON_PATH]);assert.match(out.truthBoundary,/one-file Sandwich descendant append/i);});
test('Sandwich promotion exception refuses wrong base marker, extra files, or arbitrary source changes',()=>{const wrong=sandwichCandidate({admittedFromBaseRevision:'b'.repeat(40)});assert.equal(admit(verified(wrong)).ok,false);const extra=structuredClone(sandwichCandidate());extra.changes.push({operation:'CREATE',path:'src/side-door.mjs',content:'export default true;\n',rationale:'side door'});const extraVerified=verified(extra);extraVerified.verifiedReceipt.verifiedFingerprint=sovereignChangeFingerprint(extra);assert.equal(admit(extraVerified).ok,false);const arbitrary=structuredClone(sandwichCandidate());arbitrary.changes[0].path='src/side-door.mjs';const arbitraryVerified=verified(arbitrary);arbitraryVerified.verifiedReceipt.verifiedFingerprint=sovereignChangeFingerprint(arbitrary);assert.equal(admit(arbitraryVerified).ok,false);});
test('existing test modification is refused by local promotion layer',()=>{const out=admit(verified(retarget('tests/harmless-regression.test.mjs')));assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('existing-test-modification-refused:tests/harmless-regression.test.mjs'));});
test('promotion receipt requires both fixed gates',()=>{const weak=compileSovereignLocalPromotionReceipt({admission:admit(),promotionCommitSha:NEXT,parentSha:BASE,verification:[{command:'npm run check:syntax',status:'PASS'}]});assert.equal(weak.ok,false);assert.ok(weak.reasonCodes.includes('fixed-post-apply-check-required:npm run test:deterministic'));});
test('verified local main promotion compiles offline release request without PR fiction',()=>{const p=fullPass();assert.equal(p.ok,true);const r=compileSovereignReleaseRequest({promotionReceipt:p});assert.equal(r.ok,true);assert.equal(r.promotionClass,'LOCAL_MAIN_FAST_FORWARD');assert.equal(r.promotionRef,'refs/heads/main');assert.equal(r.prNumber,null);assert.equal(r.sourceCommit,NEXT);assert.equal(r.signingAuthority,'NOT_GRANTED_BY_REQUEST');assert.equal(verifySovereignReleaseRequest(r).ok,true);});
test('local release request tampering is detected',()=>{const r=compileSovereignReleaseRequest({promotionReceipt:fullPass()});r.promotionRef='refs/heads/evil';const v=verifySovereignReleaseRequest(r);assert.equal(v.ok,false);assert.ok(v.reasonCodes.includes('local-main-promotion-ref-required'));assert.ok(v.reasonCodes.includes('release-request-digest-mismatch'));});
test('runtime promoter is zero-network and installer separates identities',()=>{const runtime=readFileSync(new URL('../scripts/sovereign-local-promote.mjs',import.meta.url),'utf8');const service=readFileSync(new URL('../ops/sovereign/uberbond-local-promote.service',import.meta.url),'utf8');const installer=readFileSync(new URL('../ops/sovereign/install-authoring-node.sh',import.meta.url),'utf8');assert.doesNotMatch(runtime,/\bfetch\s*\(|https?:\/\//);assert.match(service,/^PrivateNetwork=true$/m);assert.match(service,/^User=uberbond-promoter$/m);assert.match(installer,/uberbond-promoter/);assert.match(installer,/chown -R uberbond-promoter:uberbond-autonomy/);assert.match(installer,/release signing authority must not live/i);});
test('promotion success wakes truth-first authoring without giving promoter network',()=>{const pathUnit=readFileSync(new URL('../ops/sovereign/uberbond-authoring-after-promotion.path',import.meta.url),'utf8');const promotePath=readFileSync(new URL('../ops/sovereign/uberbond-local-promote.path',import.meta.url),'utf8');assert.match(promotePath,/verified\.json/);assert.match(pathUnit,/promotion-receipt\.json/);assert.match(pathUnit,/Unit=uberbond-authoring\.service/);});
