import test from 'node:test';
import assert from 'node:assert/strict';
import {compileSovereignBootstrapReadiness,REQUIRED_SOURCE_CONTRACTS,REQUIRED_AUTHORING_UNITS,OFFLINE_MODEL_STATUS} from '../src/sovereign-bootstrap-readiness.mjs';

const all=xs=>Object.fromEntries(xs.map(x=>[x,true]));
const sourceCommit='c'.repeat(40);
const requestDigest='d'.repeat(64);
const releaseName=`release-${sourceCommit.slice(0,12)}-${requestDigest.slice(0,16)}`;
const receipt={status:OFFLINE_MODEL_STATUS,modelId:'qwen-local',observedModelId:'qwen-local',binarySha256:'a'.repeat(64),modelSha256:'b'.repeat(64),endpoint:'http://127.0.0.1:11439'};
const signerReceipt={ok:true,status:'SIGNED_RELEASE_READY_IN_OFFLINE_OUTBOX',requestDigest,sourceCommit,releaseName,signingAuthority:'SEPARATE_OFFLINE_SIGNER_ONLY',deploymentAuthority:'NONE',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE'};
const courierReceipt={ok:true,status:'SIGNED_RELEASE_COURIERED_TO_RUNTIME_INBOX',releaseName,signingAuthority:'NONE',deploymentAuthority:'NONE',businessEffectAuthority:'NONE',externalEffectAuthority:'NONE'};
const base={sourceCommit,cleanSource:true,sourceContracts:all(REQUIRED_SOURCE_CONTRACTS),authoringConfigPresent:true,configuredSourceRootMatches:true,installedSourceCommit:sourceCommit,services:{...all(REQUIRED_AUTHORING_UNITS),localModelRuntime:true,localModelProxy:true},founderConsoleReachable:true,modelReceipt:receipt,isolatedWorkerEnabled:true,founderDialogueEnabled:true,signerReceipt,courierReceipt,runtimeReceipt:{ok:true,rehearsalObserved:true,sourceCommit}};

test('fully observed engineering bootstrap stays separate from external reality',()=>{const out=compileSovereignBootstrapReadiness(base);assert.equal(out.ok,true);assert.equal(out.status,'SOVEREIGN_ENGINEERING_BOOTSTRAP_OBSERVED__EXTERNAL_REALITY_REMAINS');assert.equal(out.stages.selfCompletionLoopReady,true);assert.equal(out.stages.separateReleaseSignerObserved,true);assert.equal(out.stages.signedReleaseCourierObserved,true);assert.equal(out.stages.ownedRuntimeRehearsalObserved,true);assert.equal(out.authority.businessEffectAuthority,'NONE');});
test('source-complete checkout never becomes host evidence',()=>{const out=compileSovereignBootstrapReadiness({sourceCommit:base.sourceCommit,cleanSource:true,sourceContracts:base.sourceContracts});assert.equal(out.status,'SOVEREIGN_SOURCE_STACK_COMPLETE__HOST_ACTIVATION_REQUIRED');assert.equal(out.stages.authoringHostInstalled,false);assert.ok(out.reasonCodes.includes('sovereign-authoring-host-install-not-observed'));});
test('missing one source contract fails source admission',()=>{const sourceContracts={...base.sourceContracts,releaseCourierInstaller:false};const out=compileSovereignBootstrapReadiness({...base,sourceContracts});assert.equal(out.ok,false);assert.equal(out.status,'SOVEREIGN_BOOTSTRAP_SOURCE_INCOMPLETE');assert.deepEqual(out.missing.sourceContracts,['releaseCourierInstaller']);});
test('host source commit mismatch blocks installed-host claim',()=>{const out=compileSovereignBootstrapReadiness({...base,installedSourceCommit:'d'.repeat(40)});assert.equal(out.stages.authoringHostInstalled,false);assert.equal(out.stages.selfCompletionLoopReady,false);});
test('a same-commit development clone cannot impersonate the configured authoring source root',()=>{const out=compileSovereignBootstrapReadiness({...base,configuredSourceRootMatches:false});assert.equal(out.stages.authoringHostInstalled,false);assert.equal(out.stages.selfCompletionLoopReady,false);assert.ok(out.reasonCodes.includes('configured-authoring-source-root-mismatch'));});
test('inactive verifier blocks the self-completion conveyor',()=>{const out=compileSovereignBootstrapReadiness({...base,services:{...base.services,verifierPath:false}});assert.equal(out.stages.authoringAutomationActive,false);assert.equal(out.stages.selfCompletionLoopReady,false);assert.ok(out.missing.authoringUnits.includes('verifierPath'));});
test('unattested model blocks worker and direct dialogue',()=>{const out=compileSovereignBootstrapReadiness({...base,modelReceipt:{...receipt,observedModelId:'other'}});assert.equal(out.stages.localModelAttested,false);assert.equal(out.stages.isolatedWorkerReady,false);assert.equal(out.stages.directFounderDialogueReady,false);assert.ok(out.reasonCodes.includes('owner-controlled-local-model-not-attested'));});
test('source self-completion never depends on GitHub Vercel or a public cloud model',()=>{const out=compileSovereignBootstrapReadiness(base);assert.equal(out.dependencyBoundary.githubRequiredForSelfCompletion,false);assert.equal(out.dependencyBoundary.vercelRequiredForSelfCompletion,false);assert.equal(out.dependencyBoundary.publicCloudModelRequiredForSelfCompletion,false);assert.equal(out.dependencyBoundary.requiresPhysicalCompute,true);});
test('self-completion can be ready while signer courier runtime proof remain separate',()=>{const out=compileSovereignBootstrapReadiness({...base,signerReceipt:null,courierReceipt:null,runtimeReceipt:null});assert.equal(out.status,'READY_TO_SELF_COMPLETE_LOCALLY__RELEASE_RUNTIME_PROOF_REMAINS');assert.equal(out.stages.selfCompletionLoopReady,true);assert.equal(out.stages.separateSignedReleasePathObserved,false);assert.equal(out.stages.ownedRuntimeRehearsalObserved,false);});
test('naked observation booleans cannot forge the separate signed release path',()=>{const out=compileSovereignBootstrapReadiness({...base,signerReceipt:null,courierReceipt:null,separateSignerObserved:true,releaseCourierObserved:true,runtimeReceipt:null});assert.equal(out.stages.separateReleaseSignerObserved,false);assert.equal(out.stages.signedReleaseCourierObserved,false);assert.equal(out.status,'READY_TO_SELF_COMPLETE_LOCALLY__RELEASE_RUNTIME_PROOF_REMAINS');});
test('stale signer source cannot authorize current release readiness',()=>{const out=compileSovereignBootstrapReadiness({...base,signerReceipt:{...signerReceipt,sourceCommit:'e'.repeat(40)}});assert.equal(out.stages.separateReleaseSignerObserved,false);assert.ok(out.reasonCodes.includes('separate-release-signer-not-observed'));});
test('signer receipt cannot claim deployment authority',()=>{const out=compileSovereignBootstrapReadiness({...base,signerReceipt:{...signerReceipt,deploymentAuthority:'SIGNED_RELEASE_DEPLOY'}});assert.equal(out.stages.separateReleaseSignerObserved,false);});
test('courier receipt must bind to the exact signed release name',()=>{const out=compileSovereignBootstrapReadiness({...base,courierReceipt:{...courierReceipt,releaseName:`release-${'e'.repeat(12)}-${requestDigest.slice(0,16)}`},runtimeReceipt:null});assert.equal(out.stages.separateReleaseSignerObserved,true);assert.equal(out.stages.signedReleaseCourierObserved,false);assert.equal(out.status,'READY_TO_SELF_COMPLETE_LOCALLY__RELEASE_RUNTIME_PROOF_REMAINS');});
