import test from 'node:test';
import assert from 'node:assert/strict';
import { buildSubstrateMigrationPlan, buildSubstrateTournament, definePhysicalFunction, evaluateSubstrateCandidate } from '../src/substrate-liberation.mjs';

const fn=definePhysicalFunction({id:'private-inference',transformation:'run private low-latency inference',inputs:['model state','context'],outputs:['response'],maxLatencyMs:100,maxEnergyJoules:10,minReliability:0.95,portabilityRequired:true,environmentConstraints:['founder-controlled']});
const silicon={id:'silicon',name:'Current digital silicon node',substrateClass:'DIGITAL_SILICON',evidenceState:'OBSERVED_IN_UBERBOND',evidenceRefs:['receipt://local'],estimatedLatencyMs:50,estimatedEnergyJoules:5,estimatedReliability:0.99,portability:0.8,compatibility:1,maturity:1,reversibility:0.9};
const photonic={id:'photonics',name:'Candidate photonic path',substrateClass:'PHOTONIC',evidenceState:'LAB_DEMONSTRATED',evidenceRefs:['paper://x'],estimatedLatencyMs:30,estimatedEnergyJoules:2,estimatedReliability:0.96,portability:0.6,compatibility:0.4,maturity:0.3,reversibility:0.6};

test('physical function is defined before hardware and carries no authority',()=>{assert.equal(fn.ok,true);assert.match(fn.law,/BEFORE_CHOOSING_THE_HARDWARE/);assert.equal(fn.externalEffectAuthority,'NONE')});
test('candidate with non-hypothesis evidence state must cite evidence',()=>{const out=evaluateSubstrateCandidate({physicalFunction:fn,candidate:{...photonic,evidenceRefs:[]}});assert.equal(out.ok,false);assert.ok(out.reasonCodes.includes('non-hypothesis-candidate-requires-evidence'))});
test('candidate evaluation separates estimated fit from physical proof',()=>{const out=evaluateSubstrateCandidate({physicalFunction:fn,candidate:silicon});assert.equal(out.ok,true);assert.equal(out.hardFit,true);assert.match(out.claimBoundary,/NOT_PHYSICAL_PROOF/)});
test('tournament compares heterogeneous substrate classes instead of assuming silicon',()=>{const out=buildSubstrateTournament({physicalFunction:fn,candidates:[silicon,photonic]});assert.equal(out.ok,true);assert.equal(out.representedClasses.length,2);assert.equal(out.diversityWarning,null);assert.match(out.selectionBoundary,/NOT_PERMISSION_TO_BUILD_BUY_DEPLOY_OR_PHYSICALLY_TEST/)});
test('single-paradigm tournament exposes substrate monoculture',()=>{const out=buildSubstrateTournament({physicalFunction:fn,candidates:[silicon]});assert.match(out.diversityWarning,/SUBSTRATE_MONOCULTURE/)});
test('migration requires reversible checkpoints and preserves identity law',()=>{const a=evaluateSubstrateCandidate({physicalFunction:fn,candidate:silicon});const b=evaluateSubstrateCandidate({physicalFunction:fn,candidate:photonic});assert.equal(buildSubstrateMigrationPlan({currentCandidate:a,targetCandidate:b,checkpoints:[]}).ok,false);const out=buildSubstrateMigrationPlan({currentCandidate:a,targetCandidate:b,checkpoints:['shadow workload','state digest comparison','rollback rehearsal']});assert.equal(out.ok,true);assert.equal(out.rollbackRequired,true);assert.match(out.identityLaw,/FOUNDER_RELATION_MUST_SURVIVE/)});
