import test from 'node:test';import assert from 'node:assert/strict';import { UBER_SOVEREIGN_LAYERS, compileUberSovereignStack } from '../src/uber-sovereign-stack.mjs';const evidenceFor=layer=>({sourceVerified:true,testsPassed:true,controlOwned:true,providerReplaceable:true,stateExportable:layer.stateful?true:false,authorityRoot:'UBERBOND',runtimeObserved:layer.runtimeProof?true:false,evidenceRefs:[`test:${layer.id}`]});
// The named list is the specification; the count is derived from it.
//
// This asserted a bare 28 alongside a list of 28 ids. UBEROCEAN was added to the
// registry and not to the list, so the count check failed while the list check
// still passed -- the test could say "wrong number of layers" but not which one,
// and the same omission had already broken the orchestration graph. Deriving the
// count from the list means adding a layer without naming it here fails with the
// name, and naming one that does not exist fails too.
const EXPECTED_LAYER_IDS=['UBERMESH','UBERCLOUD','UBEROCEAN','UBERCEL','UBERSOURCE','UBERFORGE','UBERSTATE','UBERQUEUE','UBEROBSERVE','UBERBROWSER','UBERIDENTITY','UBERSKILLS','UBERGRAPH','UBERMIND','UBERDNA','UBERMEMORY','UBERVAULT','UBERRUNTIME','UBERCONTROL','UBERAGENTS','UBERMODELS','UBERRESEARCH','UBERGENESIS','UBERORCHESTRATION','UBERECONOMY','UBERPAY','UBERMAIL','UBERDELIVERY','UBERDISTRIBUTION'];

test('Uber sovereign registry contains the complete first-party stack without duplicate identities',()=>{
  const ids=UBER_SOVEREIGN_LAYERS.map(x=>x.id);
  assert.equal(new Set(ids).size,ids.length,'duplicate layer id');
  assert.deepEqual([...ids].sort(),[...EXPECTED_LAYER_IDS].sort(),'registry and expected layer list disagree');
});test('source evidence cannot impersonate live sovereign runtime',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,{...evidenceFor(l),runtimeObserved:false}]));const r=compileUberSovereignStack({layerEvidence});assert.equal(r.ok,true);assert.notEqual(r.status,'UBER_SOVEREIGN_STACK_RUNTIME_READY');assert.ok(r.runtimeBlockers.length>0);});test('Uber sovereign stack refuses any provider as the authority root',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,evidenceFor(l)]));layerEvidence.UBERSOURCE.authorityRoot='GITHUB';const r=compileUberSovereignStack({layerEvidence});assert.ok(r.independenceBlockers.includes('UBERSOURCE'));});test('stateful Uber layers cannot claim independence without exportability',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,evidenceFor(l)]));layerEvidence.UBERSTATE.stateExportable=false;assert.ok(compileUberSovereignStack({layerEvidence}).independenceBlockers.includes('UBERSTATE'));});test('every layer reaches runtime ready only with complete evidence',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,evidenceFor(l)]));const r=compileUberSovereignStack({layerEvidence});assert.equal(r.status,'UBER_SOVEREIGN_STACK_RUNTIME_READY');assert.deepEqual(r.runtimeBlockers,[]);});