import test from 'node:test';
import assert from 'node:assert/strict';
import { UBER_SUBSTRATE_LAYERS, compileUberSourcePlan, compileUberForgePlan, compileUberStatePlan, compileUberQueuePlan, compileUberObservePlan, compileUberBrowserPlan, compileUberIdentityPlan } from '../src/uber-sovereign-substrate.mjs';
const D='sha256:'+'a'.repeat(64);

test('UberSource requires two distinct custody providers and rejects GitHub as authority root',()=>{const base={immutableRevisionRef:'sha:abc',sourceExportRef:'export:1',restoreDrillRef:'restore:1',custodyCells:[{cellId:'a',provider:'git-a',evidenceRef:'e:a',readable:true},{cellId:'b',provider:'git-b',evidenceRef:'e:b',readable:true}]};assert.equal(compileUberSourcePlan(base).ok,true);assert.equal(compileUberSourcePlan({...base,githubAuthorityRoot:true}).ok,false);assert.equal(compileUberSourcePlan({...base,custodyCells:[base.custodyCells[0]]}).ok,false);});
test('UberForge refuses secret-bearing builds and self-promotion',()=>{const base={sourceRevision:'sha:abc',recipeDigest:D,runnerIsolationRef:'iso:1',artifactDigest:D,signerRef:'signer:1'};assert.equal(compileUberForgePlan(base).ok,true);assert.equal(compileUberForgePlan({...base,secretsMounted:true}).ok,false);assert.equal(compileUberForgePlan({...base,selfPromote:true}).ok,false);});
test('UberState requires portable export and restore evidence without raw encryption keys',()=>{const base={schemaVersion:'v1',exportFormat:'SQL',snapshotDigest:D,encryptionKeyRef:'keyref:1',restoreDrillRef:'restore:1',provider:'cell-a',portable:true};assert.equal(compileUberStatePlan(base).ok,true);assert.equal(compileUberStatePlan({...base,portable:false}).ok,false);assert.equal(compileUberStatePlan({...base,rawEncryptionKey:'secret'}).ok,false);});
test('UberQueue requires idempotency bounded leases retries and cannot invent effect authority',()=>{const base={missionId:'m1',idempotencyKey:'k1',leaseOwner:'worker1',leaseTtlSeconds:60,maxAttempts:5,deadLetterRef:'dlq:1',durableStateRef:'state:1'};assert.equal(compileUberQueuePlan(base).ok,true);assert.equal(compileUberQueuePlan({...base,leaseTtlSeconds:99999}).ok,false);assert.equal(compileUberQueuePlan({...base,effectAuthority:true}).ok,false);});
test('UberObserve refuses secrets raw founder-private telemetry and provider truth authority',()=>{const base={sourceRef:'runtime:1',eventType:'health',observedAt:'2026-09-11T12:00:00Z',evidenceRef:'e:1',redactionPolicyRef:'redact:1',payloadDigest:D,retentionDays:30};assert.equal(compileUberObservePlan(base).ok,true);assert.equal(compileUberObservePlan({...base,containsSecret:true}).ok,false);assert.equal(compileUberObservePlan({...base,truthAuthority:'PROVIDER'}).ok,false);});
test('UberBrowser is read-only by default and mutating sessions require explicit effect authority',()=>{const base={targetUrl:'https://example.com/x',allowedTargetRef:'allow:1',sessionIsolationRef:'session:1',evidenceRef:'browser:1',dataClass:'PUBLIC'};assert.equal(compileUberBrowserPlan(base).ok,true);assert.equal(compileUberBrowserPlan({...base,externalEffect:true}).ok,false);assert.equal(compileUberBrowserPlan({...base,mode:'MUTATING'}).ok,false);assert.equal(compileUberBrowserPlan({...base,mode:'MUTATING',effectAuthorityRef:'authority:1'}).ok,true);});
test('UberIdentity keeps raw credentials out and makes UberBond the authority root',()=>{const base={subjectId:'workload:1',identityClass:'WORKLOAD',credentialRef:'vault:credential:1',revocationRef:'revoke:1',expiresAt:'2099-01-01T00:00:00Z',issuer:'uberidentity',authorityRoot:'UBERBOND'};assert.equal(compileUberIdentityPlan(base).ok,true);assert.equal(compileUberIdentityPlan({...base,rawSecret:'x'}).ok,false);assert.equal(compileUberIdentityPlan({...base,authorityRoot:'GOOGLE'}).ok,false);});
test('Uber sovereign substrate has all eight unique first-party layers including UberSkills',()=>{const ids=UBER_SUBSTRATE_LAYERS.map(x=>x.id);assert.equal(ids.length,8);assert.equal(new Set(ids).size,8);for(const id of ['UBERSOURCE','UBERFORGE','UBERSTATE','UBERQUEUE','UBEROBSERVE','UBERBROWSER','UBERIDENTITY','UBERSKILLS'])assert.ok(ids.includes(id));});
