import test from 'node:test';
import assert from 'node:assert/strict';
import { UBER_SOVEREIGN_LAYERS, compileUberSovereignStack } from '../src/uber-sovereign-stack.mjs';

const evidenceFor=layer=>({sourceVerified:true,testsPassed:true,controlOwned:true,providerReplaceable:true,stateExportable:layer.stateful?true:false,authorityRoot:'UBERBOND',runtimeObserved:layer.runtimeProof?true:false,evidenceRefs:[`test:${layer.id}`]});

test('Uber sovereign registry contains complete 25-layer first-party stack without duplicate identities',()=>{const ids=UBER_SOVEREIGN_LAYERS.map(x=>x.id);assert.equal(ids.length,25);assert.equal(new Set(ids).size,25);for(const id of ['UBERMESH','UBERCLOUD','UBERCEL','UBERSOURCE','UBERFORGE','UBERSTATE','UBERQUEUE','UBEROBSERVE','UBERBROWSER','UBERIDENTITY','UBERSKILLS','UBERGRAPH','UBERMIND','UBERDNA','UBERMEMORY','UBERVAULT','UBERRUNTIME','UBERCONTROL','UBERAGENTS','UBERMODELS','UBERRESEARCH','UBERECONOMY','UBERPAY','UBERMAIL','UBERDELIVERY'])assert.ok(ids.includes(id),`${id} missing`);});
test('source evidence cannot impersonate live sovereign runtime',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,{...evidenceFor(l),runtimeObserved:false}]));const r=compileUberSovereignStack({layerEvidence});assert.equal(r.ok,true);assert.notEqual(r.status,'UBER_SOVEREIGN_STACK_RUNTIME_READY');assert.ok(r.runtimeBlockers.length>0);});
test('Uber sovereign stack refuses any provider as the authority root',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,evidenceFor(l)]));layerEvidence.UBERSOURCE.authorityRoot='GITHUB';const r=compileUberSovereignStack({layerEvidence});assert.equal(r.independenceBlockers.includes('UBERSOURCE'),true);assert.equal(r.status,'UBER_SOVEREIGN_STACK_SOURCE_READY');});
test('stateful Uber layers cannot claim independence without exportability',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,evidenceFor(l)]));layerEvidence.UBERSTATE.stateExportable=false;const r=compileUberSovereignStack({layerEvidence});assert.ok(r.independenceBlockers.includes('UBERSTATE'));});
test('all 25 layers can reach source independence and runtime ready only with complete evidence',()=>{const layerEvidence=Object.fromEntries(UBER_SOVEREIGN_LAYERS.map(l=>[l.id,evidenceFor(l)]));const r=compileUberSovereignStack({layerEvidence});assert.equal(r.ok,true);assert.equal(r.status,'UBER_SOVEREIGN_STACK_RUNTIME_READY');assert.deepEqual(r.sourceBlockers,[]);assert.deepEqual(r.independenceBlockers,[]);assert.deepEqual(r.runtimeBlockers,[]);});
