import { createHash } from 'node:crypto';

export const GAMECHANGER_MESH_VERSION = 'uberbond.gamechanger-mesh-1.0.0';
export const GAMECHANGER_DOMAINS = Object.freeze(['AI_MODELS','AGENT_RUNTIME','OPEN_SOURCE','PROTOCOLS','AUTOMATION','DEVTOOLS','INFRASTRUCTURE','DATA','DISTRIBUTION','PAYMENTS','PRICING_FREE_TIERS','POLICY_REGULATION','SECURITY','RESEARCH','VERTICAL_MARKETS','BUSINESS_MODELS']);
export const GAMECHANGER_SOURCE_TIERS = Object.freeze({ PRIMARY_OFFICIAL:100, PRIMARY_RESEARCH:95, OPEN_SOURCE_ORIGINAL:90, REPUTABLE_SECONDARY:75, COMMUNITY_SIGNAL:55, UNSOURCED_CLAIM:10 });
export const GAMECHANGER_ATTENTION_STATES = Object.freeze(['IGNORE','WATCH','RESEARCH','ATOMIZE','EXPERIMENT_CANDIDATE']);

const TRACKING_PARAMS = new Set(['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','fbclid','mc_cid','mc_eid','ref','ref_src']);
function text(value,max=6000){const out=String(value??'').trim();return out&&out.length<=max?out:null;}
function finite(value,min=0,max=100){const n=Number(value);return Number.isFinite(n)&&n>=min&&n<=max?n:null;}
function iso(value){const raw=text(value,100);const d=raw?new Date(raw):null;return d&&Number.isFinite(d.getTime())?d.toISOString():null;}
function list(value,max=128,itemMax=2000){if(!Array.isArray(value)||value.length>max)return null;const out=[],seen=new Set();for(const item of value){const v=text(item,itemMax);if(!v)return null;if(!seen.has(v)){seen.add(v);out.push(v);}}return out;}
function envelope(extra={}){return {businessEffectAuthority:'NONE',externalEffectAuthority:'PUBLIC_READ_ONLY',commercialTruthAuthority:'NONE',...extra};}

export function canonicalizePublicUrl(value){const raw=text(value,3000);if(!raw)return null;try{const url=new URL(raw);if(url.protocol!=='https:')return null;url.hash='';for(const key of [...url.searchParams.keys()])if(TRACKING_PARAMS.has(key.toLowerCase()))url.searchParams.delete(key);if(url.pathname!=='/'&&url.pathname.endsWith('/'))url.pathname=url.pathname.slice(0,-1);return url.toString();}catch{return null;}}
function canonicalWords(value){return String(value??'').toLowerCase().replace(/https?:\/\/\S+/g,' ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}

export function normalizeGamechangerObservation(input={}){
  const id=text(input.id,300)?.toLowerCase(),sourceId=text(input.sourceId,300)?.toLowerCase(),sourceTier=text(input.sourceTier,80)?.toUpperCase(),sourceType=text(input.sourceType,80)?.toUpperCase(),url=canonicalizePublicUrl(input.url),title=text(input.title,1000),summary=text(input.summary,6000),observedAt=iso(input.observedAt),publishedAt=input.publishedAt==null?null:iso(input.publishedAt),domains=list(input.domains||[],GAMECHANGER_DOMAINS.length,120)?.map(x=>x.toUpperCase()),evidenceRefs=list(input.evidenceRefs||[],128,3000),claims=list(input.claims||[],128,2500),reasonCodes=[];
  if(!id)reasonCodes.push('observation-id-required');if(!sourceId)reasonCodes.push('source-id-required');if(!sourceTier||!(sourceTier in GAMECHANGER_SOURCE_TIERS))reasonCodes.push('recognized-source-tier-required');if(!sourceType)reasonCodes.push('source-type-required');if(!url)reasonCodes.push('public-https-url-required');if(!title)reasonCodes.push('title-required');if(!summary)reasonCodes.push('summary-required');if(!observedAt)reasonCodes.push('observed-at-required');if(input.publishedAt!=null&&!publishedAt)reasonCodes.push('valid-published-at-required');if(!domains||domains.length===0||domains.some(d=>!GAMECHANGER_DOMAINS.includes(d)))reasonCodes.push('recognized-domain-required');if(!evidenceRefs||evidenceRefs.length===0)reasonCodes.push('evidence-required');if(!claims)reasonCodes.push('claims-invalid');
  if(reasonCodes.length)return envelope({ok:false,status:'GAMECHANGER_OBSERVATION_INVALID',reasonCodes});
  return envelope({ok:true,status:'GAMECHANGER_OBSERVATION_NORMALIZED',observation:{id,sourceId,sourceTier,sourceType,url,title,summary,observedAt,publishedAt,domains,evidenceRefs,claims}});
}

export function fingerprintGamechangerObservation(input={}){const normalized=normalizeGamechangerObservation(input);if(!normalized.ok)return normalized;const o=normalized.observation;const material=[canonicalWords(o.title),canonicalWords(o.url),canonicalWords(o.claims.join(' | ')||o.summary)].join('\n');return envelope({ok:true,status:'GAMECHANGER_FINGERPRINTED',fingerprint:createHash('sha256').update(material).digest('hex'),observation:o});}

export function dedupeGamechangerObservations(observations=[]){
  if(!Array.isArray(observations)||observations.length>50000)return envelope({ok:false,status:'GAMECHANGER_DEDUPE_INVALID',reasonCodes:['bounded-observation-list-required']});
  const byFingerprint=new Map(),invalid=[];
  for(const raw of observations){const fp=fingerprintGamechangerObservation(raw);if(!fp.ok){invalid.push({inputId:raw?.id??null,reasonCodes:fp.reasonCodes});continue;}const current=byFingerprint.get(fp.fingerprint);if(!current){byFingerprint.set(fp.fingerprint,{fingerprint:fp.fingerprint,observation:fp.observation,corroboratingSourceIds:[fp.observation.sourceId],evidenceRefs:[...fp.observation.evidenceRefs],domains:[...fp.observation.domains],sourceTiers:[fp.observation.sourceTier]});continue;}current.corroboratingSourceIds=[...new Set([...current.corroboratingSourceIds,fp.observation.sourceId])];current.evidenceRefs=[...new Set([...current.evidenceRefs,...fp.observation.evidenceRefs])];current.domains=[...new Set([...current.domains,...fp.observation.domains])];current.sourceTiers=[...new Set([...current.sourceTiers,fp.observation.sourceTier])];if(new Date(fp.observation.observedAt).getTime()>new Date(current.observation.observedAt).getTime())current.observation={...fp.observation,evidenceRefs:current.evidenceRefs,domains:current.domains};}
  return envelope({ok:true,status:'GAMECHANGER_DEDUPED',observations:[...byFingerprint.values()],invalid,inputCount:observations.length,uniqueCount:byFingerprint.size});
}

function sourceTrustScore(sourceTiers=[]){if(!sourceTiers.length)return 0;const weights=sourceTiers.map(t=>GAMECHANGER_SOURCE_TIERS[t]??0).sort((a,b)=>b-a);return Math.min(100,(weights[0]??0)+Math.min(10,Math.max(0,weights.length-1)*3));}
export function scoreGamechangerCandidate(input={}){
  const positives=[['novelty',.12],['enablingPower',.15],['economicUpside',.17],['founderMinutesSaved',.12],['distributionLeverage',.10],['costCurveShift',.08],['crossIndustryTransfer',.07],['evidenceQuality',.09],['implementationEase',.05],['timeSensitivity',.05]],penalties=[['risk',.08],['uncertainty',.07],['maintenanceBurden',.04],['regulatoryFriction',.05],['commoditizationRisk',.04]],values={};
  for(const [key] of [...positives,...penalties]){const v=finite(input[key]);if(v==null)return {ok:false,reasonCodes:[`bounded-${key}-required`]};values[key]=v;}
  const sourceTrust=finite(input.sourceTrust??50),corroboratingSources=Number(input.corroboratingSources??1);if(sourceTrust==null||!Number.isSafeInteger(corroboratingSources)||corroboratingSources<1||corroboratingSources>10000)return {ok:false,reasonCodes:['valid-source-trust-and-corroboration-required']};
  const upside=positives.reduce((s,[k,w])=>s+values[k]*w,0),penalty=penalties.reduce((s,[k,w])=>s+values[k]*w,0),trustAdjustment=(sourceTrust-50)*.08,corroborationBonus=Math.min(8,Math.log2(corroboratingSources)*2.5),score=Math.max(0,Math.min(100,Number((upside-penalty+trustAdjustment+corroborationBonus).toFixed(2))));
  return {ok:true,score,components:{upside:Number(upside.toFixed(2)),penalty:Number(penalty.toFixed(2)),trustAdjustment:Number(trustAdjustment.toFixed(2)),corroborationBonus:Number(corroborationBonus.toFixed(2))}};
}
export function classifyGamechangerAttention(score,{evidenceQuality=0,sourceTrust=0}={}){const s=finite(score),e=finite(evidenceQuality),t=finite(sourceTrust);if(s==null||e==null||t==null)return 'IGNORE';if(s>=80&&e>=70&&t>=70)return 'EXPERIMENT_CANDIDATE';if(s>=68&&e>=55)return 'ATOMIZE';if(s>=55)return 'RESEARCH';if(s>=40)return 'WATCH';return 'IGNORE';}

export function buildCoverageReceipt({sources=[],requiredDomains=GAMECHANGER_DOMAINS,minIndependentSourcesPerDomain=2}={}){if(!Array.isArray(sources)||sources.length>10000||!Array.isArray(requiredDomains))return envelope({ok:false,status:'GAMECHANGER_COVERAGE_INVALID',reasonCodes:['bounded-sources-and-domains-required']});const min=Number(minIndependentSourcesPerDomain);if(!Number.isSafeInteger(min)||min<1||min>20)return envelope({ok:false,status:'GAMECHANGER_COVERAGE_INVALID',reasonCodes:['valid-minimum-source-count-required']});const counts=Object.fromEntries(requiredDomains.map(d=>[d,new Set()]));for(const source of sources){const sid=text(source?.id,300)?.toLowerCase(),domains=Array.isArray(source?.domains)?source.domains.map(d=>String(d).toUpperCase()):[];if(!sid)continue;for(const domain of domains)if(counts[domain])counts[domain].add(sid);}const byDomain=Object.fromEntries(Object.entries(counts).map(([d,set])=>[d,set.size])),gaps=requiredDomains.filter(d=>(byDomain[d]??0)<min),coverageRatio=requiredDomains.length?Number(((requiredDomains.length-gaps.length)/requiredDomains.length).toFixed(4)):1;return envelope({ok:true,status:gaps.length?'GAMECHANGER_COVERAGE_GAPS':'GAMECHANGER_COVERAGE_COMPLETE',byDomain,gaps,coverageRatio,minimumIndependentSourcesPerDomain:min});}

export function buildSourceFetchPlan({sources=[],now=new Date().toISOString()}={}){
  const observedNow=iso(now);if(!observedNow||!Array.isArray(sources)||sources.length>10000)return envelope({ok:false,status:'GAMECHANGER_SOURCE_PLAN_INVALID',reasonCodes:['valid-now-and-bounded-sources-required']});const directReads=[],searchLanes=[],invalid=[];
  for(const source of sources){const id=text(source?.id,300)?.toLowerCase(),mode=text(source?.mode,40)?.toUpperCase(),cadenceMinutes=Number(source?.cadenceMinutes??60),lastCheckedAt=source?.lastCheckedAt==null?null:iso(source.lastCheckedAt),domains=Array.isArray(source?.domains)?[...new Set(source.domains.map(d=>String(d).toUpperCase()).filter(d=>GAMECHANGER_DOMAINS.includes(d)))]:[];if(!id||!['DIRECT_PUBLIC_READ','SEARCH_LANE'].includes(mode)||!Number.isSafeInteger(cadenceMinutes)||cadenceMinutes<15||cadenceMinutes>43200||domains.length===0){invalid.push({id:source?.id??null,reason:'invalid-source-contract'});continue;}const due=!lastCheckedAt||(new Date(observedNow).getTime()-new Date(lastCheckedAt).getTime())>=cadenceMinutes*60000;if(!due)continue;if(mode==='DIRECT_PUBLIC_READ'){const url=canonicalizePublicUrl(source?.url);if(!url){invalid.push({id,reason:'direct-source-requires-public-https-url'});continue;}directReads.push({id,url,parser:text(source?.parser,40)?.toUpperCase()||'AUTO',cadenceMinutes,domains,sourceTier:text(source?.sourceTier,80)?.toUpperCase()||'REPUTABLE_SECONDARY'});}else{const query=text(source?.query,2000);if(!query){invalid.push({id,reason:'search-lane-query-required'});continue;}searchLanes.push({id,query,cadenceMinutes,domains,sourceTier:text(source?.sourceTier,80)?.toUpperCase()||'REPUTABLE_SECONDARY'});}}
  return envelope({ok:invalid.length===0,status:invalid.length?'GAMECHANGER_SOURCE_PLAN_PARTIAL':'GAMECHANGER_SOURCE_PLAN_READY',observedAt:observedNow,directReads,searchLanes,invalid,directReadAuthority:'PUBLIC_READ_ONLY',searchLaneAuthority:'RESEARCH_ONLY',prohibited:['LOGIN_BYPASS','CAPTCHA_BYPASS','PRIVATE_SESSION_ACCESS','PAID_ACCESS_BYPASS','MESSAGE','PURCHASE','DEPLOYMENT']});
}

function heuristicScores(item){const blob=`${item.observation.title} ${item.observation.summary} ${item.observation.claims.join(' ')}`.toLowerCase(),has=(...w)=>w.some(x=>blob.includes(x)),evidenceQuality=Math.min(100,45+sourceTrustScore(item.sourceTiers)*.45+Math.min(15,item.corroboratingSourceIds.length*4));return {novelty:has('new','launch','released','introducing','first','breakthrough')?78:52,enablingPower:has('agent','api','protocol','model','runtime','automation','tool','workflow')?82:55,economicUpside:has('free','pricing','cost','revenue','payment','sales','distribution','credit')?80:58,founderMinutesSaved:has('automate','autonomous','agent','workflow','scheduler','integration')?82:55,distributionLeverage:has('distribution','email','crm','marketing','search','social','outreach')?80:48,costCurveShift:has('free','open source','open-source','price','pricing','cheaper','credits')?85:45,crossIndustryTransfer:has('protocol','platform','api','framework','database','agent')?78:55,evidenceQuality:Math.round(evidenceQuality),implementationEase:has('api','sdk','open source','open-source','mcp','a2a')?72:52,timeSensitivity:has('today','launch','released','new','breaking','change','deprecat')?78:48,risk:has('exploit','bypass','hack','unofficial','leak')?88:30,uncertainty:item.corroboratingSourceIds.length>1?28:48,maintenanceBurden:has('self-host','self host','scrape')?62:38,regulatoryFriction:has('payment','health','medical','financial','privacy','gdpr','regulation')?62:30,commoditizationRisk:has('template','wrapper','generic')?72:38};}

export function buildGamechangerTournament({observations=[],knownFingerprints=[],maxEscalations=25}={}){const known=new Set(Array.isArray(knownFingerprints)?knownFingerprints.map(String):[]),cap=Number(maxEscalations);if(!Number.isSafeInteger(cap)||cap<1||cap>500)return envelope({ok:false,status:'GAMECHANGER_TOURNAMENT_INVALID',reasonCodes:['bounded-escalation-cap-required']});const deduped=dedupeGamechangerObservations(observations);if(!deduped.ok)return deduped;const ranked=[];for(const item of deduped.observations){if(known.has(item.fingerprint))continue;const dimensions=heuristicScores(item),sourceTrust=sourceTrustScore(item.sourceTiers),result=scoreGamechangerCandidate({...dimensions,sourceTrust,corroboratingSources:item.corroboratingSourceIds.length});if(!result.ok)continue;const attentionState=classifyGamechangerAttention(result.score,{evidenceQuality:dimensions.evidenceQuality,sourceTrust});ranked.push({...item,score:result.score,scoreComponents:result.components,dimensions,sourceTrust,attentionState,nextAction:attentionState==='EXPERIMENT_CANDIDATE'?'INDEPENDENT_RESEARCH_THEN_BOUNDED_EXPERIMENT_PROPOSAL':attentionState==='ATOMIZE'?'ATOMIZE_INTO_CAPABILITY_AND_ECONOMIC_MECHANISMS':attentionState==='RESEARCH'?'SKEPTICAL_MULTI_SOURCE_RESEARCH':attentionState==='WATCH'?'RECHECK_ON_NEXT_CADENCE':'ARCHIVE_WITH_FINGERPRINT'});}ranked.sort((a,b)=>b.score-a.score||b.sourceTrust-a.sourceTrust||a.fingerprint.localeCompare(b.fingerprint));const escalations=ranked.filter(x=>['EXPERIMENT_CANDIDATE','ATOMIZE','RESEARCH'].includes(x.attentionState)).slice(0,cap);return envelope({ok:true,status:'GAMECHANGER_TOURNAMENT_READY',version:GAMECHANGER_MESH_VERSION,inputCount:observations.length,uniqueCount:deduped.uniqueCount,invalid:deduped.invalid,ranked,escalations,ignoredKnownCount:deduped.uniqueCount-ranked.length,escalationAuthority:'RESEARCH_AND_PROPOSAL_ONLY',forbiddenEscalationEffects:['MESSAGE','MONEY_MOVEMENT','PURCHASE','DEPLOYMENT','CUSTOMER_STATE_MUTATION','AUTHORITY_WIDENING']});}

export function buildFrontierSignalFromGamechanger(candidate={}){if(!candidate?.fingerprint||!candidate?.observation||!candidate?.score)return envelope({ok:false,status:'GAMECHANGER_FRONTIER_SIGNAL_INVALID',reasonCodes:['ranked-candidate-required']});const o=candidate.observation;return envelope({ok:true,status:'GAMECHANGER_FRONTIER_SIGNAL_READY',signal:{id:`gamechanger:${candidate.fingerprint.slice(0,24)}`,source:o.url,observedAt:o.observedAt,summary:o.summary,evidenceRefs:candidate.evidenceRefs,domains:candidate.domains,claimedChange:`${o.title}: ${o.claims.join(' | ')||o.summary.slice(0,1200)}`,confidence:Math.max(0,Math.min(100,Math.round(candidate.score*.6+candidate.sourceTrust*.4)))},handoff:{requiredNextStages:['FRONTIER_SIGNAL_NORMALIZATION','IDEA_ATOMIZATION','THINKER_SWARM','OPPORTUNITY_OR_CAPABILITY_TOURNAMENT'],promotionAuthority:'NONE'}});}
