// Futures as structured counterfactuals, and what they are allowed to decide.
//
// The failure mode here is not bad forecasting. It is a simulated Mohamed
// acquiring a vote. Build enough plausible futures, notice that eight of ten
// "regret" a choice, and the counting starts to feel like evidence -- but the
// eight were generated by the same assumptions, so what has been measured is
// the generator, not the life.
//
// Three things follow, and they are the module:
//
//   futures are counted by lineage, never by head        (agreement is not evidence)
//   an ancestor must appear across independent lineages  (or it is one story's prop)
//   no future self outranks the present one              (perspective, not authority)
//
// The Time Telescope half is here too, because the same rule governs it: a
// consequence visible at ten years is a projection under stated assumptions,
// and widening the range is the honest response to distance, not narrowing it.
export const REACHABLE_FUTURES_VERSION = 'uberbond.reachable-futures.v1';

/** Horizons a consequence may be projected across. Ordered. */
export const HORIZONS = Object.freeze(['DAYS', 'MONTHS', 'ONE_YEAR', 'FIVE_YEARS', 'DECADES']);

/** Seats on the council. Lenses, not voters. */
export const COUNCIL_SEATS = Object.freeze([
  'NEAR_TERM', 'FIVE_YEAR', 'MIDLIFE', 'OLDER', 'PROFESSIONAL', 'CREATIVE',
  'FAMILY_ORIENTED', 'FREEDOM_SEEKING', 'HEALTH_ORIENTED', 'ADVENTUROUS'
]);

const text = (value, max = 2000) => {
  const out = String(value ?? '').trim();
  return out && out.length <= max ? out : null;
};

const fail = (status, reasonCodes, extra = {}) => ({
  ok: false, status, reasonCodes: [...new Set(reasonCodes.filter(Boolean))],
  businessEffectAuthority: 'NONE', ...extra
});

/**
 * A counterfactual future, tagged with the assumption set that produced it.
 *
 * The lineage is mandatory. Without it futures are countable, and countable is
 * exactly what they must not be.
 */
export function projectFuture(input = {}) {
  const name = text(input?.name, 240);
  const lineage = text(input?.lineage, 240);
  if (!name) return fail('FUTURE_INVALID', ['future-name-required']);
  if (!lineage) return fail('FUTURE_INVALID', ['assumption-lineage-required'], {
    note: 'A future with no stated assumption set is countable, and counting futures measures the generator.'
  });

  const requires = [...new Set((Array.isArray(input?.requires) ? input.requires : [])
    .map(item => text(item, 240)).filter(Boolean))].sort();

  return {
    ok: true,
    status: 'FUTURE_PROJECTED',
    future: {
      name,
      lineage,
      requires,
      opens: (Array.isArray(input?.opens) ? input.opens : []).map(item => text(item, 240)).filter(Boolean),
      closes: (Array.isArray(input?.closes) ? input.closes : []).map(item => text(item, 240)).filter(Boolean),
      desirable: input?.desirable === true
    },
    businessEffectAuthority: 'NONE'
  };
}

/**
 * Prerequisites shared across desirable futures -- the future ancestors.
 *
 * A capability only counts as an ancestor if it appears in futures from
 * different lineages. Appearing ten times inside one assumption set says the
 * assumption set requires it, which is a fact about the story rather than about
 * the world.
 */
export function futureAncestors(futures = []) {
  const rows = (Array.isArray(futures) ? futures : []).filter(row => row?.name && row?.lineage);
  const desirable = rows.filter(row => row.desirable);

  const byRequirement = new Map();
  for (const future of desirable) {
    for (const requirement of future.requires) {
      const entry = byRequirement.get(requirement) || { requirement, futures: [], lineages: new Set() };
      entry.futures.push(future.name);
      entry.lineages.add(future.lineage);
      byRequirement.set(requirement, entry);
    }
  }

  const ancestors = [...byRequirement.values()]
    .map(entry => ({
      requirement: entry.requirement,
      appearsIn: entry.futures,
      independentLineages: entry.lineages.size,
      // Two independent lineages is the floor. One is a prop of a single story.
      isAncestor: entry.lineages.size >= 2
    }))
    .sort((a, b) => b.independentLineages - a.independentLineages);

  return {
    ok: true,
    status: 'FUTURE_ANCESTORS_COMPILED',
    desirableFutures: desirable.length,
    lineages: new Set(desirable.map(row => row.lineage)).size,
    ancestors: ancestors.filter(row => row.isAncestor),
    singleLineageOnly: ancestors.filter(row => !row.isAncestor),
    law: 'A_REQUIREMENT_APPEARING_ONLY_INSIDE_ONE_ASSUMPTION_SET_IS_A_FACT_ABOUT_THAT_SET',
    businessEffectAuthority: 'NONE'
  };
}

/**
 * How the reachable set changes, without treating more as better.
 *
 * Optionality is not maximized here. Commitment closes branches deliberately --
 * for love, mastery, loyalty, a child -- and a module that scored closure as
 * loss would recommend against every one of them.
 */
export function reachableGeometry({ before = [], after = [], commitment = false } = {}) {
  const start = new Set((Array.isArray(before) ? before : []).map(item => text(item, 240)).filter(Boolean));
  const end = new Set((Array.isArray(after) ? after : []).map(item => text(item, 240)).filter(Boolean));

  const opened = [...end].filter(item => !start.has(item));
  const closed = [...start].filter(item => !end.has(item));

  return {
    ok: true,
    status: 'REACHABLE_GEOMETRY',
    opened,
    closed,
    preserved: [...start].filter(item => end.has(item)),
    netChange: end.size - start.size,
    // Reported, never scored. The interpretation is the founder's.
    interpretation: commitment && closed.length
      ? 'Branches were closed by a deliberate commitment. That is what commitment is, not a loss to be minimized.'
      : closed.length
        ? 'Branches closed without a stated commitment, which is worth looking at.'
        : 'No branches closed.',
    businessEffectAuthority: 'NONE'
  };
}

/**
 * Consequences projected across horizons, widening with distance.
 *
 * The refusal is the point: a decade-out projection stated as narrowly as a
 * week-out one is false precision wearing a long horizon, and long horizons are
 * exactly where false precision is least checkable.
 */
export function timeTelescope({ action = null, projections = [] } = {}) {
  const name = text(action, 240);
  if (!name) return fail('TELESCOPE_INVALID', ['action-required']);

  const rows = (Array.isArray(projections) ? projections : [])
    .map(row => ({
      horizon: HORIZONS.includes(row?.horizon) ? row.horizon : null,
      consequence: text(row?.consequence, 1000),
      rangeWidth: Number.isFinite(Number(row?.rangeWidth)) ? Number(row.rangeWidth) : null
    }))
    .filter(row => row.horizon && row.consequence);

  const narrowing = [];
  for (let i = 1; i < rows.length; i += 1) {
    const previous = rows[i - 1];
    const current = rows[i];
    if (HORIZONS.indexOf(current.horizon) <= HORIZONS.indexOf(previous.horizon)) continue;
    if (current.rangeWidth !== null && previous.rangeWidth !== null && current.rangeWidth < previous.rangeWidth) {
      narrowing.push({ from: previous.horizon, to: current.horizon });
    }
  }

  if (narrowing.length) {
    return fail('TELESCOPE_FALSE_PRECISION', ['uncertainty-must-not-narrow-with-distance'], {
      action: name, narrowing,
      note: 'A longer horizon that is more certain than a shorter one is false precision where it is least checkable.'
    });
  }

  return {
    ok: true,
    status: 'CONSEQUENCES_PROJECTED',
    action: name,
    projections: rows,
    horizonsCovered: [...new Set(rows.map(row => row.horizon))],
    truthBoundary: 'A PROJECTION IS A CONSEQUENCE UNDER STATED ASSUMPTIONS ACROSS TIME. IT IS NOT A PREDICTION OF WHAT WILL HAPPEN.',
    businessEffectAuthority: 'NONE'
  };
}

/**
 * The council of future selves: disagreement surfaced, never resolved.
 *
 * A council that returns a majority has become a vote, and a vote among
 * simulated selves is the present self being outnumbered by models of himself.
 */
export function councilOfFutureSelves({ decision = null, views = [] } = {}) {
  const question = text(decision, 1000);
  if (!question) return fail('COUNCIL_INVALID', ['decision-required']);

  const rows = (Array.isArray(views) ? views : [])
    .map(row => ({
      seat: COUNCIL_SEATS.includes(row?.seat) ? row.seat : null,
      view: text(row?.view, 1000),
      favours: text(row?.favours, 240) || null
    }))
    .filter(row => row.seat && row.view);

  const positions = new Map();
  for (const row of rows) {
    if (!row.favours) continue;
    positions.set(row.favours, [...(positions.get(row.favours) || []), row.seat]);
  }

  return {
    ok: true,
    status: 'COUNCIL_CONVENED',
    decision: question,
    views: rows,
    // Positions and who holds them -- deliberately not a tally, and no winner
    // field for a caller to reach for.
    positions: [...positions.entries()].map(([position, seats]) => ({ position, heldBy: seats })),
    disagreement: positions.size > 1,
    authority: 'THESE ARE PERSPECTIVE LENSES. NO SIMULATED FUTURE SELF OVERRIDES THE PRESENT ONE, AND NO MAJORITY IS COMPUTED.',
    businessEffectAuthority: 'NONE'
  };
}
