import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawn, spawnSync } from 'node:child_process';

export const UBERLIT_RELEASE_SCHEMA='uberbond.uberlit.release.v1';
export const UBERLIT_POINTER_SCHEMA='uberbond.uberlit.pointer.v1';
export const UBERLIT_PROCESS_SCHEMA='uberbond.uberlit.process.v1';
export const UBERLIT_BUILD_SCHEMA='uberbond.uberlit.build-receipt.v1';
export const UBERLIT_POLICY='uberlit-1.2.0';
const SHA40=/^[0-9a-f]{40}$/;const DIGEST=/^sha256:[0-9a-f]{64}$/;const ENV_NAME=/^[A-Z_][A-Z0-9_]{0,127}$/;const canonical=v=>JSON.stringify(v);const hash=v=>`sha256:${crypto.createHash('sha256').update(v).digest('hex')}`;
const exact=v=>Boolean(v&&typeof v==='object'&&!Array.isArray(v));
function atomic(file,value){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});const tmp=`${file}.tmp.${process.pid}.${crypto.randomBytes(6).toString('hex')}`;fs.writeFileSync(tmp,`${JSON.stringify(value,null,2)}\n`,{mode:0o600});fs.renameSync(tmp,file);}
function readJson(file){const s=fs.lstatSync(file);if(!s.isFile()||s.isSymbolicLink()||s.size>2_000_000)throw new Error('uberlit-unsafe-json');return JSON.parse(fs.readFileSync(file,'utf8'));}
function args(v,{empty=false}={}){if(!Array.isArray(v)||(!empty&&v.length<1)||v.length>128)throw new Error('uberlit-argv-invalid');return v.map(x=>{x=String(x??'');if(!x||x.length>4096||x.includes('\0')||/[\r\n]/.test(x))throw new Error('uberlit-argv-item-invalid');return x;});}
function envNames(v=[]){if(!Array.isArray(v)||v.length>256)throw new Error('uberlit-env-allowlist-invalid');return [...new Set(v.map(x=>String(x).trim()).filter(Boolean))].sort().map(x=>{if(!ENV_NAME.test(x))throw new Error('uberlit-env-name-invalid');return x;});}
function healthPath(v='/api/health'){v=String(v||'').trim();if(!v.startsWith('/')||v.includes('..')||v.includes('\0')||v.length>512)throw new Error('uberlit-health-path-invalid');return v;}
function port(v){v=Number(v);if(!Number.isSafeInteger(v)||v<1024||v>65535)throw new Error('uberlit-port-invalid');return v;}
function commit(v){v=String(v||'').trim().toLowerCase();if(!SHA40.test(v))throw new Error('uberlit-source-commit-invalid');return v;}
function releaseDir(root,id){if(!/^uberlit_[0-9a-f]{32}$/.test(String(id||'')))throw new Error('uberlit-release-id-invalid');return path.join(path.resolve(root),'releases',id);}
function strip(v,k){const o={...v};delete o[k];return o;}
const releaseDigest=v=>hash(canonical(strip(strip(v,'releaseId'),'releaseDigest')));const pointerDigest=v=>hash(canonical(strip(v,'pointerDigest')));const processDigest=v=>hash(canonical(strip(v,'processDigest')));const buildDigest=v=>hash(canonical(strip(v,'receiptDigest')));
function git(cwd,argv,opts={}){return execFileSync('git',argv,{cwd,encoding:'utf8',maxBuffer:64*1024*1024,...opts}).trim();}
function walk(root,base=root,out=[]){for(const name of fs.readdirSync(root).sort()){const p=path.join(root,name),rel=path.relative(base,p).split(path.sep).join('/'),s=fs.lstatSync(p);if(s.isSymbolicLink())throw new Error(`uberlit-source-symlink-refused:${rel}`);if(s.isDirectory())walk(p,base,out);else if(s.isFile())out.push({path:rel,size:s.size,digest:hash(fs.readFileSync(p))});else throw new Error(`uberlit-source-special-file-refused:${rel}`);}return out;}
function inventory(root){const files=walk(root);return{files,fileCount:files.length,totalBytes:files.reduce((n,x)=>n+x.size,0),digest:hash(canonical(files))};}
function extractTar(buffer,target){fs.mkdirSync(target,{recursive:true,mode:0o700});const r=spawnSync('tar',['-xf','-','-C',target],{input:buffer,encoding:'utf8',maxBuffer:32*1024*1024});if((r.status??1)!==0)throw new Error(`uberlit-source-extract-failed:${String(r.stderr||'')}`);}
function expectedInventoryFromArchive(archive){const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'uberlit-verify-'));try{extractTar(archive,tmp);return inventory(tmp);}finally{fs.rmSync(tmp,{recursive:true,force:true});}}

export function compileUberLitRelease({sourceCommit,buildArgv=['npm','ci'],startArgv=['node','server.mjs'],healthPath:hp='/api/health',envAllowlist=[],processRole='web'}={}){const body={schemaVersion:UBERLIT_RELEASE_SCHEMA,policyVersion:UBERLIT_POLICY,sourceCommit:commit(sourceCommit),buildArgv:args(buildArgv,{empty:true}),startArgv:args(startArgv),healthPath:healthPath(hp),envAllowlist:envNames(envAllowlist),processRole:String(processRole||'web').trim().slice(0,80),businessEffectAuthority:'NONE'};if(!body.processRole)throw new Error('uberlit-process-role-required');const d=hash(canonical(body));return{...body,releaseId:`uberlit_${d.slice(7,39)}`,releaseDigest:d};}
export function verifyUberLitReleaseManifest(m){try{if(!exact(m)||m.schemaVersion!==UBERLIT_RELEASE_SCHEMA||m.policyVersion!==UBERLIT_POLICY||!/^uberlit_[0-9a-f]{32}$/.test(String(m.releaseId||''))||!DIGEST.test(String(m.releaseDigest||''))||!SHA40.test(String(m.sourceCommit||''))||m.businessEffectAuthority!=='NONE')return false;args(m.buildArgv,{empty:true});args(m.startArgv);healthPath(m.healthPath);envNames(m.envAllowlist);const d=releaseDigest(m);return d===m.releaseDigest&&m.releaseId===`uberlit_${d.slice(7,39)}`;}catch{return false;}}
export function stageUberLitRelease({rootDir,repoDir,manifest}={}){if(!verifyUberLitReleaseManifest(manifest))throw new Error('uberlit-valid-release-manifest-required');const repo=path.resolve(repoDir),target=releaseDir(rootDir,manifest.releaseId),resolved=git(repo,['rev-parse',`${manifest.sourceCommit}^{commit}`]).toLowerCase();if(resolved!==manifest.sourceCommit)throw new Error('uberlit-exact-source-commit-required');if(fs.existsSync(target)){const v=verifyStagedUberLitRelease({rootDir,releaseId:manifest.releaseId});if(!v.ok)throw new Error('uberlit-existing-release-corrupt');return{...v,status:'UBERLIT_RELEASE_ALREADY_STAGED'};}const temp=`${target}.tmp.${process.pid}.${crypto.randomBytes(6).toString('hex')}`,source=path.join(temp,'source');fs.mkdirSync(temp,{recursive:true,mode:0o700});try{const archive=execFileSync('git',['archive','--format=tar',manifest.sourceCommit],{cwd:repo,maxBuffer:256*1024*1024}),tree=git(repo,['rev-parse',`${manifest.sourceCommit}^{tree}`]).toLowerCase();fs.writeFileSync(path.join(temp,'source.tar'),archive,{mode:0o600});extractTar(archive,source);const inv=inventory(source);const binding={sourceCommit:manifest.sourceCommit,sourceTree:tree,archiveDigest:hash(archive),sourceInventoryDigest:inv.digest,sourceFileCount:inv.fileCount,sourceTotalBytes:inv.totalBytes};binding.bindingDigest=hash(canonical(binding));atomic(path.join(temp,'manifest.json'),manifest);atomic(path.join(temp,'source.json'),binding);fs.mkdirSync(path.dirname(target),{recursive:true,mode:0o700});fs.renameSync(temp,target);}catch(e){fs.rmSync(temp,{recursive:true,force:true});throw e;}const v=verifyStagedUberLitRelease({rootDir,releaseId:manifest.releaseId});if(!v.ok)throw new Error(`uberlit-stage-postverify-failed:${v.reasonCodes.join(',')}`);return{...v,status:'UBERLIT_RELEASE_STAGED'};}
export function verifyStagedUberLitRelease({rootDir,releaseId}={}){try{const dir=releaseDir(rootDir,releaseId),m=readJson(path.join(dir,'manifest.json'));if(!verifyUberLitReleaseManifest(m)||m.releaseId!==releaseId)return{ok:false,status:'UBERLIT_RELEASE_REFUSED',reasonCodes:['release-manifest-integrity-failed']};const b=readJson(path.join(dir,'source.json')),saved=b.bindingDigest;if(!DIGEST.test(String(saved||''))||saved!==hash(canonical(strip(b,'bindingDigest')))||b.sourceCommit!==m.sourceCommit||!SHA40.test(String(b.sourceTree||''))||!DIGEST.test(String(b.archiveDigest||''))||!DIGEST.test(String(b.sourceInventoryDigest||'')))return{ok:false,status:'UBERLIT_RELEASE_REFUSED',reasonCodes:['source-binding-invalid']};const archive=fs.readFileSync(path.join(dir,'source.tar'));if(hash(archive)!==b.archiveDigest)return{ok:false,status:'UBERLIT_RELEASE_REFUSED',reasonCodes:['source-archive-digest-drift']};const expected=expectedInventoryFromArchive(archive),actual=inventory(path.join(dir,'source'));if(expected.digest!==b.sourceInventoryDigest||expected.fileCount!==b.sourceFileCount||expected.totalBytes!==b.sourceTotalBytes)return{ok:false,status:'UBERLIT_RELEASE_REFUSED',reasonCodes:['archive-inventory-binding-invalid']};for(const e of expected.files){const a=actual.files.find(x=>x.path===e.path);if(!a||a.size!==e.size||a.digest!==e.digest)return{ok:false,status:'UBERLIT_RELEASE_REFUSED',reasonCodes:[`tracked-source-drift:${e.path}`]};}return{ok:true,status:'UBERLIT_RELEASE_VERIFIED',releaseId,manifest:m,sourceTree:b.sourceTree,sourceInventoryDigest:b.sourceInventoryDigest,businessEffectAuthority:'NONE'};}catch(e){return{ok:false,status:'UBERLIT_RELEASE_REFUSED',reasonCodes:[String(e?.message||e)]};}}
function runtimeEnv(m,env,p,data){const out={PATH:process.env.PATH||'',HOME:process.env.HOME||'',TMPDIR:process.env.TMPDIR||'/tmp',LANG:process.env.LANG||'C.UTF-8',NODE_ENV:'production',PORT:String(p),DATA_DIR:data,PROCESS_ROLE:m.processRole,UBERLIT_RELEASE_ID:m.releaseId,UBERLIT_SOURCE_COMMIT:m.sourceCommit};for(const n of m.envAllowlist)if(Object.prototype.hasOwnProperty.call(env,n))out[n]=String(env[n]);return out;}
function run(argv,{cwd,env,timeout=10*60_000}={}){const r=spawnSync(argv[0],argv.slice(1),{cwd,env,encoding:'utf8',timeout,maxBuffer:32*1024*1024});return{exitCode:r.status??1,signal:r.signal||null,stdout:String(r.stdout||''),stderr:String(r.stderr||''),error:r.error?String(r.error.message||r.error):null};}
function buildPath(root,id){return path.join(releaseDir(root,id),'build-receipt.json');}
export function buildUberLitRelease({rootDir,releaseId,env=process.env,port:p=3000}={}){const v=verifyStagedUberLitRelease({rootDir,releaseId});if(!v.ok)throw new Error('uberlit-build-release-invalid');const dir=releaseDir(rootDir,releaseId),source=path.join(dir,'source'),data=path.join(path.resolve(rootDir),'data',releaseId);fs.mkdirSync(data,{recursive:true,mode:0o700});let x={exitCode:0,stdout:'',stderr:'',signal:null,error:null};if(v.manifest.buildArgv.length)x=run(v.manifest.buildArgv,{cwd:source,env:runtimeEnv(v.manifest,env,port(p),data)});const staged=verifyStagedUberLitRelease({rootDir,releaseId});if(!staged.ok)throw new Error(`uberlit-build-mutated-source:${staged.reasonCodes.join(',')}`);const builtInv=inventory(source),r={schemaVersion:UBERLIT_BUILD_SCHEMA,releaseId,sourceCommit:v.manifest.sourceCommit,sourceTree:v.sourceTree,buildArgv:v.manifest.buildArgv,exitCode:x.exitCode,signal:x.signal,error:x.error,stdoutDigest:hash(x.stdout),stderrDigest:hash(x.stderr),builtInventoryDigest:builtInv.digest,builtFileCount:builtInv.fileCount,builtTotalBytes:builtInv.totalBytes,businessEffectAuthority:'NONE'};r.receiptDigest=buildDigest(r);atomic(buildPath(rootDir,releaseId),r);if(x.exitCode!==0)throw Object.assign(new Error('uberlit-build-failed'),{receipt:r});return{ok:true,status:'UBERLIT_RELEASE_BUILT',receipt:r};}
export function verifyUberLitBuild({rootDir,releaseId}={}){try{const v=verifyStagedUberLitRelease({rootDir,releaseId});if(!v.ok)return{ok:false,reasonCodes:['release-invalid-before-build-check']};const r=readJson(buildPath(rootDir,releaseId));if(r.schemaVersion!==UBERLIT_BUILD_SCHEMA||r.releaseId!==releaseId||r.sourceCommit!==v.manifest.sourceCommit||r.sourceTree!==v.sourceTree||r.exitCode!==0||!DIGEST.test(String(r.receiptDigest||''))||r.receiptDigest!==buildDigest(r))return{ok:false,reasonCodes:['build-receipt-integrity-failed']};const inv=inventory(path.join(releaseDir(rootDir,releaseId),'source'));if(inv.digest!==r.builtInventoryDigest||inv.fileCount!==r.builtFileCount||inv.totalBytes!==r.builtTotalBytes)return{ok:false,reasonCodes:['built-filesystem-drift']};return{ok:true,status:'UBERLIT_BUILD_VERIFIED',receipt:r};}catch(e){return{ok:false,reasonCodes:[String(e?.message||e)]};}}
export function readUberLitPointer({rootDir}={}){const f=path.join(path.resolve(rootDir),'state','current.json');if(!fs.existsSync(f))return null;const p=readJson(f);if(!exact(p)||p.schemaVersion!==UBERLIT_POINTER_SCHEMA||!DIGEST.test(String(p.pointerDigest||''))||p.pointerDigest!==pointerDigest(p))throw new Error('uberlit-pointer-integrity-failed');return p;}
function writePointer(root,{releaseId,previousReleaseId,p,sourceCommit}){const body={schemaVersion:UBERLIT_POINTER_SCHEMA,releaseId,previousReleaseId:previousReleaseId||null,port:port(p),sourceCommit:commit(sourceCommit),activatedAt:new Date().toISOString(),businessEffectAuthority:'LOCAL_RUNTIME_ONLY'},ptr={...body,pointerDigest:hash(canonical(body))};atomic(path.join(path.resolve(root),'state','current.json'),ptr);atomic(path.join(path.resolve(root),'activations',`${ptr.pointerDigest.slice(7)}.json`),ptr);return ptr;}
function alive(pid){try{process.kill(pid,0);return true;}catch{return false;}}function procPath(root){return path.join(path.resolve(root),'state','process.json');}
export function readUberLitProcess({rootDir}={}){const f=procPath(rootDir);if(!fs.existsSync(f))return null;const s=readJson(f);if(!exact(s)||s.schemaVersion!==UBERLIT_PROCESS_SCHEMA||!Number.isSafeInteger(s.pid)||s.pid<=1||!DIGEST.test(String(s.processDigest||''))||s.processDigest!==processDigest(s))throw new Error('uberlit-process-state-integrity-failed');return{...s,alive:alive(s.pid)};}
export async function waitForUberLitHealth({port:p,healthPath:hp='/api/health',timeoutMs=30_000,fetchImpl=globalThis.fetch}={}){const url=`http://127.0.0.1:${port(p)}${healthPath(hp)}`,until=Date.now()+timeoutMs;let last=null;while(Date.now()<until){try{const r=await fetchImpl(url,{signal:AbortSignal.timeout(1500)}),text=await r.text();last={status:r.status,text};if(r.ok)return{ok:true,status:r.status,bodyDigest:hash(text),url};}catch(e){last={error:String(e?.message||e)};}await new Promise(r=>setTimeout(r,200));}return{ok:false,last,url};}
export function startUberLitRelease({rootDir,releaseId,port:p=3000,env=process.env}={}){const old=readUberLitProcess({rootDir});if(old?.alive)throw new Error('uberlit-process-already-running');const v=verifyStagedUberLitRelease({rootDir,releaseId});if(!v.ok)throw new Error('uberlit-start-release-invalid');const b=verifyUberLitBuild({rootDir,releaseId});if(!b.ok)throw new Error(`uberlit-verified-build-required:${b.reasonCodes.join(',')}`);const source=path.join(releaseDir(rootDir,releaseId),'source'),data=path.join(path.resolve(rootDir),'data',releaseId),logs=path.join(path.resolve(rootDir),'logs');fs.mkdirSync(data,{recursive:true,mode:0o700});fs.mkdirSync(logs,{recursive:true,mode:0o700});const logFile=path.join(logs,`${releaseId}.log`),fd=fs.openSync(logFile,'a',0o600),child=spawn(v.manifest.startArgv[0],v.manifest.startArgv.slice(1),{cwd:source,env:runtimeEnv(v.manifest,env,port(p),data),detached:true,stdio:['ignore',fd,fd]});child.unref();fs.closeSync(fd);const s={schemaVersion:UBERLIT_PROCESS_SCHEMA,releaseId,sourceCommit:v.manifest.sourceCommit,pid:child.pid,port:port(p),startedAt:new Date().toISOString(),logFile,businessEffectAuthority:'LOCAL_RUNTIME_ONLY'};s.processDigest=processDigest(s);atomic(procPath(rootDir),s);return{ok:true,status:'UBERLIT_PROCESS_STARTED',state:s};}
export async function stopUberLitProcess({rootDir,graceMs=8000}={}){const s=readUberLitProcess({rootDir});if(!s)return{ok:true,status:'UBERLIT_PROCESS_ABSENT'};if(s.alive){try{process.kill(-s.pid,'SIGTERM');}catch{try{process.kill(s.pid,'SIGTERM');}catch{}}const until=Date.now()+graceMs;while(Date.now()<until&&alive(s.pid))await new Promise(r=>setTimeout(r,100));if(alive(s.pid)){try{process.kill(-s.pid,'SIGKILL');}catch{try{process.kill(s.pid,'SIGKILL');}catch{}}}}fs.rmSync(procPath(rootDir),{force:true});return{ok:true,status:'UBERLIT_PROCESS_STOPPED',releaseId:s.releaseId};}
export async function promoteUberLitRelease({rootDir,releaseId,port:p=3000,env=process.env,healthTimeoutMs=30_000}={}){const v=verifyStagedUberLitRelease({rootDir,releaseId});if(!v.ok||!verifyUberLitBuild({rootDir,releaseId}).ok)throw new Error('uberlit-promotion-release-or-build-invalid');const previous=readUberLitPointer({rootDir});await stopUberLitProcess({rootDir});const started=startUberLitRelease({rootDir,releaseId,port:p,env}),h=await waitForUberLitHealth({port:p,healthPath:v.manifest.healthPath,timeoutMs:healthTimeoutMs});if(!h.ok){await stopUberLitProcess({rootDir});if(previous&&verifyUberLitBuild({rootDir,releaseId:previous.releaseId}).ok)startUberLitRelease({rootDir,releaseId:previous.releaseId,port:previous.port,env});throw Object.assign(new Error('uberlit-health-admission-failed'),{health:h});}const ptr=writePointer(rootDir,{releaseId,previousReleaseId:previous?.releaseId,p:p,sourceCommit:v.manifest.sourceCommit});return{ok:true,status:'UBERLIT_RELEASE_PROMOTED',pointer:ptr,process:started.state,health:h,businessEffectAuthority:'LOCAL_RUNTIME_ONLY'};}
export async function rollbackUberLitRelease({rootDir,env=process.env,healthTimeoutMs=30_000}={}){const cur=readUberLitPointer({rootDir});if(!cur?.previousReleaseId)throw new Error('uberlit-no-rollback-target');const id=cur.previousReleaseId,v=verifyStagedUberLitRelease({rootDir,releaseId:id});if(!v.ok||!verifyUberLitBuild({rootDir,releaseId:id}).ok)throw new Error('uberlit-rollback-target-invalid');await stopUberLitProcess({rootDir});startUberLitRelease({rootDir,releaseId:id,port:cur.port,env});const h=await waitForUberLitHealth({port:cur.port,healthPath:v.manifest.healthPath,timeoutMs:healthTimeoutMs});if(!h.ok)throw Object.assign(new Error('uberlit-rollback-health-failed'),{health:h});const ptr=writePointer(rootDir,{releaseId:id,previousReleaseId:cur.releaseId,p:cur.port,sourceCommit:v.manifest.sourceCommit});return{ok:true,status:'UBERLIT_RELEASE_ROLLED_BACK',pointer:ptr,health:h,businessEffectAuthority:'LOCAL_RUNTIME_ONLY'};}
export function tailUberLitLog({rootDir,releaseId,maxBytes=64_000}={}){const f=path.join(path.resolve(rootDir),'logs',`${releaseId}.log`);if(!fs.existsSync(f))return'';const s=fs.statSync(f),start=Math.max(0,s.size-Math.max(1,Math.min(Number(maxBytes)||64_000,1_000_000))),fd=fs.openSync(f,'r');try{const b=Buffer.alloc(s.size-start);fs.readSync(fd,b,0,b.length,start);return b.toString('utf8');}finally{fs.closeSync(fd);}}
